### ISSUE TITLE
Compiler internal error when creating an array out of a typeclass

### ISSUE THREAD

**Issue by ReneSac** [Araq/Nim#1131]
The following code makes the compiler crash:
```Nimrod
var x:Array[2, Tinteger] = [1, 2]

# Error: internal error: GetUniqueType
# No stack traceback available
# > Process terminated with exit code 256
```

This is probably not supposed to work, but the compiler should inform this together with the error line.

**Comment by Araq** [comment]
var x: array[2, Tinteger] = [1, 2]
echo x[0]

now compiles and runs.

**Comment by ReneSac** [comment]
Is this the expected behaviour? And is it documented?
