### ISSUE TITLE
C++ backend has issues with imported functions of type "const char *"

### ISSUE THREAD

**Issue by rbehrends** [Araq/Nim#1290]
The problem manifests trying to compile the compiler itself with the C++ backend. `gai_strerror()` is declared to return `cstring`, but per the POSIX standard actually returns a `const char *`, not a `char *`. Compiling the generated C++ code then fails when assigning the result of `gai_strerror()` to a temporary variable of type `NCSTRING` (= `char *`).

This problem will likely also occur with other types of `const` pointers.

**Comment by Araq** [comment]
This can now be fixed with c++ patterns. (Closing since this issue is a duplicate.)
