### ISSUE TITLE
Styling of code snippets needs improvement

### ISSUE THREAD

**Issue by sjakobi** [Araq/Nim#1375]
One aspect that makes the library documentation harder to read is that the name of the documented item isn't highlighted. Instead the type is highlighted which distracts the reader from what he's looking for.

Compare [a bit of Nimrod documentation](http://nimrod-lang.org/strutils.html) with a page from the [Python docs](https://docs.python.org/3/library/string.html) or the [Go docs](http://golang.org/pkg/strings/).

**Comment by Araq** [comment]
It is highlighted now.
