### ISSUE TITLE
idetools fails when the tacked file and the project file are in different directories

### ISSUE THREAD

**Issue by barcharcraz** [Araq/Nim#1397]
for a project like
root
  main.nim
    subfolder
      file.nim
a query like `nimrod idetools --trackDirty:/tmp/nimtmp.tmp,subfolder/file.nim,4,8 --suggest main.nim` will fail while a query like `nimrod idetools --trackDirty:/tmp/nimtmp.tmp,subfolder/file.nim,4,8 --suggest subfolder/file.nim` will succeed.

**Comment by Araq** [comment]
idetools has been replaced by nimsuggest.
