### ISSUE TITLE
Can't use c++ class without default constructor

### ISSUE THREAD

**Issue by cowboy-coders** [Araq/Nim#1499]
Generated code tries to call zero arg constructor when it doesn't exist. Here is a snippet of generated code illustrating the problem:

```c++
N_NIMCALL(void, use2_102046)(void) {
	test item;
	int LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NI LOC4;
	NimStringDesc* LOC5;
	NimStringDesc* LOC6;
	nimfr("use2", "clibpp.nim")
	nimln(174, "clibpp.nim");
	item = test(mult_102038);
``` 
here the class is called test. The associated Nimrod code:

```nimrod
        proc use2() =
          let item = test(mult)
```
I couldn't see a pragma that changed this behaviour.

**Comment by Araq** [comment]
Now works with latest C++ codegen.
