### ISSUE TITLE
Use custom file extension for nimrod compiler configuration files

### ISSUE THREAD

**Issue by gradha** [Araq/Nim#1555]
The current pattern for compiler configuration files is to take the current filename (example [koch.nim](https://github.com/Araq/Nimrod/blob/1da251523fb5e09d1edcd1ff37c2c993ec26273b/koch.nim)), remove the ``.nim`` extension and append ``.nimrod.cfg`` (example [koch.nimrod.cfg](https://github.com/Araq/Nimrod/blob/1da251523fb5e09d1edcd1ff37c2c993ec26273b/koch.nimrod.cfg)). While this is fine with Nimrod it [prevents other tools](http://stackoverflow.com/questions/20767891/can-macosx-register-an-uti-with-a-dot-in-the-extension) to detect this double extension.

Chances are nobody else is going to support file extensions with dots in them, so it would help to rename ``.nimrod.cfg`` to something like ``.nimcfg`` or just about anything else without a dot. It would help the people writing tools around Nimrod to recognise these files properly.

**Comment by gradha** [comment]
Will there be a deprecation path for configuration files? The last 0.10.2 version reports ``.nimrod.cfg`` usage without any deprecation warning.

**Comment by Araq** [comment]
``nimcfg`` as extension is now supported.
