### ISSUE TITLE
Codegen error with recursive variant type

### ISSUE THREAD

**Issue by EXetoC** [Araq/Nim#1700]
```nimrod
import tables

type
  E* = enum
    eX
    eY
  T* = object
    case kind: E
    of eX:
      xVal: Table[string, T]
    of eY:
      nil

proc p*(x: Table[string, T]) =
  discard
```
```
error: field ‘Xval’ has incomplete type
 struct {table111015 Xval;
                                ^
```

**Comment by akiradeveloper** [comment]
This is the same problem I am facing right now.
Araq, do you have no idea to fix this? If there is a workaround I am fine with it.

**Comment by elpres** [comment]
Same problem with this piece of code, might be a more simple test case:

```nim
import tables

type
  Node = object
    branches: Table[char, Node]

proc newNode(): Node = 
  result = Node()
  result.branches = initTable[char, Node]()

var n = newNode()
n.branches['a'] = newNode()
```

**Comment by def-** [comment]
@Araq  I don't see how this creates a type that will require infinite memory.

@akiradeveloper As a workaround you can use ref objects.

**Comment by fowlmouth** [comment]
how does this require infinite memory when a seq[T] for any T is the size of a pointer? T here should be 16 bytes big max

**Comment by Araq** [comment]
fowl: You're right there is something different going on here.
