### ISSUE TITLE
"compiler" directory is required by some Nimrod tools.

### ISSUE THREAD

**Issue by philip-wernersbach** [Araq/Nim#1706]
Some tools like c2nim use files from the "compiler" directory, but the compiler directory isn't installed when issuing a `koch install`. The workaround is to copy the compiler directory to the Nimrod install directory manually, which we have to do for Homebrew/homebrew#34693.

There should be a better system of sharing the files in compiler with the tools that need them. I'm not sure that modifying koch to do a wholesale copy of the compiler directory would be beneficial here, since the amount of tools that rely on these files is small.

**Comment by Araq** [comment]
c2nim now finally works via Nimble so I consider this fixed.

**Comment by philip-wernersbach** [comment]
Thanks! Good enough for me as a package maintainer. Eventually I'd like to see @skyfex's suggestion implemented, but that's for another day.

**Comment by reactormonk** [comment]
@philip-wernersbach In progress: https://github.com/Araq/Nim/issues/623
