### ISSUE TITLE
Non-ambiguous call considered ambiguous

### ISSUE THREAD

**Issue by flaviut** [Araq/Nim#1714]
```nimrod
proc foo[T](val: T) =
  echo val

proc foo(val: SomeInteger) =
  echo val

foo(1)
```

`test.nim(7, 3) Error: ambiguous call; both test.foo(val: T) and test.foo(val: SomeInteger) match for: (int literal(1))`

Seems similar to #907.

**Comment by Araq** [comment]
Now works and calls the right proc.
