### ISSUE TITLE
Internal error (sigmatch.nim) with 'range' constraint

### ISSUE THREAD

**Issue by gmpreussner** [Araq/Nim#1786]
type
      Foo*[N: range, T] = object  #removing ": range" fixes it
        bar: array[N, T]
     
    var m: Foo[range[1..2], float]
     
    #Error: internal error: (filename: compiler/sigmatch.nim, line: 1024)
    #No stack traceback available

**Comment by zah** [comment]
I fixed this as a by-product of a recent commit.
