### ISSUE TITLE
shallowCopy with closure iterators is broken

### ISSUE THREAD

**Issue by novist** [Araq/Nim#1803]
Using shallowCopy with closure iterators somehow corrupts stack values of that iterator.

    [18:33:22] <def-> if you set onlySafeCode = false in lib/pure/algorithm.nim it works

Sample:

    # thanks def-
    type TaskFn = iterator (): float

    iterator a1(): float {.closure.} =
        var k = 10
        while k > 0:
            echo "a1 ", k
            dec k
            yield 1.0

    iterator a2(): float {.closure.} =
        var k = 15
        while k > 0:
            echo "a2 ", k
            dec k
            yield 2.0

    var
        x = a1
        y = a2
        z: TaskFn

    discard x()
    shallowCopy(z, x)
    shallowCopy(z, y)
    discard x()

Output:

    a1 10
    a1 17

Expected output:

    a1 10
    a1 9

**Comment by Araq** [comment]
Produces 
a1 10
a1 9

on windows 32 bit, with both debug and release and -d:useSysAssert -d:useGcAssert.
which OS, C compiler?

**Comment by novist** [comment]
On mint 17.1. gcc version (Ubuntu 4.8.2-19ubuntu1) 4.8.2. I run it as:

    % nim c -d:useSysAssert -d:useGcAssert --run test.nim
    Hint: used config file '/etc/nim.cfg' [Conf]
    Hint: system [Processing]
    Hint: test [Processing]
    CC: test
    CC: system
    [Linking]
    Hint: operation successful (8779 lines compiled; 0.892 sec total; 17.174MB) [SuccessX]
    /home/user/Desktop/nim/test 
    a1 10
    a1 17

**Comment by Araq** [comment]
Assignment shows the same behaviour. Putting it all in a 'main' proc makes it work. Generated code looks correct. Weird.
