### ISSUE TITLE
Issues with the Windows installer

### ISSUE THREAD

**Issue by def-** [Araq/Nim#1804]
Today I had the chance to try the Nim Windows installer for x86_64 and noticed two minor problems:

Where you uninstall programs in Windows, the author of Nim is shown as "@[Andreas Rumpf]".
Also, you can't uninstall Nim there, have to run the uninstaller in the directory.

**Comment by def-** [comment]
Don't have access to a Windows system anymore, but something about the uninstallation not being possible.

**Comment by Araq** [comment]
I tested the uninstallation on Windows 8 multiple times and it always worked for me.

**Comment by def-** [comment]
That was on Windows 8.1, not sure if it matters or the system was just setup wrongly.

**Comment by cremno** [comment]
It's caused by `UninstallString` under `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Nim`. The path is `C:\Nim\uninst.exe`, but it should be `C:\Nim\uninstaller.exe`.
