### ISSUE TITLE
Compiler user guide has jumbled options/commands.

### ISSUE THREAD

**Issue by jpoirier** [Araq/Nim#1819]
The [compiler guide] (http://nim-lang.org/nimc.html) has some malformed parts. Specifically, idetools and serve in advanced commands and the --gc option in advanced options.

**Comment by jpoirier** [comment]
btw, I attempted to fix this myself but there's something strange happening to an indented line that immediately follows the "//idetools ..." and "//serve .." lines, but an un-indented line is fine though. And based on the text layout in doc/advopt.txt the intention is to indent the options list for idetools and serve.

**Comment by dom96** [comment]
What's malformed about it?

**Comment by jpoirier** [comment]
The output in the advanced command section is malformed.

**Comment by jpoirier** [comment]
The output should look something like the following:
```
idetools                   compiler support for IDEs: possible options:
    --track:FILE,LINE,COL            track a file/cursor position
    --trackDirty:DIRTY_FILE,ORIG_FILE,LINE,COL
                                    track a file, currently not saved to disk
    --suggest                       suggest all possible symbols at position
    --def                           list all possible definitions at position
    --context                       list possible invokation context
    --usages                        list all usages of the symbol at position
    --eval                          evaluates an expression
  serve                   start the compiler as a service mode (CAAS)
    --server.type:TYPE              either stdin or tcp
    --server.port:PORT              port for tcp mode, by default 6000
    --server.address:HOST           binds to that address, by default ""
```

**Comment by keyle** [comment]
This is because of .replace("//", "") of some of the commands.

it shifts the description text two characters to the left causing that tabbing to be off for some lines.

Since I have no idea why there is a // in front of certain commands, I am not sure the best approach to fix it.
