### ISSUE TITLE
extra slash in url requests in httpclient

### ISSUE THREAD

**Issue by devzero** [Araq/Nim#1823]
```
import httpclient

echo(getContents("http://foo.com/dir1/"))
```

Causes a request for "//dir1/" if you look at it in wireshark.  Many webservers just play nice with this, but it's broken.  The root cause is in lines 297,349, and 445 of lib/pure/httpclient.nim where it adds a slash.  r.path is supposed to contain a base slash already (at least according to the test cases in uri.nim).

**Comment by dom96** [comment]
Does this also happen with the async http client?

**Comment by c-rack** [comment]
@dom96 Not to my knowledge.
