### ISSUE TITLE
Fix names - nimrod -> nim in /icons/

### ISSUE THREAD

**Issue by V01D-eXe** [Araq/Nim#1827]
The ChangeLog shows that  -
`The language has been renamed from Nimrod to Nim. The name of the compiler changed from nimrod to nim too.`
But the icons and resource files in /icons folder have not been renamed yet.
They need to be renamed and the build scripts and installation scripts need to be fixed in accordance with the new names.

**Comment by Araq** [comment]
Icons have been renamed.
