### ISSUE TITLE
Nim 0.10.2 Setup [32bit windows] - Error : connecting to host 

### ISSUE THREAD

**Issue by V01D-eXe** [Araq/Nim#1828]
Nim 0.10.2 Setup [32bit windows] - 
`Error : connecting to host`
while downloading either of docs, mingw , aporia. 
Also tried running as admin and installing to another drive.
Setup downloaded from http://nim-lang.org/download.html  
![nim](https://cloud.githubusercontent.com/assets/8255054/5595437/43361042-9298-11e4-94f9-0387c7c9cb0d.png)  
Not related to firewall or any internet related problem from my side. 
Windows x64 setup works fine. 
Looks like a problem in the installation scripts.

**Comment by dom96** [comment]
CC @Varriount

**Comment by V01D-eXe** [comment]
Well, I tried the same installer today and it worked. So I don't know what the problem had been. But if someone else doesn't get this problem, I think this can be closed down.

**Comment by Varriount** [comment]
I'm not getting any errors when running the installer on my system, even with all the components enabled.

**Comment by V01D-eXe** [comment]
I think that it is possible that my antivirus created the problem. That's the only thing that could have happened. Because some antivirus usually have problem with everything, they just delete anything downloaded be a downloader and then the installer gives an error.

**Comment by reactormonk** [comment]
Because most antivirus are based on signatures, e.g. file hashes. Maybe one of the x32 files sparked a false positive.
