### ISSUE TITLE
`items` for `Slice` makes `toSeq` fail

### ISSUE THREAD

**Issue by homeworkprod** [Araq/Nim#1839]
I have encountered some strange behaviour (in Nim 0.10.2) when trying to create a sequence from a slice of integers:

```nim
from sequtils import toSeq

# This works.
let s1 = toSeq(1..4)

# This fails.
let r: Slice[int] = 1..4
let s2 = toSeq(r)
```

This fails:
```
Error: type mismatch: got (Slice[int])
but expected one of: 
system.items(a: cstring): iter[char]
system.items(a: seq[T]): iter[T]
system.items(a: string): iter[char]
system.items(E: typedesc[enum]): iter[typedesc[enum]]
system.items(a: array[IX, T]): iter[T]
system.items(a: set[T]): iter[T]
system.items(a: openarray[T]): iter[T]
```

I tried to overload `system.items` for `Slice` (until now, the `openarray`-accepting variant seems to have been called):
```nim
iterator items*[T](a: Slice[T]): T {.inline.} =
  ## iterates over each item of `a`.
  var i = a.a
  while i <= a.b:
    yield i
    inc(i)
```
(According to Araq, high-to-low slices are not supported. The docs state that `..` is just an alias for `countup`.)

With the new `items` overload, this error occurs:
```
Error: type mismatch: got (seq[Slice[int]], int)
but expected one of: 
system.add(x: var string, y: cstring)
system.add(x: var string, y: char)
system.add(x: var seq[T], y: T)
system.add(x: var string, y: string)
system.add(x: var seq[T], y: openarray[T])
```

The implementation of the `toSeq` template (https://github.com/Araq/Nim/blob/devel/lib/pure/collections/sequtils.nim#L309) uses `seq[type(iter)]`. However, `type(1..4)` doesn't return `int` as expected, but raises an error (in interactive mode):
```
>>> type(1..4)
stdin(6, 8) Error: ')' expected
stdin(6, 6) Error: type mismatch: got (typedesc[int], int literal(4))
but expected one of: 
system...(a: T, b: T): Slice[T]
system...(b: T): Slice[T]

stdin(6, 10) Error: invalid indentation
stdin(6, 10) Error: expression expected, but found ')'
```

As a result, the `for` loop in `toSeq` seems to work, but the following call to `add` fails as it is passed an unexpected (and unreasonable) type of sequence (`seq[Slice[int]]` instead of `seq[int]`; see my comment on `type(1..4)` above):
```
Error: type mismatch: got (seq[Slice[int]], int)
but expected one of: 
system.add(x: var string, y: cstring)
system.add(x: var string, y: char)
system.add(x: var seq[T], y: T)
system.add(x: var string, y: string)
system.add(x: var seq[T], y: openarray[T])
```

**Comment by Araq** [comment]
But toSeq takes an iterator, even if you add an items for the Slice[int], ``r`` is not an iterator, so it cannot work.

**Comment by homeworkprod** [comment]
Just closing this as WONTFIX feels dissatisfying to me; especially since you tagged this as "high priority" and "showstopper".

So, even if this currently technically does not/could not work: *shouldn't* this work? In my initial example, directly passing a slice to `toSeq` works, so I'd expect it to work when passing it indirectly, i.e. after declaring a local variable, too.

Maybe this issue has become too technical and lost focus on the user's point of view. If there is another way besides overloading `items`, I'm looking forward to it.

**Comment by Araq** [comment]
Oh it's not WONTFIX, there never was a bug in the first place. Showstopper and high priority only means I need to look at it before the next release, which is what I did.

> *So, even if this currently technically does not/could not work: shouldn't this work?*

No, cause that's not how toSeq works.

> *In my initial example, directly passing a slice to toSeq works*
No, you don't pass a slice, you pass an iterator invocation.

> *If there is another way besides overloading items, I'm looking forward to it.*

So overload ``toSeq`` for your Slice[int].
