### ISSUE TITLE
Compiler should use Idents instead of Syms for macros.quote

### ISSUE THREAD

**Issue by def-** [Araq/Nim#1843]
As shown here: https://stackoverflow.com/questions/27750045/statement-list-composition/27750779

quote from macros module is rather difficult to use as it already does translations of Idents to Syms. I think all Syms should be Idents still.

I could figure out that semQuoteAst in compiler/semexprs.nim gets called, from there semExpandToAst(c: PContext, n: PNode) is probably responsible, but from then on it's black magic for me, so I can't fix this on my own.

**Comment by dyu** [comment]
Your answer on SO failed to compile btw.
```nim
import macros

proc symsToIdents(n): PNimrodNode {.compiletime.} =
    if n.kind == nnkSym:
        return newIdentNode($n)

    result = n
    for i in 0 .. <result.len:
      result[i] = symsToIdents(n[i])

macro test: stmt =
    var first = quote do:
        var x = 1
    var second = quote do:
        echo x

    result = newStmtList()
    first.copyChildrenTo(result)
    second.copyChildrenTo(result)
    result = symsToIdents(result)

test
```
I get:
```
Hint: 'x' is declared but not used [XDeclaredButNotUsed]
SIGSEGV: Illegal storage access.
```

I'm at nim devel (4 days old from HEAD)

**Comment by def-** [comment]
Strange, I'm on devel from today, compiles.

**Comment by dyu** [comment]
Turns out, i name the file "quote.nim" and that triggers the error.

**Comment by dom96** [comment]
@dyu you should report that as a separate bug

**Comment by zah** [comment]
Arguably, not a bug. See my comments in the stackoverflow thread.
