### ISSUE TITLE
Range checker too restrictive

### ISSUE THREAD

**Issue by mrordinaire** [Araq/Nim#1845]
```nim
var arr = [3,2,1,5,4]

# bubble sort
for i in low(arr)..high(arr):
  for j in i+1..high(arr): # Error: unhandled exception: value out of range: 5 [RangeError]
    if arr[i] > arr[j]:
      let tmp = arr[i]
      arr[i] = arr[j]
      arr[j] = tmp
```

Here the compiler throws an error, saying `j` can be out of range of `arr`. However, `j` can never be so as it is bounded by `high(arr)`.

**Comment by reactormonk** [comment]
No, it isn't really. There's the edge case where i is 4, and i+1 5. In
that case, you're running `range(5,4)` for a range which is defined as
`TRange[0..4]`, because it's derived from the array. It's just
catching the error a bit earlier that you'd expect, because it would
fail later when you're requesting `arr[j]`.

    for i in low(arr)..high(arr):
      echo i+1
      for j in i+1..high(arr):
        echo j

**Comment by mrordinaire** [comment]
With the following program, the executable compiled with `nim c --rangeChecks=on file.nim` throws a `RangeError` while the executable compiled with `nim c --rangeChecks=off file.nim` runs perfectly fine.

```Nim
var arr = [3,2,1,5,4]

for i in low(arr)..high(arr):
  echo i
  for j in i+1..high(arr): # Error: unhandled exception: value out of range: 5 [RangeError]
    echo "  ", j
```

**Comment by dom96** [comment]
Yeah but you are trying to do the following:

```nimrod
var arr = [3,2,1,5,4]
for j in 5..high(arr):
  echo "  ", j
```

And ``high(arr)`` is equal to 4. So what would you like that for loop to do in that situation?

**Comment by reactormonk** [comment]
Probably nothing.

**Comment by mrordinaire** [comment]
Precisely. I want' that `for` loop to do nothing in the case where `i == 4`. Otherwise, the simple code for bubble sort will have to be transformed into the following, which is not really nice and probably not as efficient.

```nim
var arr = [3,2,1,5,4]

# bubble sort
for i in low(arr)..high(arr):
  var j = i+1
  while j <= high(arr):
    if arr[i] > arr[j]:
      let tmp = arr[i]
      arr[i] = arr[j]
      arr[j] = tmp
    j += 1
```

One possible fix is to put `high(arr)` into a variable but that just increases the burden of the programmer.

**Comment by dom96** [comment]
Alright. I'll reopen this and we'll see what @Araq has to say about it.

**Comment by Araq** [comment]
This is actually a bug in the definition of the countup iterator. Fixing it requires some type selection magic though. :-/
