### ISSUE TITLE
Issues using `is` with types in the form "A[X] or B[X]"

### ISSUE THREAD

**Issue by MasonMcGill** [Araq/Nim#1853]
```nim
type SeqOrSet[E] = seq[E] or set[E]
type SeqOfInt = seq[int]
type SeqOrSetOfInt = SeqOrSet[int]

# This prints "false", which seems less correct that (1) printing "true" or (2)
# raising a compiler error.
echo seq is SeqOrSet

# This prints "false", as expected.
echo seq is SeqOrSetOfInt

# This prints "true", as expected.
echo SeqOfInt is SeqOrSet

# This causes an internal error (filename: compiler/semtypes.nim, line: 685).
echo SeqOfInt is SeqOrSetOfInt
```

The same errors occur when `seq` and `set` are replaced with user-defined types.

**Comment by gmpreussner** [comment]
echo seq is SeqOrSet

I would not expect 'true' here. SeqOrSet is a set, but not vice versa, imho. On the other hand, if SeqOrSet was a type class, then I would expect 'true', i.e.:

   type SeqOrSet[E] = generic s
       (s is seq[E]) or (s is set[E])

Anyway, I may be wrong :)

**Comment by MasonMcGill** [comment]
@gmpreussner: I'm not sure that's right. Not everything in the class "set or sequence" is a set, but every set is a member of the class "set or sequence". `seq is SeqOrSet` also needs to be true to stay consistent with how `or` and `is` work with non-generic types...
```nim
type IntOrStr = int or string

assert(int is IntOrStr)      # Every integer is either an integer or a string.
assert(not(IntOrStr is int)) # Not every integer and every string is an integer.
```
and how `is` works with generic types.
```nim
assert(seq[int] is seq)      # Every sequence of integers is a sequence.
assert(not(seq is seq[int])) # Not every sequence is a sequence of integers.
```

**Comment by gmpreussner** [comment]
@MasonMcGill: You are right - I had it the wrong way around.

**Comment by aboisvert** [comment]
BTW, `echo seq is SeqOrSet` is still printing `false`.  

(I wasn't sure if it was expected that it would change to `true` but at least that was my expectation :))

**Comment by Araq** [comment]
@aboisvert The 'is' operator is still broken, but at least it's not braindead anymore.
