### ISSUE TITLE
doc2 does not produce documentation for procs ending with an expression

### ISSUE THREAD

**Issue by BlaXpirit** [Araq/Nim#1854]
Using `nim doc2`, functions consisting of one line and without `return` statement are missing their description (documentation comment).

Example:

```nim
proc `<`*(a, b: Time): bool =
  ## *Returns*: whether ``a`` is earlier than ``b``
  a.microseconds < b.microseconds
```
And more: [source](https://github.com/BlaXpirit/nim-csfml/blob/a9732fd4f2084756cc9ec16fcc2cc671633f32b6/src/csfml_system.nim#L108) vs [doc](https://cdn.rawgit.com/BlaXpirit/nim-csfml/6df9060486c42aceec72afa71c80d74c6eb31295/csfml_system.html#==,Vector2i,Vector2i)

**Comment by Araq** [comment]
Works for me now.

**Comment by Araq** [comment]
Reopen if still a problem.
