### ISSUE TITLE
Remind user when compiling in debug mode

### ISSUE THREAD

**Issue by philip-wernersbach** [Araq/Nim#1868]
Release settings should be the default. We get far too many "OMGWTFBBQ Nim is so slow!" comments from users, only to have the code in question run with C-like speed when the "-d:release" switch is used. This isn't the users' faults either, most compiled languages use Release settings by default but allow the user to disable optimizations and enable debugging with compiler options. Nim does the opposite by using Debug settings by default.

**Comment by Araq** [comment]
Tutorial 1 "The first program" mentions -d:release already. With ``-d:release`` as the default we would get way too many crashes instead of "Index out of bound" errors with *more* unhappy users.

> *This isn't the users' faults either, most compiled languages use Release settings by default*

No. GCC doesn't default to O3. In fact, I don't know of any compiler that defaults to release settings.

**Comment by philip-wernersbach** [comment]
> No. GCC doesn't default to O3. In fact, I don't know of any compiler that defaults to release settings.

Java and Visual Studio optimize and don't produce debugging information by default. GCC, Clang, et al. don't optimize by default, but they don't produce debugging information by default either.

**Comment by reactormonk** [comment]
How about a "you're compiling in debug mode, for speed activate `-d:release`"?

**Comment by Varriount** [comment]
Hm, that sounds good. But where would this be printed (and would you be able to turn it off)?

Putting a message at the beginning of compilation is no good, as the user is unlikely to see it (since all the compilation messages get in the way), so perhaps at the end? And then there could be an option in the compiler config to turn the message off? Or a switch?

**Comment by reactormonk** [comment]
How about put it into koch as an option which you provide which enables the notification, and have that option in the "how to install"? That way new people get the notification and you can disable it by having your own `./koch boot` line in the shell history.

**Comment by Araq** [comment]
> Java and Visual Studio optimize and don't produce debugging information by default. 

My Visual Studio defaults to the "debug" profile. Java doesn't count as a traditional compiled language but it defaults to producing stack traces and e.g. IndexOutOfBoundsExceptions too.

**Comment by zielmicha** [comment]
Maybe we could add information about compilation mode to current final line:

```
Hint: successfully compiled in debug mode (use -d:release for release builds) (18936 lines compiled; 1.056 sec total; 31.322MB)
```
instead of
```
Hint: operation successful (18936 lines compiled; 1.056 sec total; 31.322MB)
```

**Comment by Araq** [comment]
@zielmicha That's a good idea but officially the compiler doesn't know about the ``release`` switch, it's implemented in the config. But oh well, so it's an official switch then who cares.

**Comment by Varriount** [comment]
Well, the '-d:release' flag doesn't have to be mentioned.

**Comment by philip-wernersbach** [comment]
Adding a reminder about compiling in debug mode is a good way to go here. I'd still argue that release mode should be the default, but @Araq does have a point that disabling bounds checking by default would be worse for users.

The only thing about this is that the reminder has to be at the end of every compilation, and it should be on its own line like:

Hint: Operation successful...
Notice: Compiled with debug settings. Use release settings for release builds

**Comment by triplefox** [comment]
I didn't know -d:release existed or was relevant to me because I didn't look at the tutorials, I just went straight to the language reference. I would be happy with a hint indicating that I am using debug settings(this matches my expectations for the rest of Nim's behavior).

**Comment by Varriount** [comment]
So @araq has expressed hesitation with having the compiler directly state "debug" and "release" mode, as the compiler doesn't technically know about these - it only knows what checks and flags are modified via command line and configuration file. 

Following this thought, what about giving a warning when some or all runtime checks are enabled, stating that the program might not run optimally?

**Comment by reactormonk** [comment]
Would it be possible to let the config file `nim/config/nim.cfg` say something?

**Comment by philip-wernersbach** [comment]
@Varriount: In my mind, the warning shouldn't depend on the presence of any certain flag, just that one or more of the runtime checks are enabled in the compiler.

**Comment by Varriount** [comment]
Hmm,  so when the program has compiled, print out a message with the major compilation options and their status?

**Comment by reactormonk** [comment]
Too long imo.

**Comment by philip-wernersbach** [comment]
In my opinion the message should just be "`Notice: Debug options are enabled. Use release options for release builds.`", and then leave it as an exercise for the user to read the documentation and call it a day.
