### ISSUE TITLE
Nim 0.10.2 syntax error for previously valid code

### ISSUE THREAD

**Issue by gradha** [Araq/Nim#1875]
Some of the files from [lazy_rest](https://github.com/gradha/lazy_rest) won't compile with v0.10.2, they compile fine with v0.9.6. To test, run the following commands:

	$ git clone https://github.com/gradha/lazy_rest.git
	$ cd lazy_rest
	$ git checkout 73e5a34d175033e35603991f7ea02a9a5eaa4cec
	$ nim c lazy_rest_c_api.nim
	lazy_rest_c_api.nim(230, 33) Error: ')' expected

[Line 230](https://github.com/gradha/lazy_rest/blob/73e5a34d175033e35603991f7ea02a9a5eaa4cec/lazy_rest_c_api.nim#L230) doesn't do anything fancy, so probably the previous code is at fault.

**Comment by Araq** [comment]
'func' is now a keyword.
