### ISSUE TITLE
POSIX_SPAWN_USEVFORK in osproc requires GNU

### ISSUE THREAD

**Issue by def-** [Araq/Nim#1881]
https://github.com/Araq/Nim/blob/devel/lib/pure/osproc.nim#L716
POSIX_SPAWN_USEVFORK is only available when __USE_GNU is set:

spawn.h:
```c
/* Flags to be set in the `posix_spawnattr_t'.  */
#define POSIX_SPAWN_RESETIDS		0x01
#define POSIX_SPAWN_SETPGROUP		0x02
#define POSIX_SPAWN_SETSIGDEF		0x04
#define POSIX_SPAWN_SETSIGMASK		0x08
#define POSIX_SPAWN_SETSCHEDPARAM	0x10
#define POSIX_SPAWN_SETSCHEDULER	0x20
#ifdef __USE_GNU
# define POSIX_SPAWN_USEVFORK		0x40
#endif
```
This makes tcc fail to compile. Not sure what's the best way to avoid this. just setting USE_GNU makes other parts fail, but only setting it for spawn.h works.

**Comment by Araq** [comment]
So? Import it like so: 

```nimrod
const POSIX_SPAWN_USEVFORK = 0x40
```

Who cares if the header file thinks it's a good idea this magic number.
