### ISSUE TITLE
No exception message with cpp

### ISSUE THREAD

**Issue by def-** [Araq/Nim#1888]
When compiling with `nim cpp min` `getCurrentExceptionMsg()` returns an empty string:
```nim
try:
  raise newException(ValueError, "Need odd and >= 3 digits")
except ValueError:
  echo getCurrentExceptionMsg()
```

**Comment by def-** [comment]
The problem is that in the generated C++ code `currexception_16645` is never assigned anything.

**Comment by def-** [comment]
Even better, there is no exception being thrown now.

**Comment by Araq** [comment]
I think it is thrown, but caught.

**Comment by achataignier** [comment]
I investigated this issue a bit. A C++ exception is actually thrown and catched, but no Nim exception is pushed in the try block, nor set in the catch block, so there is no "currentException" in the Nim exception functions ( getCurrentExceptionMsg() is one of them). I think the logical fix is to add a call to setcurrentexception() in the catch block, as the exception handling relies upon native C++ exceptions handlers, so there is no need to push or pop any exceptions, this is natively done by C++. What is your opinion on this ?

Here is the currently generated -buggy- C++ code with the latest Nim devel branch, generated from your example code above. I'll try to propose a fix in the next days.

``` c++
	try {
		Valueerror3449* e_92005;
		NimStringDesc* LOC2;
		e_92005 = 0;
		nimln(2265, "system.nim");
		e_92005 = (Valueerror3449*) newObj((&NTI22601), sizeof(Valueerror3449));
		(*e_92005).m_type = (&NTI3449);
		nimln(2266, "system.nim");
		LOC2 = 0;
		LOC2 = (*e_92005).message; (*e_92005).message = copyStringRC1(((NimStringDesc*) &TMP140));
		if (LOC2) nimGCunrefNoCycle(LOC2);
		nimln(2, "nim1888.nim");
		throw NimException(e_92005, "ValueError");
	} catch (NimException& TMP139) {
	setFrame((TFrame*)&FR);
	if (isObj(TMP139.exp->m_type, (&NTI3449))) 	{
		NimStringDesc* LOC4;
		nimln(4, "nim1888.nim");
		LOC4 = 0;
		LOC4 = getcurrentexceptionmsg_86637();
		printf("%s\015\012", LOC4? (LOC4)->data:"nil");
	}
	else 	{
		throw;
	}
```

**Comment by achataignier** [comment]
Just saw you have solved this issue in the meantime, thanks.
