### ISSUE TITLE
5e4ae8d breaks our SDL app with no traceback

### ISSUE THREAD

**Issue by dustinlacewell** [Araq/Nim#1899]
As of https://github.com/Araq/Nim/commit/5e4ae8dbb4f5e3ca8cf8c1fb356ca0f500f32746 our game no longer runs and we get the following output:

> nim c -r lightsout
> config/nim.cfg(45, 2) Hint: added path: '/home/dlacewell/.babel/pkgs/' [Path]
> config/nim.cfg(46, 2) Hint: added path: '/home/dlacewell/.nimble/pkgs/templates-0.1' [Path]
> config/nim.cfg(46, 2) Hint: added path: '/home/dlacewell/.nimble/pkgs/random-0.2.4' [Path]
> config/nim.cfg(46, 2) Hint: added path: '/home/dlacewell/.nimble/pkgs/nimble-0.4.0' [Path]
> config/nim.cfg(46, 2) Hint: added path: '/home/dlacewell/.nimble/pkgs/csfml-0.1.0' [Path]
> config/nim.cfg(46, 2) Hint: added path: '/home/dlacewell/.nimble/pkgs/gtk2-1.0' [Path]
> config/nim.cfg(46, 2) Hint: added path: '/home/dlacewell/.nimble/pkgs/x11-1.0' [Path]
> config/nim.cfg(46, 2) Hint: added path: '/home/dlacewell/.nimble/pkgs/irc-0.1.0' [Path]
> config/nim.cfg(46, 2) Hint: added path: '/home/dlacewell/.nimble/pkgs/sdl2-1.0' [Path]
> config/nim.cfg(46, 2) Hint: added path: '/home/dlacewell/.nimble/pkgs/opengl-1.0' [Path]
> config/nim.cfg(46, 2) Hint: added path: '/home/dlacewell/.nimble/pkgs/' [Path]
> Hint: used config file '/home/dlacewell/dev/nim/Nim/config/nim.cfg' [Conf]
> Hint: used config file '/home/dlacewell/dev/nim/lights-out/nim.cfg' [Conf]
> Hint: system [Processing]
> Hint: lightsout [Processing]
> Hint: magic [Processing]
> Hint: colors [Processing]
> Hint: strutils [Processing]
> Hint: parseutils [Processing]
> Hint: tables [Processing]
> Hint: hashes [Processing]
> Hint: math [Processing]
> Hint: times [Processing]
> Hint: sdl [Processing]
> Hint: unsigned [Processing]
> SIGSEGV: Illegal storage access. (Try to compile with -d:useSysAssert -d:useGcAssert for details.)

The source to the game is available at: https://github.com/dustinlacewell/lights-out

**Comment by dustinlacewell** [comment]
Here is the output from compiling with a debug release: 
https://gist.github.com/62855fb88c14bee46304

**Comment by reactormonk** [comment]
Works here, x64 linux. Although the "press X to Y" text doesn't disappear after hitting enter.

**Comment by Araq** [comment]
Fixed due to the reversal of commit 5e4ae8d.
