### ISSUE TITLE
Incorrect 'discard' usage inside case blocks generates misleading compiler error

### ISSUE THREAD

**Issue by gmpreussner** [Araq/Nim#1904]
When calling procs inside case blocks and discarding their return value, the compiler thinks that not all cases are covered:

    proc foo(): int = 666

    var i = 0
    case i # Error: not all cases are covered
    of 0: echo "0"
    of 1:
      foo discard
    else:
      echo "foobar"

Not discarding the return values of function calls inside case works.

**Comment by cowboy-coders** [comment]
shoudln't that be:

```nimrod
proc foo(): int = 666

var i = 0
case i # Error: not all cases are covered
of 0: echo "0"
of 1:
  discard foo()
else:
  echo "foobar"

```
?

**Comment by gmpreussner** [comment]
@cowboy-coders: You're right, I have it swapped. In that case it would reduce to a misleading error message. I can't try it right now, but will check tonight whether that fixes it. Thanks!

**Comment by gmpreussner** [comment]
I verified that `discard foo()` works fine. I renamed the subject of this issue accordingly.

**Comment by Araq** [comment]
The 'discard' ends the 'case' statement prematurely. You're right it's a confusing error message but we cannot do better for now.
