### ISSUE TITLE
terminal / eraseScreen() throws an OverflowError

### ISSUE THREAD

**Issue by keyle** [Araq/Nim#1906]
Nim Compiler Version 0.10.2 (2014-12-30) [Windows: amd64]

```nimrod
import terminal

echo "yo?"
eraseScreen()
```

```
yo?
Traceback (most recent call last)
[...]
terminal.nim(190)        eraseScreen
Error: unhandled exception: over- or underflow [OverflowError]
```

**Comment by keyle** [comment]
More info

this only happens because my buffer size is bigger than windows size (it scrolls)

If I set my buffer size to be equal to my window size, there is no overflow error.

![image](https://cloud.githubusercontent.com/assets/9749/5660333/c21c43fa-976a-11e4-939a-e678f479159b.png)

**Comment by keyle** [comment]
This is a work around for windows only:

```nimrod
import os, terminal

discard execShellCmd("cls")
setCursorPos(0, 0)
```

maybe that should be implemented in terminal.nim for the when defined("windows") ?
https://github.com/Araq/Nim/blob/master/lib/pure/terminal.nim#L183

**Comment by keyle** [comment]
Found more information... with a buffer width of 150 and a buffer height of 218, it won't throw a OverflowError. However with Y = 219 it will.

So with X * Y 

- 32700 passes
- 32850 fails

So it appears somewhere we use a *short* and we should use a *int* (I don't think having a buffer of 218+ lines on windows' cmd is outrageous)

I would fix it if I knew where to fix it :)

any ideas?

**Comment by Varriount** [comment]
We can't use anything larger, as we are limited by the integer size the underlying windows functions can take. THis can be worked around by clearing portions of the screen, one at a time.
