### ISSUE TITLE
Incorrect assembler generated

### ISSUE THREAD

**Issue by JinShil** [Araq/Nim#1907]
The following procedure in nim:
```
proc sysWrite*(arg1: int, arg2: pointer, arg3: int) : int =
    asm """ 
        "syscall" 
        : "=a"(`result`) 
        : "a" (1), "D"(`arg1`), "S"(`arg2`), "m"(`arg2`), "d"(`arg3`) 
        : "memory", "cc", "rcx", "r11" 
    """
```
generates the following C code:
```
N_NIMCALL(NI, syswrite_1003)(NI arg1, void* arg2, NI arg3) {
	NI result;
	result = 0;
	asm(        "syscall" 
"        : "=a"(result) \n"
"        : "a" (1), "D"(arg1), "S"(arg2), "m"(arg2), "d"(arg3) \n"
"        : "memory", "cc", "rcx", "r11" \n"
);
	return result;
}
```
I don't think those quotes and \n characters are supposed to be there. 

However, if I put the assembly all on one line...
```
proc sysWrite*(arg1: int, arg2: pointer, arg3: int) : int =
    asm """ "syscall" : "=a"(`result`) : "a" (1), "D"(`arg1`), "S"(`arg2`), "m"(`arg2`), "d"(`arg3`) : "memory", "cc", "rcx", "r11" """
```
then the generated assembly code in the C file is good and compiles fine:
```
N_NIMCALL(NI, syswrite_1003)(NI arg1, void* arg2, NI arg3) {
	NI result;
	result = 0;
	asm( "syscall" : "=a"(result) : "a" (1), "D"(arg1), "S"(arg2), "m"(arg2), "d"(arg3) : "memory", "cc", "rcx", "r11" 
);
	return result;
}
```

Forgive me if I'm mistaken, I'm quite new to Nim.

**Comment by reactormonk** [comment]
Found it, but I have no idea if it breaks something.


    diff --git a/compiler/ccgstmts.nim b/compiler/ccgstmts.nim
    index 6c7d40d..00d3e58 100644
    --- a/compiler/ccgstmts.nim
    +++ b/compiler/ccgstmts.nim
    @@ -938,7 +938,7 @@ proc genAsmOrEmitStmt(p: BProc, t: PNode, isAsmStmt=false): PRope =
             # ignore empty lines
             app(result, "\"")
             app(result, x)
    -        app(result, "\\n\"\n")
    +        app(result, "\"\n")
       else:
         res.add(tnl)
         result = res.toRope

**Comment by Araq** [comment]
Other workaround: No whitespace after the colon.
