### ISSUE TITLE
wrong field names of compatible tuples in generic types

### ISSUE THREAD

**Issue by lyro** [Araq/Nim#1910]
Consider the following two variables:

```nim
import tables

var p : OrderedTable[tuple[a:int], int]
var q : OrderedTable[tuple[x:int], int]
```
The following code compiles:
```nim
for key in p.keys:
  echo key.a
```
However, this code does not:
```nim
for key in q.keys:
  echo key.x
```
**nim 0.10.2** shows the error "Error: undeclared identifier: 'x'"
Instead, the field of the keys of `q` seems to be called `a`, too, i.e. the following code does compile:
```nim
for key in q.keys:
  echo key.a
```
Note that the field of `q` is correctly named `x` if we change the tuple type so that both tables have different types, i.e. this does compile, too
```nim
import tables

var p : OrderedTable[tuple[a:int], int]
var q : OrderedTable[tuple[x:Natural], int]

for key in p.keys:
  echo key.a
for key in q.keys:
  echo key.x
```

**Comment by Araq** [comment]
That is a consequence of the fact that tuple names do not matter anymore. I wonder if we should revert this to the old version of the spec.

**Comment by lyro** [comment]
Well, I find it very surprising that a tuple field has to be accessed by a different name. In particular because the two variables could be defined in completely different places, even in different modules. For me it would be ok that tuples with the same type and different names are compatible in the sense that variables of one type can be used whenever one of the other type is expected. But the type of the variable should determine the name of the fields.
