### ISSUE TITLE
List comprehension macro only supports infix checks as guards

### ISSUE THREAD

**Issue by jouni-kantola** [Araq/Nim#1920]
The boolean guard infix checks, [1st](https://github.com/Araq/Nim/blob/master/lib/pure/future.nim#L146) and [2nd](https://github.com/Araq/Nim/blob/master/lib/pure/future.nim#L158), in the list comprehension macro invalidates quite a few type of guards.

I commented out the expectations, which allowed this:
```nim
proc isEven(x: int): bool =
  x mod 2 == 0
echo lc[x | (x <- 1..10, x.isEven), int]
echo lc[x | (x <- 1..10, not isEven(x)), int]
```

I appreciate the list comprehensions and it would be useful to be able to guard in other styles than infix.

**Comment by def-** [comment]
The first one should stay, but the second has to be removed indeed.

**Comment by jouni-kantola** [comment]
Yeah, I agree; only the check on [line 158](https://github.com/Araq/Nim/blob/master/lib/pure/future.nim#L158) is an issue.
