### ISSUE TITLE
float literals

### ISSUE THREAD

**Issue by esheldon** [Araq/Nim#1927]
float literals seem to need a digit after the decimal place in order to get parsed correctly.  e.g. "15.0" compiles but "15." fails to compile.

```
let
    # compiles
    x1 = 15.0
    # fails to compile with Error: invalid indentation
    x2 = 15.
```

**Comment by Araq** [comment]
Yes. because 1.foo(a, b) works and I never liked that floating point literals can be shortened to the point of obscurity.
