### ISSUE TITLE
Devel build broken on Mac?

### ISSUE THREAD

**Issue by keyle** [Araq/Nim#1932]
See the bottom of this

http://hastebin.com/elenevogut.md

Mac OS X 10.6.8 (snow leopard) x86_64

**Comment by Araq** [comment]
Please also submit a stack trace produced by GDB. Edit the build script for that so that it compiles with ``-g``.

**Comment by keyle** [comment]
@Araq http://hastebin.com/wefayofobu.md Is this what you need?

Let me know - thanks

**Comment by flaviut** [comment]
@keyle 
Not quite, he wants a stack trace for the segfault:
```console
$ gdb bin/nim
> run c koch
 ...
> bt
 ...
> quit
```

**Comment by sillesta** [comment]
Works for me on 10.10 x86_64.
```
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
```

**Comment by keyle** [comment]
yep, here it is

http://hastebin.com/otivivogah.coffee
http://hastebin.com/lejusucoyo.pl

**Comment by Araq** [comment]
Cannot reproduce.
