### ISSUE TITLE
split(string, ...) don't work as expected

### ISSUE THREAD

**Issue by flaviut** [Araq/Nim#1933]
The precedent (see [perl][], [javascript][]) is for an empty splitter to split the string into characters.

- `split(string, Regex)` returns the whole input
- `split(string, string)` gets stuck in an infinite loop

While Nim might not want to follow the precedent, `split(string, Regex)` and `split(string, string)` should at least have identical behavior.

[perl]: man7.org/linux/man-pages/man3/pcreapi.3.html
[javascript]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split

**Comment by Araq** [comment]
I'm not even sure this counts as a bug. Don't use an empty splitter.

**Comment by flaviut** [comment]
Of course it counts as a bug: if two functions are named "split", they then should have same behavior for the same input.

**Comment by Araq** [comment]
Not for edge cases.

**Comment by flaviut** [comment]
This seems to be a symptom of the underlying `findall` function mishandling the case where the match is of length 0.

**Comment by Varriount** [comment]
Either way, the split procedure probably shouldn't cause an infinite loop. Python throws an exception when str.split's separator is empty, other languages separate the string into chars. Which behavior should strutils.split adopt?

**Comment by flaviut** [comment]
In case people want the Perl/Javascript split-into-characters, I have some code at https://github.com/flaviut/nre/blob/master/src/nre.nim#L387-L424 that might come in handy during implementation.

**Comment by Araq** [comment]
This has been fixed, I think.
