### ISSUE TITLE
FreeBSD compiler is wrong

### ISSUE THREAD

**Issue by sa2ajj** [Araq/Nim#1934]
I've been trying to build Nim on FreeBSD (adding a build slave for @Varriount build farm).  (For the record, I'm using FreeBSD 10.1.)

It looks like the current `build.sh` script in `c_sources` wants gcc as the compiler.  It's not available in the base system (it was replaced by clang) and even if I update the script to use `gcc48`, only the first stage would succeed: `bin/nim c koch` would fail with `gcc: not found` error.

I wonder what is the right way to change the compiler (be it `gcc48` if we really want to use it, or `clang`, which is available in the base system).

FWIW, clang's version:

```
$ clang --version
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.1
Thread model: posix
```

**Comment by reactormonk** [comment]
clang is also the compiler for the os X port, so use that one.

**Comment by sa2ajj** [comment]
That's what I tried and, as I said, the first phase was successful (`cd csources && sh build.sh`).

The problem appears on the next phase -- `bin/nim c koch`.

**Comment by Varriount** [comment]
I just want to add, this is preventing me from adding FreeBSD to the buildbot site.

**Comment by Araq** [comment]
So use ``cc=clang`` in the nim config file?

**Comment by sa2ajj** [comment]
@Araq, this _somehow_ works for the manual build.  But we aim to do it automatically.

As far as I understand, I'd need to modify `config/nim.cfg` file in a way similar to Mac OSX:

```
@if macosx:
  cc = clang
...
```

But I am not sure what symbol should be checked.

**Comment by sa2ajj** [comment]
Right, `nimrod.cfg` has

```
@if macosx or freebsd:
...
```

Trying that.

**Comment by sa2ajj** [comment]
Somehow helped.

The next error is after running `./koch boot -d:release`:

```
[Linking]
clang: error: no such file or directory: 'usr/home/bbnim/tempo/Nim/compiler/nimcache/jsgen.o'
clang: error: no such file or directory: 'usr/home/bbnim/tempo/Nim/compiler/nimcache/cgen.o'
clang: error: no such file or directory: 'usr/home/bbnim/tempo/Nim/compiler/nimcache/vmgen.o'
clang: error: no such file or directory: 'usr/home/bbnim/tempo/Nim/compiler/nimcache/vm.o'
clang: error: no such file or directory: 'usr/home/bbnim/tempo/Nim/compiler/nimcache/sem.o'
Error: execution of an external program failed
FAILURE
```

All these files exist.

Second run of `./koch boot -d:release` gives:

```
[Linking]
usr/home/bbnim/tempo/Nim/compiler/nimcache/cgen.o: In function `cgenwritemodules_593360':
usr/home/bbnim/tempo/Nim/compiler/nimcache/cgen.c:(.text+0x273d5): undefined reference to `writemapping_203894'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of an external program failed
FAILURE
```

I'm not sure how to proceed further.

**Comment by Araq** [comment]
This is a known bug on the BSDs I think. Please try ``--parallelBuild:1`` as a workaround. ``osproc`` can run processes in parallel but it seems to be broken on BSD.

**Comment by sa2ajj** [comment]
Yes, adding `--parallelBuild:1` to `./koch boot -d:release` helped to build it w/o problem.

**Comment by sa2ajj** [comment]
I'm not sure though that if this helps with the original goal: building Nim on FreeBSD w/ Buildbot.

**Comment by Araq** [comment]
ParallelBuild on FreeBSD has been fixed by now.
