### ISSUE TITLE
Website has filename collisions

### ISSUE THREAD

**Issue by gradha** [Araq/Nim#1949]
When a user goes to http://nim-lang.org/lib.html and follows the [rst](http://nim-lang.org/rst.html) module link they will reach the forum's quick reference instead of the documentation for the ``rst`` module.

**Comment by dom96** [comment]
Yeah. The docs should really be placed in a ``docs`` dir IMO.

**Comment by Araq** [comment]
Well now they are versionized so the problem is gone.
