### ISSUE TITLE
Can´t compile if file location contains spaces on Windows

### ISSUE THREAD

**Issue by yonson2** [Araq/Nim#1955]
As the title says, the gcc version that the Nim installer for windows ships (4.9.1 x86_64-win32-seh-rev1) can´t correctly process files if there are spaces on its location. gcc gives various `No such file or directory` and `fatal error: no input files` errors and then the compilation is terminated.

Removing all spaces from the file location fixes the issue.

**Comment by Varriount** [comment]
What happens with paths with spaces on Linux? 

A fix for this would be to escape/quote the input files when Nim invokes gcc
