### ISSUE TITLE
httpclient.HttpMethod should not be an enum

### ISSUE THREAD

**Issue by gdmoore** [Araq/Nim#1962]
Hi,

HttpMethod is currently defined as an enum. This actually doesn't correctly model the method as defined by the HTTP spec: the method can be one of the values listed in the enum, ''or'' an extension method: http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html

As a practical example, having HttpMethod defined as an enum breaks being able to use httpclient to implement a WebDAV client (since there is no way to issue COPY, LOCK, MOVE, etc).

I would suggest changing the type to a string, which would allow for WebDAV (and whatever other extension methods) to specify the method as needed.

**Comment by dom96** [comment]
The functions should instead take an HttpMethod or a string.

**Comment by gdmoore** [comment]
This does fix the issue but usage is a bit clunky. The previous usage method took the enum and stripped off the "http" prefix, making the enum "httpGET" actually issue a "GET".

The submitted change means you must pass a string prefixed with "http" still. eg to do a GET, I have to `request("httpGET")`. This is extra clunky for WebDAV where I would need to write `request("httpCOPY")`, in order to actually request using the "COPY" method.

It's clear to you and me now but I think this will be a point of confusion for people using this library in the future.

**Comment by dom96** [comment]
I agree. Please submit a PR to fix this.
