### ISSUE TITLE
Compiling for Standalone AVR broken in 0.10.2

### ISSUE THREAD

**Issue by timfoden** [Araq/Nim#1964]
When I compile a simple Hello World example for an embedded AVR (standalone) the compile fails with a type mismatch error in system.nim (299, 46).

This can be reproduced on Windows using the following source files:

U:\>type hello.nim
``` nimrod
echo "Hello, World!"
```

U:\>type panicoverride.nim
``` nimrod
proc printf(frmt: cstring) {.varargs, importc, header: "<stdio.h>", cdecl.}
proc exit(code: int) {.importc, header: "<stdlib.h>", cdecl.}

{.push stack_trace: off, profiler:off.}

proc rawoutput(s: string) =
  printf("%s\n", s)

proc panic(s: string) =
  rawoutput(s)
  exit(1)

{.pop.}
```

U:\>nim --version
Nim Compiler Version 0.10.2 (2014-12-30) [Windows: i386]
Copyright (c) 2006-2014 by Andreas Rumpf

U:\>nim c -c --cpu:avr --os:standalone --deadCodeElim:on hello.nim
c:\dev\nim\config\nim.cfg(45, 2) Hint: added path: 'C:\Users\dwfntfoden\.babel\p
kgs\' [Path]
c:\dev\nim\config\nim.cfg(46, 2) Hint: added path: 'C:\Users\dwfntfoden\.nimble\
pkgs\' [Path]
Hint: used config file 'c:\dev\Nim\config\nim.cfg' [Conf]
Hint: system [Processing]
c:\dev\nim\lib\system.nim(299, 46) Error: type mismatch

**Comment by Araq** [comment]
Who said 'echo' works for os:standalone?
