### ISSUE TITLE
for loop over iterator does not function as expected when lo==high

### ISSUE THREAD

**Issue by gdmoore** [Araq/Nim#1971]
```
var start = 0
var end = 0
for i in start..end:
  echo($i)
```
This is a contrived example for simplicity. I ran into this while repeatedly building a buffer of random data for testing.

Summary:
 * if end is > start, the loop runs (as expected)
 * if end is < start, the loop does not run at all (as expected)
 * if end == start, the loop runs a single time (**unexpected**)

In the third case I would expect the loop to run zero times, since I'm iterating over an empty range. Your thoughts?

**Comment by gdmoore** [comment]
For clarification: I can see it making sense either way. 

The current behaviour is the opposite of what I'd expect in Python.

If this is a design decision then it would be great to have it more explicit in the documentation on iterating.

**Comment by ReneSac** [comment]
Yes, nim behaves different from python. The for loop runs `while start <= l_end`. That is why you must do `for i in 0 .. x.len - 1` or `for i in 0 .. <x.len` or `for i in 0 .. x.high` when iterating over an array. 

When your `end` is 1, the loop runs two times, not really what you would expect from python.

**Comment by gdmoore** [comment]
Fair enough. Tutorial 1 does give some examples showing that `for countup(1,10)` is the same as `while i <= 10` but I think it would be good to annotate the manual section on the for statement with your description, for clarity. Especially the ` a .. <b` syntax, which is very simple but easy to miss.

** for loops run while start <= l_end **

**Comment by reactormonk** [comment]
The file is in `doc/tut1.txt`, feel free to add it.

**Comment by BlaXpirit** [comment]
Don't be fooled by slicing, though. `"abc"[0 .. <0] == "abc"`
