### ISSUE TITLE
Enums with holes are iterable

### ISSUE THREAD

**Issue by def-** [Araq/Nim#1982]
The manual states here http://nim-lang.org/manual.html#enumeration-types :
```nim
type
  TokenType = enum
    a = 2, b = 4, c = 89 # holes are valid
```
> However, it is then not an ordinal anymore, so it is not possible to use these enums as an index type for arrays. The procedures inc, dec, succ and pred are not available for them either.

But I can iterate over this:
```nim
for i in TokenType.low .. TokenType.high:
  echo i
```
Either the documentation should be updated or the implementation fixed.

**Comment by EXetoC** [comment]
I think it should be possible in one way or another, but the current implementation is very slow since it iterates through every integer between low and high.

**Comment by flaviut** [comment]
related #1239

**Comment by def-** [comment]
Ok, it's a duplicate.

**Comment by timotheecour** [comment]
now possible via [add enumutils.items for sparse enums, typetraits.SomeSparseEnum by timotheecour · Pull Request #17080 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/17080)
