### ISSUE TITLE
Passing overloaded symbols to templates fails inside generic procedures

### ISSUE THREAD

**Issue by MasonMcGill** [Araq/Nim#1988]
Sometimes when I read the titles of these bug reports I feel like what I'm trying to do is complicated enough that I'm kind of asking for bugs...

Anyway, here's the code example:

```nim
template t(e: expr) = discard

proc positive(x: int): int = +x
proc negative(x: int): int = -x
proc negative(x: float): float = -x

proc p1 = t(negative)
proc p2[X] = t(positive)
proc p3[X] = t(negative)

p1()      # This compiles.
p2[int]() # This compiles.
p3[int]() # This raises an error.
```

And the error (coming from the definition of `p3`):

```
type mismatch: got (proc (int): int{.gcsafe, locks: 0.} | proc (float): float{.gcsafe, locks: 0.})
but expected one of: 
test.t(e: expr): stmt
```

**Comment by MasonMcGill** [comment]
A small note, per @Araq's request:

This is currently blocking me. I'm currently working on a few libraries that define `map`, `fold`, etc. as templates that accept predicates as expression parameters. A couple examples of why this is done:

- ``someTuple.map(`$`)`` should work even if `someTuple` contains fields of different types.
- The performance of `lazySourceOfInts.map((e: int) => e + 1).collect()` slows down by a factor of 5 or so if the predicate is accepted as a procedure pointer rather than an expression. Using expressions, it's as fast as the explicit loop.

This bug renders these sorts of templates are more-or-less unusable inside generic code, which is a pretty harsh restriction, especially if you're writing libraries.

**Comment by Araq** [comment]
Should be easy to fix.

**Comment by MasonMcGill** [comment]
Awesome. That'll be really helpful.
