### ISSUE TITLE
calling a large number of macros doing some computation fails

### ISSUE THREAD

**Issue by lyro** [Araq/Nim#1989]
Consider the following code
```nim
import pegs, macros

proc parse*(fmt: string): int {.nosideeffect.} =
  let p =
    sequence(capture(?sequence(anyRune(), &charSet({'<', '>', '=', '^'}))),
             capture(?charSet({'<', '>', '=', '^'})),
             capture(?charSet({'-', '+', ' '})),
             capture(?charSet({'#'})),
             capture(?(+digits())),
             capture(?charSet({','})),
             capture(?sequence(charSet({'.'}), +digits())),
             capture(?charSet({'b', 'c', 'd', 'e', 'E', 'f', 'F', 'g', 'G', 'n', 'o', 's', 'x', 'X', '%'})),
             capture(?sequence(charSet({'a'}), *pegs.any())))
  var caps: Captures
  return fmt.rawmatch(p, 0, caps)

macro test(s: string{lit}): expr =
  result = newIntLitNode(parse($s))

# the following line is repeated 7463 times
echo test("abc")
echo test("abc")
echo test("abc")
...
```
Compiling this code with nim 10.2 failes with the following error message:
```
nim c test
Hint: used config file '/path/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: test [Processing]
Hint: pegs [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: unicode [Processing]
Hint: macros [Processing]
stack trace: (most recent call last)
test.nim(18)             test
test.nim(15)             parse
lib/pure/pegs.nim(647)   rawMatch
test.nim(7482, 9) Info: instantiation from here
lib/pure/pegs.nim(647, 22) Error: interpretation requires too many iterations
```
The compilation does not fail if the line `echo test("abc")` is repeated only 7462 times.

I assume this problem is caused by some safeguard so that calling macros cannot lead to infinite loops. However, each single call is fast and I would expect that the count starts again from 0 each time a new toplevel macro is called.

The code above is only an example. I ran into the issue in some real code using the (inofficial) `strfmt` package, which used `pegs` in very much the same way. In this case far less than 7463 calls to a strfmt-macro are required in order to get this error. Is there a way to enlarge the iteration bound?

**Comment by Varriount** [comment]
Would a compiler switch specifying the iteration limit work?

**Comment by lyro** [comment]
I think this would at least be a good (temporary?) solution.

**Comment by Araq** [comment]
The internal counter should be resetted properly.
