### ISSUE TITLE
Compiling iterator with object assignment in release mode causes "var not init"

### ISSUE THREAD

**Issue by jyapayne** [Araq/Nim#2023]
I found an issue while compiling the following code in release mode:

test_iter.nim:
```
type
    Obj = object
        iter: iterator (): int8 {.closure.}

iterator test(): int8 {.closure.} =
    yield 7

proc init():Obj=
    result.iter = test

var o = init()
echo(o.iter())
```

When compiled with `nim c -r test_iter.nim`, it prints `7` as expected, but when run with `nim c -r -d:release test_iter.nim`, it prints the following error:

```
test_iter.nim(5, 9) Error: internal error: expr: var not init test_89031
No stack traceback available
```

Am I doing something wrong?

**Comment by reactormonk** [comment]
Stacktrace:

    nim.nim(91)              nim
    nim.nim(55)              handleCmdLine
    main.nim(251)            mainCommand
    main.nim(62)             commandCompileToC
    modules.nim(203)         compileProject
    modules.nim(151)         compileModule
    passes.nim(193)          processModule
    passes.nim(137)          processTopLevelStmt
    cgen.nim(1327)           myProcess
    ccgstmts.nim(1055)       genStmts
    ccgexprs.nim(2042)       expr
    ccgstmts.nim(1055)       genStmts
    ccgexprs.nim(2061)       expr
    ccgstmts.nim(227)        genVarStmt
    ccgstmts.nim(210)        genSingleVar
    ccgstmts.nim(76)         loadInto
    ccgcalls.nim(470)        genAsgnCall
    ccgcalls.nim(143)        genPrefixCall
    cgen.nim(587)            initLocExpr
    ccgexprs.nim(1948)       expr
    cgen.nim(890)            genProc
    cgen.nim(860)            genProcNoForward
    cgen.nim(787)            genProcAux
    ccgstmts.nim(1055)       genStmts
    ccgexprs.nim(2042)       expr
    ccgstmts.nim(1055)       genStmts
    ccgexprs.nim(2067)       expr
    ccgstmts.nim(1049)       genAsgn
    ccgstmts.nim(87)         loadInto
    ccgexprs.nim(2040)       expr
    ccgexprs.nim(1852)       genStmtListExpr
    ccgexprs.nim(2057)       expr
    ccgexprs.nim(1829)       genClosure
    cgen.nim(587)            initLocExpr
    ccgexprs.nim(1966)       expr
    msgs.nim(832)            internalError
    msgs.nim(809)            liMessage
    msgs.nim(714)            handleError

**Comment by reactormonk** [comment]
The dead code elimination goes haywire here. The error is reproducible with `--deadCodeElim:on`, but disappears when explicitly disabled via `--deadCodeElim:off`.

**Comment by Araq** [comment]
Is that a regression?

**Comment by reactormonk** [comment]
Backtrace on master (c754365):

    nim.nim(91)              nim
    nim.nim(55)              handleCmdLine
    main.nim(273)            mainCommand
    main.nim(73)             commandCompileToC
    modules.nim(204)         compileProject
    modules.nim(152)         compileModule
    passes.nim(193)          processModule
    passes.nim(137)          processTopLevelStmt
    sem.nim(434)             myProcess
    sem.nim(408)             semStmtAndGenerateGenerics
    semstmts.nim(1313)       semStmt
    semexprs.nim(845)        semExprNoType
    semexprs.nim(2127)       semExpr
    semstmts.nim(1114)       semProc
    semstmts.nim(1055)       semProcAux
    transf.nim(787)          transformBody
    lambdalifting.nim(949)   liftLambdas
    lambdalifting.nim(824)   transformOuterProcBody
    lambdalifting.nim(928)   transformOuterProc
    lambdalifting.nim(716)   outerProcSons
    lambdalifting.nim(865)   transformOuterProc
    lambdalifting.nim(727)   liftIterSym
    system.nim(2164)         FieldDiscriminantCheck
    Error: unhandled exception: assignment to discriminant changes object branch [FieldError]

**Comment by Araq** [comment]
that means nothing, that is an unrelated bug that was fixed in the meantime.

**Comment by jyapayne** [comment]
I know this is unrelated, but how do you get the more in-depth stacktrace? Next time I file an issue, I would like to include this.

**Comment by reactormonk** [comment]
https://github.com/reactormonk/nim/commit/fb1f15476fb3414763adb9abb05cb428fabf0484

**Comment by Varriount** [comment]
@jyapane I'm going to assume that you're using the Windows installer distribution. Either use the nim_debug executable, or bootstrap the compiler in debug mode (No -d:release )

**Comment by jyapayne** [comment]
Awesome, thanks @Varriount :)

**Comment by def-** [comment]
Now the random library doesn't compile anymore, even without -d:release:

```nim
import random
```

```
.nimble/pkgs/random-0.3.0/random.nim(141, 9) Error: internal error: expr: var not init mtRandomBytes_138513
```
