### ISSUE TITLE
re() defaults

### ISSUE THREAD

**Issue by axbender** [Araq/Nim#2028]
When using re() the defaults for "flags" is {reExtended, reStudy}, which prevents you from defining REs containing spaces (yes, we could use \s) with the re"..." notation. I believe that using spaces in REs is very common and as such "reExtended" should be removed from the default.

**Comment by axbender** [comment]
An alternative would be to allow flags to be added to re"" expressions like re"..."i (for reIgnoreCase).

**Comment by Araq** [comment]
reExtended should be the default as non-extended regexes are horrible. Nim sometimes tries to make the world a better place. Also changing the default now would break code.

**Comment by axbender** [comment]
Now, that's your call...
What about extending the syntax as proposed?

**Comment by Araq** [comment]
Extending the syntax is not desirable. Note that 're' is no special case in Nim's syntax, foo"abc" is a shortcut for  foo("abc") everywhere.

**Comment by axbender** [comment]
How would I write re(r"...", {}) using the re"..." syntax - re"..."({}) doesn't work? Could you point me to the docs describing this special syntax?
I'd really love to use the "short" re"..." syntax with the ability to provide a flags value...

**Comment by gradha** [comment]
You can use the [method call syntax](http://nim-lang.org/manual.html#method-call-syntax) to invert the order of the parameters and pass extra ones, or you can write a small wrapper for your preferred parameters:
```nimrod
proc reI(s: string): TRegex {.inline.} = re(s, {reIgnoreCase})

proc test() =
  let
    foo = "bar".re({reIgnoreCase})
    bar = "foo".reI
```

**Comment by axbender** [comment]
@gradha: I'm aware of the method call syntax and macros. But Araq's explanation does - IMHO - not directly fall under that category. re"..." obviously is an abbreviation for re(r"...", {<defaults>}) - mind the special interpretation of re"..." as raw string and the selection of the default flags parameter; so, converting re(...) using MCS, results in r"...".re({<flags>}). Thus re"..." seems to be some kind of special syntax (which seems to have no place for the flags parameter)...
No pun intended, just trying to clear things out.

**Comment by Araq** [comment]
I improved the docs. So I consider this issue closed.
