### ISSUE TITLE
String/array indexing with negative indexes?

### ISSUE THREAD

**Issue by elpres** [Araq/Nim#2029]
Negative indexes work in slices (as in `"abc"[0.. -2] == "ab"`), but trying to access the last character with `"abc"[-2]` (or `-1`, although that would probably technically point to the terminating zero) seems to actually read the memory before the beginning of the string. That seems inconsistent.

**Comment by dom96** [comment]
This is done for performance reasons.

**Comment by Varriount** [comment]
Also, there's a planned change to the negative inside behavior.

**Comment by elpres** [comment]
Is the planned changed documented somewhere? I'm curious.

Unless adding support for this would have forbidding costs, I think it's worth doing since the compiler supports negative indexes for slices, and not being able to use them for the same purpose while indexing seems arbitrary and inconsistent from language design point of view.
