### ISSUE TITLE
Prepend for singly linked rings is broken

### ISSUE THREAD

**Issue by def-** [Araq/Nim#2034]
In lists.nim:

```nim
proc prepend*[T](L: var SinglyLinkedRing[T], n: SinglyLinkedNode[T]) = 
  ## prepends a node `n` to `L`. Efficiency: O(1).
  if L.head != nil: 
    n.next = L.head    
    L.head.next = n
  else: 
    n.next = n
  L.head = n
```
`L.head.next = n` is wrong. It should be `L.last.next = n` but we don't have last.

Remove single linked rings, since that prepend seems to be about the only proc for them? Or add a reference to the last element?

**Comment by Araq** [comment]
SinglyLinkedRing should get head and tail fields.
