### ISSUE TITLE
fatal error: string.h: No such file or directory

### ISSUE THREAD

**Issue by ckkashyap** [Araq/Nim#2038]
When I try to compile https://github.com/ckkashyap/nim-xv6/blob/master/uart.nim I get fatal error: string.h: No such file or directory. From what I gather, it's for the call to strlen that gets generated.

I looked for string.h and found one here - Nim/tinyc/win32/include - and ofcourse, putting that in the include path got rid of the problem. I was just wondering though if that is the right path to include (particularly because of "win32" in the path - I am using mac and linux).

**Comment by ckkashyap** [comment]
I was facing the problem on my mac - when I checked on Linux I realized that string.h is expected to be on the system.

**Comment by reactormonk** [comment]
How did you fix it?

**Comment by ckkashyap** [comment]
I did not. I assumed that string.h was missing from my mac because I built only gcc cross compiler and not g++. I have not built g++ on mac yet (been running into some build issues)

**Comment by Tangoyzx** [comment]
Did you fix it?

**Comment by ckkashyap** [comment]
I did not fix it ... I've been working on Linux mostly and this does not
seem to be an issue there...

Regards,
Kashyap

**Comment by timmyjose** [comment]
For anyone facing the same issue on macOS (especially after an update), run the following command in a terminal - `xcode-select --install`. That should fix the issue with clang not finding header files.

**Comment by eliasjpr** [comment]
I had to run the following command for Mojave after installing the latest command line tools `xcode-select --install`

`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`
