### ISSUE TITLE
Script for regression testing

### ISSUE THREAD

**Issue by reactormonk** [Araq/Nim#2046]
The script should compare two commits (passed as argument) and display differences in test results on the compiler. This helps identifying if a change introduced a regression bug.

It should fetch the test results if available via the buildbot [e.g.](http://buildbot.nim-lang.org/test-data/linux-x64-builder/014be3a29c7c4691cde5b446a04fe522e008ea34/) to reduce build time.

**Comment by reactormonk** [comment]
The script could make use of the merger. https://github.com/Araq/Nim/issues/1696

**Comment by Araq** [comment]
Do it, or leave it but don't spam the issue tracker.
