### ISSUE TITLE
invalid pragma: header: "<gio/gio.h>"

### ISSUE THREAD

**Issue by dark-yux** [Araq/Nim#2048]
The pragma is in the documentation. Why is it invalid?

**Comment by Araq** [comment]
Because you have to attach it to a proc or a type or a var. it's not a top level statement so dependencies can be tracked more easily.

**Comment by reactormonk** [comment]
E.g. https://github.com/Araq/Nim/blob/devel/lib/wrappers/joyent_http_parser.nim#L62-L63
