### ISSUE TITLE
Nakefile fails to compile with weird error line number

### ISSUE THREAD

**Issue by gradha** [Araq/Nim#2056]
The nakefile for [dropbox_filename_sanitizer](https://github.com/gradha/dropbox_filename_sanitizer) refuses to compile with nim 0.10.2 or 0.10.3. To reproduce:
```
$ git clone https://github.com/gradha/dropbox_filename_sanitizer.git
$ cd dropbox_filename_sanitizer
$ git checkout 52ada4dcb5e0fcb39b2631d29b7dbed85c7b4bd8
$ nimble build
$ nake
…
nakefile.nim(378, 2) Error: value of type 'bool' has to be discarded
```
That line points at a [docstring](https://github.com/gradha/dropbox_filename_sanitizer/blob/52ada4dcb5e0fcb39b2631d29b7dbed85c7b4bd8/nakefile.nim#L378), so I don't know where the problem is. Any suggestions?

**Comment by Araq** [comment]
It's the last test_shell() call in that proc.

**Comment by gradha** [comment]
So having to discard a [discardable proc](https://github.com/gradha/dropbox_filename_sanitizer/blob/52ada4dcb5e0fcb39b2631d29b7dbed85c7b4bd8/nakefile.nim#L365) is not a bug then? Ok.
