### ISSUE TITLE
Add `try: except: else:`

### ISSUE THREAD

**Issue by flaviut** [Araq/Nim#2063]
It'd be nice if the following worked:

```nimrod
try:
  echo "123"
except:
  echo "fail"
else:
  echo "success"
# outputs "success"
try:
  raise newException(Excepltion, "failed")
except:
  echo "fail"
else:
  echo "success"
# outputs "fail"
```

**Comment by Varriount** [comment]
What benefit does this have?

**Comment by reactormonk** [comment]
What is the difference to

    try:
      echo "123"
      echo "success"
    except:
      echo "fail"
    # outputs "success"

**Comment by Araq** [comment]
Workaround: 

```nim

try:
  echo "123"
except:
  echo "fail"
  return
echo "Success"
```

**Comment by flaviut** [comment]
@reactormonk The primary advantage is mental separation. Sometimes it makes sense to separate them. Good point about that example, I should sleep before submitting a ticket.

@Araq That doesn't have the same semantics. I might not want to leave the function at the time.
