### ISSUE TITLE
Invalid Objective-C code generated when calling class method

### ISSUE THREAD

**Issue by philip-wernersbach** [Araq/Nim#2068]
[This is the Gist of the problem.](http://gist.github.com/philip-wernersbach/025530cd63312c41d6d9)

I'm attempting to port [MinimalistCocoaApp](http://www.cocoawithlove.com/2010/09/minimalist-cocoa-programming.html) to Nim. [Line 27 of minimalist_cocoa_app.nim](http://gist.github.com/philip-wernersbach/025530cd63312c41d6d9#file-minimalist_cocoa_app-nim-L27) generates [line 120 of minimalist_cocoa_app.m](http://gist.github.com/philip-wernersbach/025530cd63312c41d6d9#file-minimalist_cocoa_app-m-L120), which is invalid. The line should generate:
```
LOC2 = [NSApp setActivationPolicy:0];
```

**Comment by Araq** [comment]
ah excellent! Now I can improve 'importobjc'. Thanks.
