### ISSUE TITLE
generic regression

### ISSUE THREAD

**Issue by fowlmouth** [Araq/Nim#2073]
This code used to compile, now it gives this error
`t2.nim(12, 28) Error: A nested proc can have generic parameters only when it is used as an operand to another routine and the types of the generic paramers can be infered from the expected signature.`
```nim
import json,strutils,glossolalia,future

grammar(JsonNode):

  number := num_int or num_float

  digit := chr({'0'..'9'})
  digits := digit.repeat(1)
  
  num_int := 
  #  digits.save do (m:string)->JsonNode: newJInt(m.parseInt)
    digits.save((m:string)->JsonNode => newJInt(m.parseInt))

  num_float := (digits and chr('.') and digits).save do (m:string)->JsonNode: newJfloat(m.parseFloat)

echo number.match("42")
```
the commented version (`do` syntax) works fine. the library is at https://github.com/fowlmouth/glossolalia

**Comment by Araq** [comment]
This is because arrow like operators are now right associative.

**Comment by dom96** [comment]
So more parenthesis are required? Doesn't that just make this worse?
