### ISSUE TITLE
Make tuples implicitly cast to an anonymous tuple without field names

### ISSUE THREAD

**Issue by apriori** [Araq/Nim#208]
A tuple should be considered a mere named view of a struct and be implicitly convertible to an anonymous variant and also to other tuples with same layout. This way one can write generic procs etc. for just a tuple layout and not a specific named layout and wouldn't need actually energing type casts. Overload resolution could prefer the specific named variant over the anonymous one, though I don't quite know a real useful usecase for that.

**Comment by Araq** [comment]
Has been implemented as far as reasonable.
