### ISSUE TITLE
Result not initialised leads to segfault.

### ISSUE THREAD

**Issue by oderwat** [Araq/Nim#2082]
I tried something and ended up with a crash which reproduces like this:
```
proc foo(s: string): string =
    #result = ""
    result.add(s)

echo foo "bar"
```
It compiles fine and crashes on execution:

```
Traceback (most recent call last)
compiler_bug_1.nim(5)    compiler_bug_1
compiler_bug_1.nim(3)    foo
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed
```
As I am new to Nim I am not sure if this is considered a bug or is just the expected result of not initialising "result" myself?
> Nim Compiler Version 0.10.3 (2015-02-07)

**Comment by dom96** [comment]
This is not a Nim bug. All vars are initialised to binary 0 which means that strings and sequences need to be explicitly initialised.

**Comment by def-** [comment]
You can use `not nil` if you want enforced initialization (at least the compiler gives a warning so far):

```nimrod
proc foo(s: string): string not nil =
  #result = ""
  result.add(s)

echo foo "bar"
```
```
a.nim(3, 2) Warning: Cannot prove that 'result' is initialized. This will become a compile time error in the future. [ProveInit]
```

**Comment by oderwat** [comment]
OK. I just was not sure because I thought this should not segfault. It works for objects but I guess strings have their own rules.

```
type MyObject = object
    a: int
    b: int


proc foo(a, b: int): MyObject =
    result.a = 1
    #result.b = 2

echo foo(1,2) # (a:1, b:0)
```

For string return "result = nil" for object return "result = (ref?)object" that just made me wonder.

**Comment by def-** [comment]
You have to understand that an object is an actual value containing all its entries. If this was true for strings, you could not resize them inside of a sequence, for example. Instead strings behave like `ref object`s, namely they point to a heap datastructure, and for this reason an be `nil`.
