### ISSUE TITLE
"koch" error on Windows

### ISSUE THREAD

**Issue by matkuki** [Araq/Nim#2092]
When following the instructions for building Nim on Windows, the last line:
> **koch boot -d:release**

throws an error during processing:

> ...\nim-devel\lib\packages\docutils\rstgen.nim(606, 6) Error: type mismatch: got (seq[string], proc (T, T): int)
> but expected one of:
> tables.sort(t: OrderedTableRef[A, B], cmp: proc (tuple[key: A, val: B], tuple[key: A, val: B]): int{.closure.})
> tables.sort(t: CountTableRef[A])
> tables.sort(t: var CountTable[A])
> tables.sort(t: var OrderedTable[A, B], cmp: proc (tuple[key: A, val: B], tuple[key: A, val: B]): int{.closure.})
> algorithm.sort(a: var openarray[T], cmp: proc (T, T): int{.closure.}, order: SortOrder)
> FAILURE

Moved this issue here from nim-lang/csources.

**Comment by def-** [comment]
This problem is caused by too old csources IIRC.

**Comment by matkuki** [comment]
Tried with the latest "devel" branch of csources.
Reported the error to nim-lang/csources then was told that I should raise the issue here.
If there is anything else I can try, let me know.

**Comment by Araq** [comment]
Try again please.

**Comment by matkuki** [comment]
It works! Thanks
