### ISSUE TITLE
Nim sources as a tar.gz file

### ISSUE THREAD

**Issue by FedericoCeratto** [Araq/Nim#2098]
Hi and thanks for developing Nim.
Having all the sources required to build Nim (from this repository and nim-lang/csources) in one tar.gz would make the packaging for Linux distributions simpler.
Would it be possible? Thanks!

**Comment by reactormonk** [comment]
There's always https://github.com/nim-lang/csources/archive/devel.zip

**Comment by FedericoCeratto** [comment]
@reactormonk: thank you. Unfortunately devel.zip is not versioned.
Also, the only available version of "csources" is 0.9.4 which is obsoleted.

**Comment by reactormonk** [comment]
https://github.com/nim-lang/csources/issues/11 should do it

**Comment by dom96** [comment]
Is a dependency on ``unzip`` so bad?

**Comment by FedericoCeratto** [comment]
@dom96 unzip? Using unzip is not a problem, just very uncommon. Not having a release version is undesirable.

**Comment by reactormonk** [comment]
Looks like http://nim-lang.org/download/nim-0.10.2.zip is the way to go.

**Comment by kirbyfan64** [comment]
Can't you just use `bsdtar`?

**Comment by FedericoCeratto** [comment]
http://nim-lang.org/download/nim-0.10.2.zip seem to do the trick. It contains all the sources and no binaries (apart from the object files nimrod_icon.o koch_icon.o)
