### ISSUE TITLE
hint[path] = off not working in nim.cfg

### ISSUE THREAD

**Issue by axbender** [Araq/Nim#2103]
Contrary to e.g. "hint[LineTooLong] = off", "hint[Path] = off" is not recognized in nim.cfg.
"nim --hint[Path]:off" works as expected.

**Comment by Araq** [comment]
Works for me. Put ``--hint[path]:off``` in your config before the very first ``path=...`` instruction.

**Comment by axbender** [comment]
Ah, I see. However, the default "nim.cfg" has it's first setting of that kind *after* the last "path" instruction, and there's no docs.
Thx
