### ISSUE TITLE
deleting elements from a table may lead to infinite loop

### ISSUE THREAD

**Issue by lyro** [Araq/Nim#2107]
Consider the following code:

```
import tables

var t = initTable[int,int](4)

for i in 1..4:
  t[i] = i
  t.del(i)
t[5] = 5
```
Running this code gets stuck at line `t[5]=5`. As far as I can tell, the reason is that deleting an element with `del` marks the hash bucket with `seDeleted`, but such buckets will never be reused for new elements. Thus, inserting and deleting four elements will fill up all buckets and inserting the fifth element will fail to find a free one, causing an infinite loop in `rawGetImpl`.

**Comment by Araq** [comment]
@c-blake is working on this.

**Comment by Araq** [comment]
Recent improvements to the table module fixed this.
