### ISSUE TITLE
math.nextPowerOfTwo returns wrong values

### ISSUE THREAD

**Issue by lyro** [Araq/Nim#2110]
Consider `math.nextPowerOfTwo(43010)`, which gives 65522 instead of 65536. I assume this is because the tests `when sizeof(int) > 16` and `when sizeof(int) > 8` in the implementation of `nextPowerOfTwo` should really be ` ... > 2` and ` ... > 1`, respectively, because `sizeof` returns the number of bytes, not bits.

**Comment by Araq** [comment]
Please make PR!
