### ISSUE TITLE
repr should display ``\0``

### ISSUE THREAD

**Issue by dom96** [Araq/Nim#2124]
```nimrod
echo("foobar\0asd".repr)
```

Prints only ``00423980"foobar"``.

This is confusing when trying to debug some issues relating to ``\0`` in the middle of strings.

On a side note, should stdlib modules handle ``\0`` in strings? I ran into a bug with it when using ``db_sqlite``.

**Comment by fowlmouth** [comment]
echo also has issues with it
```nimrod
echo "hi\0echo"
stdout.write "hello\0there\L"
```
output:
```
hi
hellothere
```

**Comment by reactormonk** [comment]
> However, strings in Nim are both zero-terminated and have a length field.

http://nim-lang.org/manual.html#string-type

It's a design decision to have strings zero-terminated. Which makes them unable to hold binary data. Do we have a data type for binary data?

**Comment by flaviut** [comment]
@reactormonk Yes, but repr is mostly useful for debugging. Printing the \0 would make debugging easier in cases where the string is invalid.

**Comment by Varriount** [comment]
Use seq[char] or similar to hold binary data.
Repr should be changed to display the null character - that maximizes the amount of  information users receive. If it's being used for non-debugging purposes on strings,then something is wrong.

**Comment by reactormonk** [comment]
@Varriount I would expect a string to be able to hold binary data. So `readFile` etc. shouldn't return a string because you can't read binary data with it.
