### ISSUE TITLE
Redirect from nimrod to nim at the homepage (Bottom link, "Online IRC")

### ISSUE THREAD

**Issue by shevegen** [Araq/Nim#2141]
I do not know if this is the right place to report, but it is a trivial change so I'll just report it here.

The homepage at http://nim-lang.org/ at the bottom link has a link to IRC 
channel nimrod, at the link called "Online IRC" there.

This webchat-link should show "nim" instead now.

**Comment by def-** [comment]
For me that leads to #nimlang, which is also wrong, should be #nim. It's fixed in the repository already, the website just needs to be updated.

**Comment by dom96** [comment]
Yeah, has been fixed as of https://github.com/Araq/Nim/commit/4080a9ca45ec265bfe7acc16e7bc6f81d6e88bc4

I'll keep it open until the website has been updated.

**Comment by dom96** [comment]
Fixed on website.
