### ISSUE TITLE
Zip on website changed SHA1

### ISSUE THREAD

**Issue by DomT4** [Araq/Nim#2152]
The checksum of the http://nim-lang.org/download/nim-0.10.2.zip download on the Nim website changed at some point from ` 0a54d6d7f257cdade5bf950d318066959c48a6dc ` to ` 2fdd486704931807d03d25d6846c5faee880d69e `. The initial checksum was generated and checked on 4 different machines, so is unlikely to have been an error of some sort.

Can someone verify if there was a repack or something similar? Thanks!

**Comment by dom96** [comment]
Any ideas how long ago it changed?

**Comment by dom96** [comment]
I think there was a repack for new docs about a month ago.

**Comment by DomT4** [comment]
Not sure. We had it reported today, so theoretically it could have changed any time between Jan 2nd 2015 and yesterday. It was last known to be definitely correct as of Jan 1st 2015 - Beyond that, we haven't had any reports of failed checksumming till this afternoon.

**Comment by dom96** [comment]
In that case I wouldn't worry about it.

**Comment by DomT4** [comment]
Alright, Cheers for the quick reply!
