### ISSUE TITLE
Basic Objective-C FFI fails to compile on OS X

### ISSUE THREAD

**Issue by philip-wernersbach** [Araq/Nim#2153]
https://gist.github.com/philip-wernersbach/e987bb6e1454fccb1b0a

**Comment by philip-wernersbach** [comment]
Sorry, just realized that the solution is not apparent from the Gist I posted. The solution to this is to link the Foundation framework implicitly, as that is the Objective-C runtime library on OS X.

**Comment by Araq** [comment]
That's just a configuration problem, please make a PR.

**Comment by philip-wernersbach** [comment]
Other than telling people to add a `{.passL: "-framework Foundation".}` to their source code, I don't know how to fix this. If you tell me how to change the implicit linker flags I will make a PR.

**Comment by Varriount** [comment]
@philip-wernersbach Can't you make a change to nim.cfg to add the linker flags by default? Or is that wrong?

**Comment by philip-wernersbach** [comment]
Can you define flags in `nim.cfg` that are conditional on the environment? The flag only needs to be applied for GCC and Clang on OS X, and only in Objective-C mode.

**Comment by Varriount** [comment]
I believe so - the configuration script can use the basic symbols defined by the compiler itself, including 'macosx'

**Comment by Araq** [comment]
Ping. No PRs for this?

**Comment by philip-wernersbach** [comment]
Sorry, still working on it. Work's been crazy so I haven't had time to sit down and make the changes and make a PR. I'll get one to you later this week.
