### ISSUE TITLE
Leading underscore for unused variables

### ISSUE THREAD

**Issue by def-** [Araq/Nim#2154]
```nimrod
var (dir, name, ext) = splitFile(path)
```
If you only need `name` and `ext`, you will get a warning because `dir` is unused:
```
koch.nim(212, 11) Hint: 'dir' is declared but not used [XDeclaredButNotUsed]
```
Would be nice if we could declare that `dir` is intentionally unused. Other languages use a leading underscore for this, which means that the variable can't be used.

**Comment by Varriount** [comment]
Hm, interesting idea. I don't really know if it would 'fit' Nim, but interesting nonetheless. Are there any alternative solutions to the problem this tries to solve?

**Comment by trustable-code** [comment]
I would prefer a solution like  in Go. 
Example if you need only dir:
```
var (dir, _, _) = splitFile(path)
```

**Comment by dom96** [comment]
@Araq already mentioned that he might implement the syntax @trustable-code shows.

**Comment by Araq** [comment]
Has been implemented.
