### ISSUE TITLE
SYSTEM_INFO alignment?

### ISSUE THREAD

**Issue by apense** [Araq/Nim#2161]
when running the following:

```nim
import windows

var sysInfo: SYSTEM_INFO

GetSystemInfo(sysInfo)

echo sysInfo.dwOemID # 9, from wProcessorArchitecture
echo sysInfo.dwPageSize # 4096
echo sysInfo.dwActiveProcessorMask # 15
echo sysInfo.dwNumberOfProcessors # returns 0 ??
echo sysInfo.dwProcessorType # returns 4
echo sysInfo.dwAllocationGranularity # returns 8664 THIS IS PROCESSOR TYPE as PROCESSOR_AMD_X8664
```
there seems to be some differences between the structure SYSTEM_INFO structure and what one would expect (https://msdn.microsoft.com/en-us/library/windows/desktop/ms724958%28v=vs.85%29.aspx). I fully understand if I'm missing something, just thought I'd share a possible issue.
This is on an AMD A10 running Windows 8.1 x64

**Comment by Varriount** [comment]
The windows module comes from an automatic conversion performed on an old pascal module, so it's entirely possibly the structure declaration is erroneous  (which is why we perform a check when moving anything from the windows module into winlean).

Since I'm on my phone at the moment, I can't look at windows.nim (file is too large), however I suspect those fields in the API marked with the LPVOID type are wrong (since the size will differ depending on architecture). The union may be another source of errors. 

If you want to submit a PR, feel free. If not, I'll try to get to this at some point (though I can't promise when). Fixing it is simply a matter of correcting whatever fields have the incorrectly defined type.

**Comment by apense** [comment]
This seems to work alright:

```nim
type
  ProcessorStruct = object
    wProcessorArchitecture: WORD
    wReserved: WORD
  OemUnion {.union.} = object
    dwOemID: DWORD
    pWords: ProcessorStruct
  SYSTEM_INFO* = object
    dwOemID*: OemUnion
    dwPageSize*: DWORD
    lpMinimumApplicationAddress*: LPVOID
    lpMaximumApplicationAddress*: LPVOID
    dwActiveProcessorMask*: DWORD_PTR
    dwNumberOfProcessors*: DWORD
    dwProcessorType*: DWORD
    dwAllocationGranularity*: DWORD
    wProcessorLevel*: WORD
    wProcessorRevision*: WORD
  LPSYSTEM_INFO* = ptr SYSTEM_INFO

proc getSystemInfo*(lpSysInfo: LPSYSTEM_INFO) {.stdcall, dynlib: "kernel32",
  importc: "GetSystemInfo".}

proc getSystemInfo*(): SYSTEM_INFO =
  var sysi: SYSTEM_INFO
  getSystemInfo(addr(sysi))
  return sysi

var mySys = getSystemInfo()
echo mySys.dwNumberOfProcessors # returns 4
echo mySys.dwProcessorType # returns 8664, which matches my AMD x64
echo mySys.dwOemID # (dwOemID: 9, pWords: (wProcessorArchitecture: 9, wReserved: 0))
```

I haven't actually seen if this lines up with the naming styles preferred. Got some stuff to do today, but I'll take a better look soon if no one takes it.
I'm not sure there's actually a point in doing all the union/struct stuff, since dwOemId is declared obsolete and wReserved isn't used. So this actually works fine:

```nim
type
  SYSTEM_INFO* = object
    wProcessorArchitecture*: WORD
    wReserved*: WORD
    dwPageSize*: DWORD
    lpMinimumApplicationAddress*: LPVOID
    lpMaximumApplicationAddress*: LPVOID
    dwActiveProcessorMask*: DWORD_PTR
    dwNumberOfProcessors*: DWORD
    dwProcessorType*: DWORD
    dwAllocationGranularity*: DWORD
    wProcessorLevel*: WORD
    wProcessorRevision*: WORD
```

**Comment by Varriount** [comment]
I'm not sure either... is there any chance member packing and such could cause problems?

**Comment by apense** [comment]
Got it! I think.
This actually seems to be a problem with the original header. Even if you look at winbase.h in the included MinGW, `dwActiveProcessorMask` is defined as `DWORD`, whereas it should be `DWORD_PTR`, which is going to be a different size on 64-bit systems. The corresponding produced C code:
From the last example in my original post:
```c
struct  systeminfo142005  {
NI16 Wprocessorarchitecture;
NI16 Wreserved;
NI32 Dwpagesize;
void* Lpminimumapplicationaddress;
void* Lpmaximumapplicationaddress;
NI Dwactiveprocessormask;
NI32 Dwnumberofprocessors;
NI32 Dwprocessortype;
NI32 Dwallocationgranularity;
NI16 Wprocessorlevel;
NI16 Wprocessorrevision;
};
```
From the included SYSTEM_INFO object:
```c
struct  systeminfo93011  {
NI16 Wprocessorarchitecture;
NI16 Wreserved;
NI32 Dwpagesize;
void* Lpminimumapplicationaddress;
void* Lpmaximumapplicationaddress;
NI32 Dwactiveprocessormask;
NI32 Dwnumberofprocessors;
NI32 Dwprocessortype;
NI32 Dwallocationgranularity;
NI16 Wprocessorlevel;
NI16 Wprocessorrevision;
};
```
`NI` is going to be `NI64` on a 64-bit system. Anyways, long story short, I think this is fixable just by changing `DWORD` to `DWORD_PTR` or `ptr DWORD`.

**Comment by apense** [comment]
#2192
