### ISSUE TITLE
Comparing algebraic data types

### ISSUE THREAD

**Issue by flaviut** [Araq/Nim#2187]
[reported by andrea on the forums](http://forum.nim-lang.org/t/904)

>  It seems that comparing two instances of an algebraic data type fails. A minimal example I could come up with is this:
> 
> ```nim
> type
>   FooEnum = enum
>     Stringer, Numberer
>   Foo = object
>     case kind: FooEnum
>     of Stringer:
>       x: string
>     of Numberer:
>       y: int
> 
> 
> let
>   a = Foo(kind: Stringer, x: "hi")
>   b = Foo(kind: Stringer, x: "hello")
> echo (a == b)
> ```
> 
> This reports `Error: parallel 'fields' iterator does not work for 'case' objects`

**Comment by Araq** [comment]
That's not a bug. The default == for objects uses the 'fields' iterator which doesn't support iteration for 'case' objects. (Which is not trivial to support.)

**Comment by Varriount** [comment]
This fact should be documented in the manual. @araq should I open a new issue, or modify and reopen this one?
