### ISSUE TITLE
Can't pass generic function to `map`

### ISSUE THREAD

**Issue by hasenj** [Araq/Nim#2188]
The following snippet:

```
proc square[T](n: T): T{.closure.} =
    n * n
let components = @[1, 2, 3]
echo sum(components.map(square))
```
Fails with:

```
Error: type mismatch: got (seq[int], proc (T): T{.closure.})
but expected one of:
system.map(data: var openarray[T], op: proc (var T){.closure.})
system.map(data: openarray[T], op: proc (T): S{.closure.}): seq[S]

  echo sum(components.map(square))
                     ^
```

It seems I have to explicitly fill the type:
```echo sum(components.map(square[int]))```

I don't know if this is a bug or if that's intended, but it seems like the compiler should be able to deduce the type by itself, no?

**Comment by Araq** [comment]
No, implicit generic instantiation in this context is not easy to do nor desirable. The compiler is right to complain.

**Comment by hasenj** [comment]
I can understand it being not easy to implement. But why is it not desirable?
