### ISSUE TITLE
Nim compiler injecting code which resets WSAGetLastError's error code

### ISSUE THREAD

**Issue by dom96** [Araq/Nim#2191]
I have discussed this previously with @Araq but that was probably more than a year ago now.

Since I have just been bitten by this again I think I should raise an issue about it. The Nim compiler appears to be injecting C code which resets the last error code on Windows to 0. This results in problems when calling Win API functions like ``recv`` because if they fail and the Nim compiler decides to inject something in between the call to ``recv`` and ``WSAGetLastError`` then ``WSAGetLastError`` will return 0 and the user will be left confused with an "Unknown OS error" exception.

The only way to solve this would be to ensure that any C code which may be run between these statements leaves the error code as-is. As far as I understand it this will come at a performance penalty which is a problem. But perhaps it is worth it to avoid the confusion?

**Comment by Varriount** [comment]
Can you give an example that show the bug?

**Comment by dom96** [comment]
Don't think so.

**Comment by Araq** [comment]
Should be fixed by commit 3dd1ecbae4a08627.
