### ISSUE TITLE
Odd rounding in JS backend

### ISSUE THREAD

**Issue by apense** [Araq/Nim#2196]
This probably never actually produces an incorrect result, but it's worth figuring out.

The code
```nim
let c1 = 0.9189385332046727400000
let c2 = 0.9189385332046727400000
let c3 = 0.9189385332046727300000
let c4 = 0.91893853320467273
let c5 = 0.91893853320467272
let mypi = PI
```

produces 
```js
var c1_20061 = [9.1893853320467278e-001];
var c2_20063 = [9.1893853320467278e-001];
var c3_20065 = [9.1893853320467278e-001];
var c4_20067 = [9.1893853320467278e-001];
var c5_20069 = [9.1893853320467267e-001];
var c6_20071 = [9.1893853320467267e-001];
var mypi_20075 = [3.1415926535897931e+000];
```

Note that pi is defined as
`3.1415926535897932...`
but is converted to
`3.1415926535897931`

It's past the 15th significant digit, so it probably has almost no effect, but there may be some situations in which it occurs earlier? I can't really imagine this affecting anything. But I don't know.

**Comment by reactormonk** [comment]
I think that's a result of how numbers are implemented in Javascript. Nothing we could do that except implement our own numbers in JS, which is too expensive.
