### ISSUE TITLE
JSON parser fails in cpp output mode

### ISSUE THREAD

**Issue by dhasenan** [Araq/Nim#2199]
import json
    let t = """{"floor": {"friction": 0.75}}"""
    for k, v in json.pairs(json.parseJson(t)):
      echo k

Expected output:

    floor

Actual output:

    frictio

Branch: devel, revision a8acb5ec65b5a3d6577602b9fc0d8832cf3a3287
Platform: Linux Ubuntu 14.04 x64

**Comment by def-** [comment]
I can't reproduce this.

**Comment by dhasenan** [comment]
Ah, it works as expected with `nim c foo.nim` but fails with `nim cpp foo.nim`. Retested with freshly built nim from HEAD on devel, removed nimcache, no special config, etc.

**Comment by Varriount** [comment]
You're using the development version of the compiler, right?
Could you please test the example using revision 0a1bc0e9cd30ef1a3654e7637795ed22010e7977 ?

**Comment by dhasenan** [comment]
Still occurs with the revision you specified.

**Comment by dhasenan** [comment]
Verified that it works with the latest master.

**Comment by dhasenan** [comment]
Copying lib/pure/json.nim from master has no effect; it's not part of the library changes. (Not that they looked like they could be culpable.)

**Comment by dhasenan** [comment]
git bisect narrows it down to something in the range of 07f42fa612db998ec88dade7ea3140ba6a15fb5b to 74c6c8c903a2eb497ee74aaf9ba741b1abf40c88. Unfortunately, a long range of revisions there fail to compile the failing example at all, so there's an annoying amount of ambiguity.

**Comment by reactormonk** [comment]
@dhasenan start git bisect, initialize good and bad and run `git bisect ./koch temp -r c test.nim`. Make sure `test.nim` has an `assert` or `exit 1` so you have a non-zero exit code when it fails.

**Comment by dhasenan** [comment]
@reactormonk I did a git bisect to get to this point. Then git bisect gave me twelve revisions in a row that failed to compile the example. Not terribly informative. A manual scan reveals:

a400e8f7f39b1bb29245323c6d999f01b46f22c3: works as expected
e75e421: fails to compile (error: crosses initialization...)
...
d020ad0: fails to compile (error: crosses initialization...)
e84834db79854c6ccc89263ec20d3749b8a87a05: wrong output

Slightly narrower range, but it's still a lot to look through. I won't be able to look into it much in the next 36 hours. For my own purposes, at least, I have a working revision to use.

**Comment by dhasenan** [comment]
Awesome, thanks!
