### ISSUE TITLE
memory leak in HTTPClient when using HTTPS

### ISSUE THREAD

**Issue by wiffel** [Araq/Nim#2204]
I noticed there is a memory leak when using _getContent_ from _httpclient_ when using _https_.
After some searching, I think I did find the culprit(s). Sockets with an SSL wrapper are being torn down in _pure/net.nim_ and _pure/sockets.nim_ using _SSLShutdown_. But that does not release the allocated memory. It also needs a call to _SSLFree_.

I did make the following changes in my local version of the files:

_pure/net.nim_ (line 445)

    let res = SLShutdown(socket.sslHandle)
    if res == 0: 
        SSLFree(socket.sslHandle)
    
_pure/sockets.nim_ (line 658)

    if socket.isSSL:
       discard SSLShutdown(socket.sslHandle)
       discard SSLFree(socket.sslHandle)

I'm not sure if these are the correct fixes. But it did remove the memory leak in my application.

**Comment by reactormonk** [comment]
Pull Request please.

**Comment by wiffel** [comment]
Never created a Pull Request before, so I'm not sure how to do that.
But now is as good as any time to learn it, I guess ?
I'll try to create one.

**Comment by dom96** [comment]
@reactormonk Please don't demand PRs from people like that.

**Comment by reactormonk** [comment]
https://help.github.com/articles/creating-a-pull-request/ Please make sure you're basing of the `devel` branch (`git checkout devel` on your local copy) and also merging against it when creating the pull request.

**Comment by wiffel** [comment]
Thanks for the link. 

I was already working with the _devel_ branch, so that should be OK.
If I find the time tonight, I'll make that _Pull Request_.

**Comment by wiffel** [comment]
Current status ...

I did run a long test to check the validity of this change. After 5 hours of running, the memory consumption was still the same. So, I'm confident that the memory leak is gone.

But I did get a _SIGSEGV: Illegal storage access_ in the garbage collector. I don't think it has anything to do with this change, but I just want to be sure. So, I'm currently re-running my tests with some extra debug code to be sure.

**Comment by wiffel** [comment]
OK, Pull Request created.

**Comment by reactormonk** [comment]
https://github.com/Araq/Nim/pull/2210

**Comment by wiffel** [comment]
Regarding pull request https://github.com/Araq/Nim/pull/2210 ...

I Forgot to mention the results of the extra tests ...

The SIGSEGV error mentioned before was indeed anorther problem (I did some wrong variable sharing between threads). Without that bug, the tests now ran for about 8 hours, doing thousands of get- and post-requests using SSL. This test ran fine without any crashes and memory leaks. So, I'm confident now that this fix is OK

**Comment by dom96** [comment]
Fixed via #2210
