### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by jtgd** [Araq/Nim#2205]
http://nim-lang.org/pegs.html
under proc replacef,

line:
"var1=key; var2=key2".replace(peg"{\ident}'='{\ident}", "$1<-$2$2")

should read:
"var1=key; var2=key2".replacef(peg"{\ident}'='{\ident}", "$1<-$2$2")

**Comment by reactormonk** [comment]
Pull Request please.

**Comment by jtgd** [comment]
I'm guessing that you're asking me to check out the files, fix it, and
submit the change. I'd be happy to but forgive me that I am new to git
and this will be my first time.

However I don't know where the source for this web page is. The file
doc/pegdocs.txt does not seem to be it. Is there another location for
the source of http://nim-lang.org/pegs.html ?

reactormonk writes:

> Pull Request please.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Araq/Nim/issues/2205#issuecomment-75660642

--
Jay Dresser

**Comment by reactormonk** [comment]
I didn't know myself, so I took a string from the website `"PEG vs regular expression"` and ran it via `git grep` on my local copy. Final command:  `git grep "PEG vs regular expression"`. Result: https://github.com/Araq/Nim/blob/devel/doc/pegdocs.txt

**Comment by jtgd** [comment]
OK, but pegdocs.txt is not the source of http://nim-lang.org/pegs.html
If I can ever figure out where that file is I'll try to make the change.

(I think the thing to grep for is 'replacef')

reactormonk writes:

> I didn't know myself, so I took a string from the website `"PEG vs regular expression"` and ran it via `git grep` on my local copy. Final command:  `git grep "PEG vs regular expression"`. Result: https://github.com/Araq/Nim/blob/devel/doc/pegdocs.txt
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Araq/Nim/issues/2205#issuecomment-75690021

--
Jay Dresser

**Comment by jtgd** [comment]
Ok, I found it, (a comment block inside the source) but I'm not sure how to get it to you.

I did a 'git clone' and I have a copy on my machine.
Not sure how to push it to you. (how to make pull request)

**Comment by reactormonk** [comment]
https://help.github.com/articles/fork-a-repo/ + https://help.github.com/articles/using-pull-requests/ (we're using fork & pull)
