### ISSUE TITLE
Running from command line/script runner

### ISSUE THREAD

**Issue by ioquatix** [Araq/Nim#2206]
Hi,

I've had this issue come in: https://github.com/ioquatix/script-runner/issues/20#issuecomment-75649211

Just wondering, is it possible to run a nim script using a hash bang line, e.g.

    #!/usr/bin/env nim

Can you accept the script from `stdin` somehow for running unsaved files?

Sorry for the bother and thanks for your advice, assistance.

**Comment by def-** [comment]
> Just wondering, is it possible to run a nim script using a hash bang line, e.g.

Yes: http://hookrace.net/blog/what-makes-nim-practical/#use-as-a-scripting-language

> Can you accept the script from stdin somehow for running unsaved files?

I made a PR for this just yesterday: https://github.com/Araq/Nim/pull/2202

**Comment by ioquatix** [comment]
Is `nimscript` bundled by default?

**Comment by def-** [comment]
No.

**Comment by ioquatix** [comment]
What is the preferred implementation in script-runner?

1/ Bundle `nimscript` and use it.
2/ Execute something similar to what `nimscript` does.

The option of having `nimscript` included in `nim` makes life a lot easier since it can run the script outside the script-runner environment.

**Comment by def-** [comment]
I guess just running this would work: `nim --verbosity:0 -r c $FILE`

**Comment by ioquatix** [comment]
@def- I guess the big issue with that is people would have to type that into every script.. either that or it gets hard coded into script-runner in which case it might become a compatibility issue in the future if the flags change.

**Comment by ioquatix** [comment]
If no file is specified can you default to `stdin`? This is how almost every other script interpreter works.

**Comment by Araq** [comment]
Stdin support has been merged.

**Comment by ioquatix** [comment]
@Araq looking to implement this now, can you please confirm how to run this at the top of a script file, e.g.

    #!/usr/bin/env nim --verbosity:0 -r c

**Comment by reactormonk** [comment]
I can't find a correct shebang line to make it work. I think it's a problem with the argument parsing and/or how the arguments are passed to the invoked compiler.

**Comment by ioquatix** [comment]
Okay, well, essentially, what we want is something that can run on the hash bang line, it looks like `nimscript` might have cracked that nut, but perhaps it's good if this functionality is available directly from nim - once you let me know I will integrate support into script-runner.

**Comment by kirbyfan64** [comment]
@ioquatix That won't work: on most systems (including Linux), `/usr/bin/env` will not pass any command line arguments to the program. In your example, `/usr/bin/env` will be looking for an executable named `nim --verbosity:0 -r -c`.

**Comment by reactormonk** [comment]
The passing works just fine on arch. I get

    Error: invalid command: '--verbosity:0 -r c'

When enclosing the commands via `"`, I get

    Error: arguments can only be given if the '--run' option is selected

**Comment by ioquatix** [comment]
@kirbyfan64 I have never seen the behaviour your proposing. In fact, I can write an entire program after /usr/bin/env with arguments if I like:

![screen shot 2015-04-22 at 10 47 01 am](https://cloud.githubusercontent.com/assets/30030/7264168/f12ce384-e8dc-11e4-82be-6e17ae8c56cf.png)

From the `env` man page:

```
SYNOPSIS
     env [-i] [name=value ...] [utility [argument ...]]
```

The only limitation is programs with `=` in their name as this looks like an environment option.

**Comment by kirbyfan64** [comment]
@ioquatix What version of UNIX are you using? On Linux:

```
ryan@DevPC-LX:~/langtest$ ./x.rb
/usr/bin/env: ruby -e "puts ARGV.inspect" --: No such file or directory
ryan@DevPC-LX:~/langtest$ 
```

**Comment by ioquatix** [comment]
I'm on Mac OS X which is BSD derived.

**Comment by ioquatix** [comment]
On linux:

```
% /usr/bin/env ruby -e "puts ARGV.inspect" -- Apples Oranges Bananas
["Apples", "Oranges", "Bananas"]
```

Is it different when you run it in a file?

**Comment by ioquatix** [comment]
Weird, when it's in a file, it doesn't work correctly, on both Mac and Linux.

**Comment by ioquatix** [comment]
Interesting, as soon as you have quotes, it fails.

**Comment by ioquatix** [comment]
Perhaps bundling `nimscript` makes sense given the complexity of using env with arguments.

**Comment by ioquatix** [comment]
Just touching base, any progress here?

**Comment by def-** [comment]
I would recomment to use https://github.com/flaviut/nimrun

**Comment by ioquatix** [comment]
Okay right, so basically this isn't something we really need to add explicit support to script-runner then. Anyone can just add this to their path and use it. Thanks.
