### ISSUE TITLE
vcc "import math" triggers Error: execution of an external program failed

### ISSUE THREAD

**Issue by ckkashyap** [Araq/Nim#2214]
On my windows machine, I did the following - 

C:\Users\ckk>"c:\Program Files (x86)\Microsoft Visual Studio14.0\vc\vcvarsall.bat" x64

and then 

nim c --cc:vcc hello.nim 

hello.nim contains the following - 

import math
echo "hello"

I get this error

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\math.h(78): warni
ng C4005: 'NAN': macro redefinition
c:\Nim\lib\nimbase.h(306): note: see previous definition of 'NAN'
c:\users\ckk\documents\nimcache\stdlib_times.c(751): error C2065: 'tzname': unde
clared identifier
c:\users\ckk\documents\nimcache\stdlib_times.c(751): error C2109: subscript requ
ires array or pointer type
c:\users\ckk\documents\nimcache\stdlib_times.c(751): error C2198: 'cstrToNimstr'
: too few arguments for call
c:\users\ckk\documents\nimcache\stdlib_times.c(752): error C2065: 'tzname': unde
clared identifier
c:\users\ckk\documents\nimcache\stdlib_times.c(752): error C2109: subscript requires array or pointer type
c:\users\ckk\documents\nimcache\stdlib_times.c(752): error C2198: 'cstrToNimstr': too few arguments for call
c:\users\ckk\documents\nimcache\stdlib_times.c(760): error C2065: 'timezone': undeclared identifier
CC: stdlib_strutils
stdlib_strutils.c
CC: stdlib_parseutils
CC: stdlib_winlean
stdlib_parseutils.c
stdlib_winlean.c
Error:  execution of an external program failed; rerun with --parallelBuild:1 to see the error message

**Comment by Araq** [comment]
Works for me with Visual Studio 13. Note: I use their "Developer Command Prompt for VS 2013".
