### ISSUE TITLE
block inside template is ignored

### ISSUE THREAD

**Issue by AdrianV** [Araq/Nim#2217]
this does not compile anymore:
```nim
template myblock(doit: stmt): stmt =
  block:
    doit
    
block:  #ok
  var v1 = 12
  echo v1
block:  #ok
  var v1 = 12
  echo v1
  
myblock(): #ok
  var v1 = 12
  echo v1
myblock():
  var v1 = 12 # error redefinition of v1
  echo v1
```

**Comment by Araq** [comment]
But it works according to the spec: 'stmt' is checked for semantics before it's passed to 'myblock' and as such the redefinition error occurs. Use an .immediate template or make the 'doit' parameter's type 'expr'.
