### ISSUE TITLE
Compiler doesn't support spaces in path on windows.

### ISSUE THREAD

**Issue by morganthrapp** [Araq/Nim#2218]
As stated, if you attempt to compile a nim file and there's a space somewhere in the path, the compiler will be unable to find the files. Eg, C:\Nim Workspace\hello_world\hello_world.nim will fail because the compiler is looking for Workspace\hello_world\hello_world.nim.

**Comment by kirbyfan64** [comment]
Why don't you just quote it?

```
nim c "C:\Nim Workspace\hello_world\hello_world.nim"
```

**Comment by morganthrapp** [comment]
The issue is that I'm running nim c from C:\Nim Workspace\hello_world. 
Sure, I could specify the whole path, but it seems like the ideal behavior would be to just have it always wrap in quotes.

**Comment by dom96** [comment]
Works for me.

**Comment by morganthrapp** [comment]
@dom96 What OS are you using?

**Comment by Varriount** [comment]
This can't be done - it theres only so much ambiguity that can be resolved when parsing command line options. For example, in the command `nim c --run C:\Nim Workspace\hello_world\hello_world.nim` the compiler cannot tell if the entire path consists of the past two arguments, or the second to last argument (with the last being a parameter to pass to the compiled executable)

To my knowledge, very few command line utilities (even on Windows) support unquoted paths containing spaces. They either require quoting the path, or escaping the spaces in the path. 

Why not just navigate to "C:\Nim Workspace\"? The compiler doesn't require absolute paths.

**Comment by dom96** [comment]
@morganthrapp Windows 8.1

**Comment by Araq** [comment]
@morganthrapp it's known to be broken with 0.10.2 but works with devel.

**Comment by morganthrapp** [comment]
@Varriount I am in that directory.

**Comment by Varriount** [comment]
@morganthrapp Then what version of the compiler are you using?

**Comment by morganthrapp** [comment]
@Varriount 0.10.2.
