### ISSUE TITLE
Type constraints confuse overload resolution

### ISSUE THREAD

**Issue by MasonMcGill** [Araq/Nim#2219]
I'm splitting this from issue #1991, because it doesn't seem to have anything to do with `static[T]`.

Consider the following code:

```nim
type A = object of RootObj
type B = object of A
type SomeA = A|A # A hack to make "A" a typeclass.

proc p[X](x: X) =
  echo "This has the highest precedence."

proc p[X: SomeA](x: X) =
  echo "This has the second-highest precedence."

proc p[X: A](x: X) =
  echo "This has the lowest precedence."

proc p[X: any](x: X) =
  echo "This is never called."

p(B())
```

If you comment out the first definition of `p`, the second is called. If you comment out the first two, the third is called. The last definition doesn't seem to match anything. This seems wrong, since the second and third definitions seem to be more specialized than the first.

I explained my use cases in more detail in issue #1991, but they basically come down to making sure generic routines don't get hijacked by catch-all definitions in `system`.

**Comment by Araq** [comment]
'any' doesn't match anything really, so that's not a bug. I have a fix for the other issues in the works.

**Comment by MasonMcGill** [comment]
> 'any' doesn't match anything really, so that's not a bug.

I still don't have a great intuitive grasp of the difference between `any` and `auto`, so I'll take your word for it.

> I have a fix for the other issues in the works.

Nice! If you document the changes, I'll be happy to add some examples and put the result in the "Overload Resolution" section of the manual (with a cross-reference in "Generics").

**Comment by markus-oberhumer** [comment]
See also git commit 9c00f6decd4453a4233450a60ccef05b20e9f24a.
