### ISSUE TITLE
Comparing a nil TableRef to the nil value gives "Error: internal error: wrong instantiated type!"

### ISSUE THREAD

**Issue by goob** [Araq/Nim#2221]
The following program fails:

```
import tables

var x: TableRef[string, int]
echo x == nil 
```

with the following error:

>Error: internal error: wrong instantiated type!
>No stack traceback available
>To create a stacktrace, rerun compilation with ./koch temp c <file>

When changing the equality comparison to `echo x.repr`, it succeeds. Using my own local object with generics also succeeds.

Confirmed on `10.2` and the current `devel` build.

---

The stacktrace when following the instructions in the error is:

>Error: internal error: wrong instantiated type!
Traceback (most recent call last)
nim.nim(92)              nim
nim.nim(56)              handleCmdLine
main.nim(251)            mainCommand
main.nim(62)             commandCompileToC
modules.nim(203)         compileProject
modules.nim(151)         compileModule
passes.nim(193)          processModule
passes.nim(137)          processTopLevelStmt
sem.nim(454)             myProcess
sem.nim(428)             semStmtAndGenerateGenerics
semstmts.nim(1333)       semStmt
semexprs.nim(893)        semExprNoType
semexprs.nim(2093)       semExpr
semexprs.nim(1710)       semMagic
semexprs.nim(876)        semDirectOp
semexprs.nim(746)        semOverloadedCallAnalyseEffects
semcall.nim(311)         semOverloadedCall
semcall.nim(146)         resolveOverloads
semcall.nim(59)          pickBestCandidate
sigmatch.nim(1543)       matches
sigmatch.nim(1506)       matchesAux
sigmatch.nim(1376)       prepareOperand
semexprs.nim(26)         semOperand
semexprs.nim(2093)       semExpr
semexprs.nim(1710)       semMagic
semexprs.nim(876)        semDirectOp
semexprs.nim(746)        semOverloadedCallAnalyseEffects
semcall.nim(311)         semOverloadedCall
semcall.nim(146)         resolveOverloads
semcall.nim(59)          pickBestCandidate
sigmatch.nim(1543)       matches
sigmatch.nim(1507)       matchesAux
sigmatch.nim(1313)       paramTypesMatch
sigmatch.nim(1204)       paramTypesMatchAux
sigmatch.nim(901)        typeRel
msgs.nim(850)            internalError
msgs.nim(780)            rawMessage
msgs.nim(777)            rawMessage
msgs.nim(724)            handleError
FAILURE

**Comment by def-** [comment]
I believe this is why `isNil` exists. The compiler should still not fail with an internal failure of course.

**Comment by goob** [comment]
@def- `isNil()` indeed succeeds.
