### ISSUE TITLE
For-loops ending at '\xff' don't end

### ISSUE THREAD

**Issue by rspeer** [Araq/Nim#2224]
If I try to iterate over a range of bytes (chars), and the end of the range is `'\xff'`, the loop never ends.

As a simple example, this loop should run 16 times, outputting the numbers 240 to 255. But it's actually an infinite loop. After 255 it goes on to 0, counts all the way back up to 255, and repeats forever.

```nim
for b in '\xf0'..'\xff':
    echo(int(b))
```

**Comment by SSPkrolik** [comment]
It seems like the error is generic for all ordinal types whose bound is the MAX value for that type.

**Comment by Varriount** [comment]
What is the C code like for these kinds of loops?

**Comment by def-** [comment]
```c
		NIM_CHAR res_88044;
		res_88044 = 240;
		{
			while (1) {
				NimStringDesc* LOC4;
				if (!((NU8)(res_88044) <= (NU8)(255))) goto LA3;
				b_88035 = res_88044;
				LOC4 = 0;
				LOC4 = nimIntToStr(((NI) (((NU8)(b_88035)))));
				printf("%s\012", LOC4? (LOC4)->data:"nil");
				res_88044 += 1;
			} LA3: ;
		}
```

**Comment by SSPkrolik** [comment]
Please someone check the pull request I've added. It fixes the problem with countup and `..` iterators for ordinal types MAX value as a right bound of the range (#2270)
