### ISSUE TITLE
readAll(stdin) does not work properly on mac os x

### ISSUE THREAD

**Issue by aurora** [Araq/Nim#2228]
The test-case is as simple as:

    echo(readAll(stdin))

The correct behavior would be that STDIN is being read until CTRL+D is pressed (EOF), and this is how it works with Linux. But with Mac OS X (10.10) this does not work. readAll returns immediately without waiting for CTRL+D

**Comment by reactormonk** [comment]
I've run the following test program (leaned on
https://github.com/Araq/Nim/blob/devel/lib/system/sysio.nim#L127-L132 )

    proc ftell(f: File): int {.importc: "ftell", header: "<stdio.h>", tags: [].}
    proc fseek(f: File, offset: clong, whence: int): int {.importc: "fseek", header: "<stdio.h>", tags: [].}

    var oldPos = ftell(stdin)
    echo(oldPos)
    echo(fseek(stdin, 0, 2))
    echo(ftell(stdin))
    echo(fseek(stdin, clong(oldPos), 0))

Returns

    -1
    -1
    -1
    -1

on Linux. On mac it's

    80873
    0
    2
    0

same on BSD?

**Comment by aurora** [comment]
The problem with this issue is, that i cannot even work it around from userland, because most of the functions needed from sysio.nim are not exported. The workaround in my case would be to check isatty and call readAllBuffer directly ...

**Comment by Araq** [comment]
Fixed by commit 8b05bf3e8660ded6dec29e04

**Comment by aurora** [comment]
thanks for the fast fix! :+1:
