### ISSUE TITLE
Unknown line/column number in constant declaration type conversion error

### ISSUE THREAD

**Issue by crosbyb** [Araq/Nim#2252]
Tested on 0.10.2 (2014-12-29), OS X.

Declaring a constant with a type and a mismatched value results in an error with unknown line/column numbers.

Behold:
```nim
const FOO: int = 1000 / 30
```
and the output from `nim c constant.nim`:

```
config/nim.cfg(45, 2) Hint: added path: '/Users/Brad/.babel/pkgs/' [Path]
config/nim.cfg(46, 2) Hint: added path: '/Users/Brad/.nimble/pkgs/' [Path]
Hint: used config file '/Users/Brad/apps/nim-0.10.2/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: constant [Processing]
???(???, ???) Error: type mismatch: got (float) but expected 'int'
```

**Comment by G4MR** [comment]
I get a similar error on: Nim Compiler Version 0.10.3 (2015-03-01) [Windows: i386]

    D:\Documents\Projects\Nim\test\imports>nim c -r main.nim
    d:\nim\config\nim.cfg(53, 2) Hint: added path: 'C:\Users\XXXX\.babel\pkgs\' [Path]
    d:\nim\config\nim.cfg(54, 2) Hint: added path: 'C:\Users\XXXX\.nimble\pkgs\aporia-0.2.0' [Path]
    d:\nim\config\nim.cfg(54, 2) Hint: added path: 'C:\Users\XXXX\.nimble\pkgs\cairo-1.0' [Path]
    d:\nim\config\nim.cfg(54, 2) Hint: added path: 'C:\Users\XXXX\.nimble\pkgs\nimble-0.6.0' [Path]
    d:\nim\config\nim.cfg(54, 2) Hint: added path: 'C:\Users\XXXX\.nimble\pkgs\sdl2-1.0' [Path]
    d:\nim\config\nim.cfg(54, 2) Hint: added path: 'C:\Users\XXXX\.nimble\pkgs\gtk2-1.0' [Path]
    d:\nim\config\nim.cfg(54, 2) Hint: added path: 'C:\Users\XXXX\.nimble\pkgs\' [Path]
    Hint: used config file 'D:\Nim\config\nim.cfg' [Conf]
    Hint: system [Processing]
    Hint: main [Processing]
    ???(???, ???) Error: type mismatch: got (float) but expected 'int'

And the code block:

    const foo : int = 1000 / 30

    echo foo
