### ISSUE TITLE
Multiple spawn and channels error

### ISSUE THREAD

**Issue by wiffel** [Araq/Nim#2257]
As mentioned in http://forum.nim-lang.org/t/959

I think that the program below should work, but it gives a compiler error/warning that it is not GC-safe. When ignoring the error/warning, the generated program does not run correctly. It freezes at the *recv* call.

It does work when using a single channel. 
It also works when using an *int* as the channel type instead of a *string* type.

<pre>
import threadpool

type StringChannel = TChannel[string]
var channels : array[1..3, StringChannel]

proc consumer(ix : int) {.thread.} =
  echo channels[ix].recv() ###### not GC-safe: 'channels'

proc main =
  for ix in 1..3: channels[ix].open()
  for ix in 1..3: spawn consumer(ix)
  for ix in 1..3: channels[ix].send("test")
  sync()
  for ix in 1..3: channels[ix].close()

when isMainModule:
  main()
</pre>

**Comment by swerling** [comment]
I was playing around with the example at the top of this ticket in order to learn nim. I discovered I can still get the lockup. The likelihood of a lockup goes up with the value of ch_max. 
```nim
import threadpool

const ch_max:int = 3

var channels: array[1..ch_max, TChannel[string]]

proc consumer(ix : int) {.thread.} =
  echo "received: " & channels[ix].recv()

proc main =

  for ix in countup(1,ch_max):
    echo "opening: " & $ix & "/" & $ch_max
    channels[ix].open()

  for ix in countup(1,ch_max):
    echo "spawning: " & $ix & "/" & $ch_max
    spawn consumer(ix)

  for ix in countup(1,ch_max):
    echo "sending: " & $ix & "/" & $ch_max
    channels[ix].send("channel recv " & $ix)

  sync()
  echo "synced"

  for ix in countup(1,ch_max): channels[ix].close()

when isMainModule:
  echo "<<begin>>"
  main()
  echo "<<end>>"
```

**Comment by swerling** [comment]
I read the thread from the forum that spawned (so to speak) this ticket. I missed this line from Araq:

> In summary: TChannel has been designed for TThread, spawn plus a channel is wrong.

I think I didn't read the above line closely enough before posting the message above.
