### ISSUE TITLE
re: findAll entering endless loop

### ISSUE THREAD

**Issue by def-** [Araq/Nim#2258]
```nimrod
import re
var tokenRE = re"""[\s,]*(~@|[\[\]{}()'`~^@]|"(?:[\\].|[^\\"])*"|;.*|[^\s\[\]{}()'"`@,;]+)"""
echo "(123 456)".findAll(tokenRE)
```
This should return something, as the same code with the nre library does,  and not go into an infinite loop.

**Comment by dom96** [comment]
Should we just adopt nre? Why haven't we at least adopted its fixes?

**Comment by def-** [comment]
nre seems to work better. But the fact that it uses optional_t makes addition to the stdlib difficult probably.

**Comment by dom96** [comment]
Hrm. Can we replace the ``optional_t`` usage with something else?

**Comment by def-** [comment]
This seems to be fixed, returns the same as nre now.
