### ISSUE TITLE
Character set in db_mysql

### ISSUE THREAD

**Issue by kemege** [Araq/Nim#2261]
Procedures in the `db_mysql` library don't seem to involve anything about character sets.

When I use `db_mysql.open` on my computer, the default character set is `latin1`, so I cannot work with unicode characters unless I call `mysql.set_character_set`. (I'm using Windows 7 and the libmysql.dll is shipped with pyQt5. Although it's version is not the same as the MySQL server, I don't think it has anything to do with the character set.)

As UTF-8 is the most used encoding in Nim, maybe we can add `mysql.set_character_set` into `db_mysql.open` to change the character set to UTF-8 after opening a connection, or provide a procedure in `db_mysql` which calls `mysql.set_character_set`?

**Comment by Varriount** [comment]
What do other interfaces to MySQL normally do? Personally, I would rather take the latter option, as setting the character encoding (even if it can be changed later) is a bit presumptuous.

**Comment by dom96** [comment]
We should add an option to ``open`` to set the character encoding it opens the connection with. This means every other ``db_*`` module needs it too.

**Comment by Araq** [comment]
This is now possible.
