### ISSUE TITLE
codegen error for empty tuple

### ISSUE THREAD

**Issue by fowlmouth** [Araq/Nim#2266]
causes this library to not compile https://github.com/MasonMcGill/tuples. TMP357 is used around line 542 in tuples.nim, I can't reproduce it otherwise
```c
//bad c
NIM_CONST TY181219 TMP357 = {{}
}
;
```

**Comment by MasonMcGill** [comment]
**Side note:** I separated the tests from the main module in https://github.com/MasonMcGill/tuples, so people can use it if they're interested, despite this bug popping up. 1 caveat: users of the "devel" branch of Nim will get a lot of warnings about "PNimrodNode" being deprecated. I'll fix this once Nim 0.10.4 is out.

**Comment by Araq** [comment]
Well please create a minimal test program for this.

**Comment by MasonMcGill** [comment]
Hi @Araq,

Here's your minimal test program:

```nim
import macros

proc impl(op: static[int]) = discard
proc impl(op: static[int], init: any) = discard

macro wrapper1: stmt = newCall(bindSym"impl", newLit(0))
macro wrapper2: stmt = newCall(bindSym"impl", newLit(0), newLit(0))

wrapper1() # Code generation for this succeeds.
wrapper2() # Code generation for this fails.
```

Also, I added a workaround (https://github.com/MasonMcGill/tuples/commit/13ac9d4c7d8b1bf09204b55cc79dca9b0effde7c) to the tuples library so this bug shouldn't affect anyone who wants to use it.
