### ISSUE TITLE
Question Mark in url gets dropped in the final executable. 

### ISSUE THREAD

**Issue by teroz** [Araq/Nim#2278]
![screenshot from 2015-03-06 15 48 37](https://cloud.githubusercontent.com/assets/853846/6526247/622b1658-c418-11e4-950b-3744b42cd42b.png)
Hi there
the question mark in any url gets dropped when a nim executable is created. 

`echo(getContent(url="http://6lines.com/products/?search=meh"))`

Code is compiled with the default C backed on ubuntu 14.10 x64

` nim c -r main.nim`

404 error is retuned

`Error: unhandled exception: 404 Not Found [HttpRequestError]`

Compiled C code still has the question mark in there

`grep -i 6lines.com -R nimcache/`

`nimcache/main.c:STRING_LITERAL(TMP1004, "http://6lines.com/products/?search=meh", 38);`

If I use double question marls in the url then it works fine

**Comment by def-** [comment]
I don't see any ampersand in your URL. Also this works for me with the current devel branch. It's a known bug with 0.10.2.

**Comment by teroz** [comment]
My mistake - I meant question mark

**Comment by teroz** [comment]
Correction - the compiled executable does have the correct url in there
`strings main | grep -i 6lines`
`http://6lines.com/products?search=meh`

**Comment by def-** [comment]
It's fixed in the devel branch, as I said. It was a bug in httpclient and uri modules.

**Comment by teroz** [comment]
excellent thank you
