### ISSUE TITLE
import statements with path components show inconsistent behavior.

### ISSUE THREAD

**Issue by oderwat** [Araq/Nim#2281]
I just found that `import ../dir/module` works but `import ../module` does not as it want to import `../ module` (notice the space). But `import "../module"` again does work. Afais the documentation does not specify anything about what is supposed to work besides simple names.

```nim
# import ../anything (gets ../ anything)
StmtList
  ImportStmt
    Prefix
      Ident !"../"
      Ident !"anything"

# import ../dir/anything
StmtList
  ImportStmt
    Infix
      Ident !"/"
      Prefix
        Ident !"../"
        Ident !"dir"
      Ident !"anything"

# import "../anything"
StmtList
  ImportStmt
    StrLit ../anything
```

**Comment by reactormonk** [comment]
It's a bug. https://github.com/Araq/Nim/blob/devel/compiler/importer.nim#L39

**Comment by oderwat** [comment]
I think I fixed it! Thank you to show me where about I had to search!
