### ISSUE TITLE
Incorrect codegen with parenthesized expressions with wrapped C++ types

### ISSUE THREAD

**Issue by dhasenan** [Araq/Nim#2292]
The nim code

    let length = (wall.p1 - wall.p2).length

is emitted as

    float length = (*wall).P1 - (*wall).P2.Length();

It should be emitted as

    float length = ((*wall).P1 - (*wall).P2).Length();

but the parentheses are omitted, leading to an eventual error:

    error: no match for ‘operator-’ (operand types are ‘Urho3D::Vector3’ and ‘float’)

(p1 and p2 are Vector3 from Urhonimo.)

Will come up with a complete minimal test case. The obvious fix would be to retain parentheses expressions in the AST through to codegen (assuming they aren't now) and emit them appropriately.

The workaround is to assign the value to a temporary variable:

    let delta = wall.p1 - wall.p2
    let length = delta.length

**Comment by dhasenan** [comment]
This is on the devel branch, encountered well before commit 819a2a03acb6bd47c4205be900f8b3f20e17c583 and still present at 41ce6571a32ecd63c67ba7f972c7fb1c0f4f9200. Haven't checked the release branch.

**Comment by reactormonk** [comment]
Could you please give a full code snippet?

**Comment by dhasenan** [comment]
paren.vim:

    {.emit: """
    class Vec {
    public:
      Vec operator-(Vec other) {
        return Vec();
      }

      float Length() {
        return 0;
      }
    }
    """ .}

    type
      Vec {.importcpp, nodecl.} = object

    proc `-`(a, b: Vec): Vec {.importcpp: "# - #".}
    proc length(a: Vec): cfloat {.importcpp: "Length".}

    var a, b: Vec
    echo((a - b).length())

To compile:

    nim cpp --parallelBuild:1 paren.vim

**Comment by fowlmouth** [comment]
`importcpp: "(# - #)"` should work, and it should probably be required instead of the compiler having to check if this is a binary expression

**Comment by reactormonk** [comment]
It doesn't seem to, it produces `N_NIMCALL(Vec, # - #)(Vec a, Vec b);`

**Comment by Araq** [comment]
Urhonimo has been fixed.
