### ISSUE TITLE
Failing test tgetfileinfo.nim / how to create the right exception?

### ISSUE THREAD

**Issue by oderwat** [Araq/Nim#2308]
The test **tgetfileinfo.nim** fails in line https://github.com/Araq/Nim/blob/devel/tests/stdlib/tgetfileinfo.nim#L83 with a segfault instead of the expected exception.

Looking at https://github.com/Araq/Nim/blob/devel/lib/pure/os.nim#L1999-L2000 this is not very surprising.

I would like to fix that but I am unsure about what exception should be generated and how?

```nim
 proc getFileInfo*(file: File): FileInfo =
+  if file.isNil:
+      raiseOSError(?????) # what's supposed to happen here?
   result = getFileInfo(file.getFileHandle())
```

**Comment by dom96** [comment]
A SIGSEGV is the expected result of calling this function with a nil param.

**Comment by oderwat** [comment]
Yeah. But the test fails because of that :) ... **so then the test should be fixed!**

**Comment by dom96** [comment]
indeed

**Comment by oderwat** [comment]
I guess testing for a segfault is not "so easy"... So I do a PR with just this part being removed from the test?

**Comment by dom96** [comment]
You could probably edit the test to make the SIGSEGV an expected crash at the end.

**Comment by oderwat** [comment]
OK I will try that.

**Comment by def-** [comment]
Fixed in here already: https://github.com/Araq/Nim/pull/2307

**Comment by oderwat** [comment]
Well.. Your code does not SIGSEGV anymore ... which we just learned is the way it should work?

Actually it answers my question though :+1:
