### ISSUE TITLE
Nim requires POSIX_SPAWN_USEVFORK

### ISSUE THREAD

**Issue by tongson** [Araq/Nim#2325]
Nim Version: 0.10.2

POSIX_SPAWN_USEVFORK is missing from musl <http://www.musl-libc.org>. See: <http://marc.info/?l=musl&m=140094278705289&w=2>
> This is not useful with musl. In principle we could just provide the flag as a no-op, but it's a really bad API design (exposing the implementation-detail rather than the semantics as the flag name) and since it doesn't affect ABI, I'd rather get apps which are using it fixed at the source level rather than adding a no-op flag.

**Comment by Araq** [comment]
Pretty sure that's fixed on devel. Can you check please?

**Comment by def-** [comment]
This should be fixed in the current devel branch. Can you give it a try?

**Comment by tongson** [comment]
Thank you for the quick response.

I'll try the devel branch and post an update. 
Regards.

**Comment by tongson** [comment]
Indeed it was fixed. Sorry for not looking deeper.

    # Non-GNU systems like TCC and musl-libc  don't define __USE_GNU, so we
    # can't get the magic number from spawn.h
    const POSIX_SPAWN_USEVFORK* = cint(0x40)
