### ISSUE TITLE
Emit pragma should emit code at earliest position

### ISSUE THREAD

**Issue by dhasenan** [Araq/Nim#2335]
Found when attempting to create a minimal test for another issue. This example isn't minimal but should be small enough to be usable.

    {.emit: """
    template <typename T>
    struct AWrapper {
    public:
      T value;
    };
    """.}

    type
      AWrapper{.importcpp, nodecl.}[T] = object
      IntWrapper = object
        w: AWrapper[cint]

    var c = IntWrapper()

This fails because the {.emit.} pragma's contents are emitted after type definitions. The compiler error given is `error: ‘AWrapper’ does not name a type`.

The emitted code (heavily abridged):

    struct intwrapper90009;
    struct  intwrapper90009  {
    AWrapper<int>  W;
    };
    template <typename T>
    struct AWrapper {
    public:
      T value;
    };

**Comment by dhasenan** [comment]
Build information: devel branch, revision d6c957e9b438ceb340c14139c9141ca102de4fa5, Linux Ubuntu 14.04 x64.

**Comment by Araq** [comment]
This is impossible to do with the current codegen. But we can give .emit an additional option in which section to put it.
