### ISSUE TITLE
build.sh's executable bit keeps getting removed in unrelated commits.

### ISSUE THREAD

**Issue by philip-wernersbach** [Araq/Nim#2345]
Looking at the [history for build.sh](https://github.com/Araq/Nim/commits/devel/build.sh) shows that build.sh's executable bit from my initial commit got removed in 61c5c92, which is an unrelated commit. Since then people have added and re-added the executable bit, but each time an unrelated commit has removed the executable bit again.

If this has happened on purpose, please disregard this issue and close it.

**Comment by Araq** [comment]
I don't care, ``chmod +x script;; ./script`` is VERY common in unix land anyway.
