### ISSUE TITLE
Regression in typeclasses (generic var x)

### ISSUE THREAD

**Issue by BlaXpirit** [Araq/Nim#2346]
```nim
type RNG64 = generic var rng
  rng.randomUint64() is uint64

proc randomInt*(rng: var RNG64; max: int): int = 4


type MyRNG* = object

proc randomUint64*(self: var MyRNG): uint64 = 4

var r = MyRNG()
echo r.randomInt(5)
```

This code works on 0.10.2 and slightly old 0.10.3 devel, but does not work on latest devel:

    (12, 6) Error: type mismatch: got (MyRNG, int literal(5))
    but expected one of:
    a0.randomInt(rng: var RNG64, max: int)

This caught me by surprise, [breaking my library](https://circleci.com/gh/BlaXpirit/nim-random/19)

**Comment by fowlmouth** [comment]
It looks like randomint should really accept RNG64 since it includes var in
its definition, as it would be var var T?

**Comment by BlaXpirit** [comment]
I've tried a few combinations, but not what *fowlmouth* suggested. I will try this tomorrow.

**Comment by BlaXpirit** [comment]
No, that doesn't help.

Ideally, I wouldn't even use `var` in the definition, I don't need to enforce it, but it didn't work without it.
