### ISSUE TITLE
Destructuring for loop

### ISSUE THREAD

**Issue by sid-code** [Araq/Nim#2347]
I was trying to destructure tuples in a for loop. The following code does not compile because the compiler doesn't like the parens.
```nim
for (x, y) in @[(3,5), (2,3)]:
  echo x + y
```

Is there a way to do this?

**Comment by def-** [comment]
No need for parentheses and you need to call `items` explicitly because with 2 loop variables `pairs` will be called by default:

```nimrod
for x, y in @[(3,5), (2,3)].items:
  echo x + y
```
