### ISSUE TITLE
Subrange of `not nil` string does not prove `not nil`

### ISSUE THREAD

**Issue by goob** [Araq/Nim#2356]
A subrange of a `not nil` string should be accepted as a `not nil` value during assignment.

```
type
  Foo = object
    foo: string not nil
    bar: string not nil

var f = Foo(foo: "foo")

f.bar = f.foo # works
f.bar = f.foo[0..0] # Error: cannot prove [](f.foo, 0..0) is not nil
```

Result: `Error: cannot prove [](f.foo, 0..0) is not nil`

Expected: Successful compilation.

Tested on current 10.3 build

>Nim Compiler Version 0.10.3 (2015-03-16) [Linux: amd64]

**Comment by Araq** [comment]
The stdlib doesn't give a damn about 'not nil' for now.
