### ISSUE TITLE
Can't access argument in proc from stmt passed in to a template

### ISSUE THREAD

**Issue by sid-code** [Araq/Nim#2365]
The following code works on Nim 0.10.2 but not on the latest pull from HEAD.

```nim
template doIt(body: stmt) {.immediate.} =
  proc res(str: string) =
    body

  res("hi")

doIt:
  echo str
```

The error message:

```
templatetest.nim(8, 7) Error: undeclared identifier: 'str'
```

What has changed and how can I achieve this on the latest version?

**Comment by Araq** [comment]
Parameters are now gensym'ed like local variables. Declare your template as '.immediate, dirty' and it works again. Re-open if it doesn't.
