### ISSUE TITLE
Error: field 'strVal' cannot be found

### ISSUE THREAD

**Issue by StefanSalewski** [Araq/Nim#2373]
$ cat t5.nim
import strutils, macros

macro gen_code(s: string): stmt =
  let iput = s.strVal

const
  bbb = "data.cfg"

echo bbb

gen_code(bbb)
#gen_code("data.cfg")

t5.nim(4, 14) Error: field 'strVal' cannot be found
stefan@AMD64X2 ~/t5 $ nim -v
Nim Compiler Version 0.10.3 (2015-03-19) [Linux: amd64]

Sorry, my first tests with macros, so I have no idea. With plain string literal it compiles fine.

**Comment by EXetoC** [comment]
you're passing in a string, not a NimNode. Perhaps you want a parameter of type stmt instead. However, the same error message appears then and I have no idea why.

**Comment by kirbyfan64** [comment]
The error seems to be because you're trying to access the `strVal` field, which is only available on real string literals.

Not sure how to get around that, though...

**Comment by EXetoC** [comment]
So, just buggy error reporting then?

**Comment by fowlmouth** [comment]
because string matches a variable string or a literal string
```nim
import macros
macro m (s:string): stmt =
  echo treerepr s
var x= "hi"
m x
m "hi"
```
output
```
Sym "x"
StrLit hi
```

**Comment by StefanSalewski** [comment]
Thanks for your comments.
Yes, I tried to follow this example:
http://nim-lang.org/tut2.html#generating-source-code

This is my first tests with macros. My final goal is to replace a big C GObject lib macro. Generally that macro should only generate a few lines of Nim source code -- most code is constant, with a few variable parameters. I thought that may be not that difficult. But maybe it is difficult, so I should ask in the Forum for  help...

**Comment by EXetoC** [comment]
Yes please do unless you suspect that it's related to an issue somewhere in the Nim distribution.

**Comment by StefanSalewski** [comment]
>because string matches a variable string or a literal string

$ cat t5.nim 
import strutils, macros

macro gen_code(s: string): stmt =
  var iput = s.strVal

var
  bbb = "data.cfg"

echo bbb

gen_code(bbb)

t5.nim(4, 14) Error: field 'strVal' cannot be found

**Comment by EXetoC** [comment]
```nim
import strutils, macros

macro m1(s: string{lit}): stmt =
  echo s.strVal

macro m2(s: string): stmt =
  echo s.strVal

macro m3(s: stmt): stmt =
  echo s.strVal

const
  S = "hi"

m1("hi")

# "Error: type mismatch: got (system.string)
# but expected one of:
# bug2.m1(s: system.string)"
#m1(S)

m2("hi")

# Error in 'm2' since it's not restricted to string *literals*
#m2(S)

m3("hi")

# Error in 'm3' since it takes any statement
#m3(S)
```

**Comment by Araq** [comment]
Well. It's not a bug.

**Comment by EXetoC** [comment]
Can't the error message contain more details?

**Comment by kirbyfan64** [comment]
I don't think that's really possible, considering that the compiler nodes are just another variant type.
