### ISSUE TITLE
cpuRelax not defined on ARM

### ISSUE THREAD

**Issue by def-** [Araq/Nim#2376]
Threadpool can't be used on ARM because `cpuRelax` is not defined. See the failing tests here: http://buildbot.nim-lang.org/builders/linux-arm5-builder/builds/206/steps/Run%20Testament/logs/stdio

The code for `cpuRelax` is in atomics.nim:

```nimrod
when (defined(x86) or defined(amd64)) and someGcc:
  proc cpuRelax* {.inline.} =
    {.emit: """asm volatile("pause" ::: "memory");""".}
elif (defined(x86) or defined(amd64)) and defined(vcc):
  proc cpuRelax* {.importc: "YieldProcessor", header: "<windows.h>".}
elif defined(icl):
  proc cpuRelax* {.importc: "_mm_pause", header: "xmmintrin.h".}
elif false:
  from os import sleep

  proc cpuRelax* {.inline.} = os.sleep(1)
```
Any reason the last block couldn't be an `else` instead? I can't really test this issue since I don't have an ARM machine.

**Comment by Araq** [comment]
I'd rather have assembler code for ARM instead.

**Comment by kirbyfan64** [comment]
Linux has this snippet of code (taken from [here](https://github.com/torvalds/linux/blob/master/arch/arm/include/asm/processor.h#L79)):

```
#if __LINUX_ARM_ARCH__ == 6 || defined(CONFIG_ARM_ERRATA_754327)
#define cpu_relax()			smp_mb()
#else
#define cpu_relax()			barrier()
#endif
```

`smp_mb` is defined in [barrier.h](https://github.com/torvalds/linux/blob/master/arch/arm/include/asm/barrier.h#L56), and `barrier` seems to be a `dump macro` or sorts usually defined something like this:

```c
#define barrier() asm volatile ("" ::: "memory")
```

**Comment by def-** [comment]
Good to see, then that's the same I proposed here: https://github.com/Araq/Nim/pull/2378
