### ISSUE TITLE
Await inside try block

### ISSUE THREAD

**Issue by sid-code** [Araq/Nim#2388]
These are the three limitations listed in the asyncdispatch module's docs:

* except statement (without try) does not work inside async procedures.
* The effect system (raises: []) does not work with async procedures.
* Can't await in a except body

The following code seems to comply:

```nim
import asyncdispatch

proc ap {.async.} =
  try:
    await ap()
    echo 5
  except:
    raise newException(Exception, "Oops!")
```

but the compiler throws an index out of bounds exception. Should the documentation read "cannot await in a try block"?

**Comment by dom96** [comment]
You're creating an infinite loop using this code because you are calling ``ap`` recursively.

**Comment by sid-code** [comment]
In my actual code I wasn't calling the proc recursively, I was calling `request` from the httpclient module.

**Comment by dom96** [comment]
This now works on my PC.
