### ISSUE TITLE
Forward declarations require parameter names to match and shouldn't

### ISSUE THREAD

**Issue by dhasenan** [Araq/Nim#2394]
Parameter names aren't part of the procedure signature and yet are used when matching a procedure implementation to its forward declaration. This should not be the case.

Reproduction case:

```
proc foo(i: int32): int32
proc foo(j: int32): int32 = j
```

Error message:

```prototype.nim(1, 5) Error: implementation of 'prototype.foo(i: int32)' expected```

**Comment by Araq** [comment]
On the contrary, they are part of the signature and need to match (think about named argument calls).
