### ISSUE TITLE
macros.genSym fails to generate a unique symbol

### ISSUE THREAD

**Issue by EXetoC** [Araq/Nim#2407]
```nim
import macros

macro m(): stmt =
  result = newStmtList(
    newVarStmt(newIdentNode($genSym()), newIntLitNode(0)),
    newVarStmt(newIdentNode($genSym()), newIntLitNode(0)))

m() # Error: redefinition of ':tmp'
```

Is this right? If not, then it's really difficult to figure out what to do.

**Comment by def-** [comment]
I don't think that's how you use `genSym`, see also https://github.com/Araq/Nim/blob/devel/tests/macros/tgensym.nim

**Comment by def-** [comment]
I don't think that's how you use `genSym`, see also https://github.com/Araq/Nim/blob/devel/tests/macros/tgensym.nim

This seems to work:

```nimrod
import macros

macro m(): stmt =
  result = newStmtList(
    newVarStmt(genSym(nskVar, "foo"), newIntLitNode(0)),
    newVarStmt(genSym(nskVar, "foo"), newIntLitNode(0)))

m()
```

**Comment by EXetoC** [comment]
Right, parentheses in the wrong places... thanks
