### ISSUE TITLE
Access to uninitialized string should raise an exception

### ISSUE THREAD

**Issue by trustable-code** [Araq/Nim#2430]
Example program:

```nim
try:
  var s: string
  echo(s[5])
except:
  echo(getCurrentExceptionMsg())
  echo(getCurrentException().getStackTrace())
```
Result: 
The program crashes with SIGSEGV.

Expected result: 
An Exception is thrown (e.g. "NullPointerException").

Tested with Nim devel 2015-03-30, test program compiled as debug.

**Comment by Araq** [comment]
This program "works" as expected.

**Comment by kirbyfan64** [comment]
I though Nim inserted null pointer checks in debug mode? Or do you have to enable them manually?
