### ISSUE TITLE
json {} proc is missing variant to handle varargs[string] (and naming is inconsistent)

### ISSUE THREAD

**Issue by maxgrenderjones** [Araq/Nim#2431]
Warning: nim newbie!

The `json` module has a ``{}`` operator defined, with a docstring that suggests it ought to take a `varargs[string]` so that users can provide a list of keys to safely index into a `json` object and get `nil` back if one of the intermediate keys is missing. However the only provided method takes a single `string` parameter:

```nim
proc `{}`*(node: JsonNode, key: string): JsonNode =
  ## Transverses the node and gets the given value. If any of the
  ## keys do not exist, returns nil
  result = node
  if isNil(node): return nil
  result = result[key]
```

(Aside: I think this method is equivalent to the  ``[]`` operator, and would anyway be covered by the `varargs[string]` version below, so perhaps it's actually redundant?)

It would therefore make sense if we had a varargs[string] version to work with too:
```nim
proc `{}`*(node: JsonNode, keys: varargs[string]): JsonNode =
  ## Transverses the node and gets the given value. If any of the
  ## keys do not exist, returns nil
  result = node
  for key in keys:
    if isNil(result) or not result.hasKey(key):
      return nil
    else:
      result=result[key]
```

And while we're about it, ``{}=`` takes `names` as an argument, however everywhere else in the module, such functionality is denoted by `key`. For consistency, I'd therefore recommend renaming `names` to `keys` (a breaking change, but isn't that what the pre v1 is for?)

```nim
proc `{}=`*(node: JsonNode, keys: varargs[string], value: JsonNode) =
  ## Transverses the node and tries to set the value at the given location
  ## to `value` If any of the keys are missing, they are added
  var node = node
  for i in 0..(keys.len-2):
    if isNil(node[keys[i]]):
      node[keys[i]] = newJObject()
    node = node[keys[i]]
  node[keys[keys.len-1]] = value
```

**Comment by dom96** [comment]
Sure, make a PR :)
