### ISSUE TITLE
At compile time, assigning string or seq to `let` variable becomes reference instead of copy

### ISSUE THREAD

**Issue by goob** [Araq/Nim#2432]
At compile time, if I have a proc that takes an object as a `var` parameter, and we assign a `seq` or `string` property of that object to a `let` variable, and then assign a new value to the same object property, the change is reflected in our `let` variable. 

```
type
  Test = object
    value: seq[int]

proc testBug(self:var Test) =
  let vCopy = self.value   # copy the @[123] seq
  self.value = @[456]
  echo vCopy               # echos @[456], expected @[123]

static:
  var t = Test(value: @[123])
  t.testBug()
```

So the `vCopy` variable gets updated when the `self.value` property is updated.

If we make `vCopy` a `var` instead of a `let`, this does not occur.

>Nim Compiler Version 0.10.3 (2015-03-29) [Linux: amd64]

-----

EDIT: Example can be simplified to use a `string` or `seq` directly. Doesn't need to be an object property.

```
proc testBug(self:var seq[int]) =
  let vCopy = self
  self = @[456]
  echo vCopy    # echos @[456], expected @[123]

static:
  var t = @[123]
  t.testBug()
```

**Comment by Araq** [comment]
At runtime the same can and does happen. We have no borrow checking.

**Comment by goob** [comment]
@Araq 

Doesn't happen for me at runtime. If I get rid of `static:` it echos `@[123]`.

I don't understand what borrow checking has to do with it. Aren't strings and sequences supposed to be copied on assignment? Of the `string` type, the manual states: *"The assignment operator for strings always copies the string"* and it says that strings are *"merely a sequence of bytes"*.

Having assignment to a local `var` behave differently than assignment to a local `let` is surprising to me. I wouldn't think it would change the meaning of the code (aside from mutability). And having it behave differently at compile time is even more surprising.
