### ISSUE TITLE
[performance][codegen][js] Project compiles to JS 14 times slower than to native.

### ISSUE THREAD

**Issue by yglukhov** [Araq/Nim#2438]
Don't know if it's a good time for such issue, but it really makes hard to use Nim when targeting JS. Sample project:
```sh
git clone https://github.com/yglukhov/nimx
cd nimx
nimble install
cd test
time nake js
```
The build process takes approximately 4 minutes, while building to native target takes 17 seconds.

**Comment by def-** [comment]
Did you build your compiler with `./koch boot -d:release`? 4 minutes seems like quite a lot, takes 12 seconds on my pretty old machine.

**Comment by yglukhov** [comment]
Ahh, -d:release took it down to 14 seconds. Thank you.
