### ISSUE TITLE
Illegal storage access when using typetraits on tuple

### ISSUE THREAD

**Issue by bluenote10** [Araq/Nim#2447]
I'm not really sure if this is related to one of the other reports of a `SIGSEGV: Illegal storage access`, but this crashes for me:

    import typetraits

    proc takesTuple(t: tuple) =
      echo t
      echo t.type.name # crashes
      echo t.type.arity # crashes
      echo repr(t.type) # crashes as well, but with: Error: internal error: GetUniqueType, No stack traceback available

    var
      t = (1, "Test", (1,2,3), 3.14)

    takesTuple(t)

I'm running nim 0.10.2 on Ubuntu 12.04 (will try later on 0.10.3 / Ubuntu 14.04).

**Comment by def-** [comment]
You can use `./koch temp c foo.nim` to get a stacktrace:

```
Traceback (most recent call last)
nim.nim(94)              nim
nim.nim(56)              handleCmdLine
main.nim(251)            mainCommand
main.nim(62)             commandCompileToC
modules.nim(203)         compileProject
modules.nim(151)         compileModule
passes.nim(197)          processModule
passes.nim(137)          processTopLevelStmt
sem.nim(446)             myProcess
sem.nim(420)             semStmtAndGenerateGenerics
semstmts.nim(1346)       semStmt
semexprs.nim(893)        semExprNoType
semexprs.nim(2115)       semExpr
semexprs.nim(876)        semDirectOp
semexprs.nim(746)        semOverloadedCallAnalyseEffects
semcall.nim(326)         semOverloadedCall
semcall.nim(306)         semResolvedCall
seminst.nim(253)         generateInstance
seminst.nim(116)         instantiateBody
semexprs.nim(1328)       semProcBody
semexprs.nim(2198)       semExpr
semstmts.nim(1292)       semStmtList
semexprs.nim(2116)       semExpr
semexprs.nim(1725)       semMagic
semexprs.nim(876)        semDirectOp
semexprs.nim(746)        semOverloadedCallAnalyseEffects
semcall.nim(325)         semOverloadedCall
semcall.nim(159)         resolveOverloads
semcall.nim(70)          pickBestCandidate
sigmatch.nim(1600)       matches
sigmatch.nim(1563)       matchesAux
sigmatch.nim(1425)       prepareOperand
semexprs.nim(26)         semOperand
semexprs.nim(2077)       semExpr
semexprs.nim(2126)       semExpr
semexprs.nim(877)        semDirectOp
semexprs.nim(868)        afterCallActions
semmagic.nim(155)        magicsAfterOverloadResolution
semmagic.nim(70)         semTypeTraits
semmagic.nim(57)         evalTypeTrait
ast.nim(929)             len
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by bluenote10** [comment]
Somehow I produce `Illegal storage access` a lot currently. Here is another minimal example (this was a result from generating C bindings, so the use of the enum here is nonsense -- but just as a example):

    type 
      EyeType* = enum 
        Eye_Left = 0,
        Eye_Right = 1,
        Eye_Count = 2, 
        Eye_EnumSize = 0x7FFFFFFF # crash depends on this line
                                  # commenting it out compiles fine!        
    type 
      HmdDesc* = object
        perEyeSomething : array[Eye_Count, int]

The traceback in this case:

    Traceback (most recent call last)
    nim.nim(94)              nim
    nim.nim(56)              handleCmdLine
    main.nim(251)            mainCommand
    main.nim(62)             commandCompileToC
    modules.nim(203)         compileProject
    modules.nim(151)         compileModule
    passes.nim(197)          processModule
    passes.nim(137)          processTopLevelStmt
    sem.nim(446)             myProcess
    sem.nim(420)             semStmtAndGenerateGenerics
    semstmts.nim(1346)       semStmt
    semexprs.nim(893)        semExprNoType
    semexprs.nim(2203)       semExpr
    semstmts.nim(716)        semTypeSection
    semstmts.nim(648)        typeSectionRightSidePass
    semtypes.nim(1247)       semTypeNode
    semtypes.nim(661)        semObjectNode
    semtypes.nim(571)        semRecordNodeAux
    semtypes.nim(586)        semRecordNodeAux
    semtypes.nim(1192)       semTypeNode
    semtypes.nim(264)        semArray
    SIGSEGV: Illegal storage access. (Attempt to read from nil?)

This is with nim 0.10.3 now on Ubuntu 14.04.
