### ISSUE TITLE
Changing ':' to '=' results in compiler crash in GetUniqueType

### ISSUE THREAD

**Issue by endragor** [Araq/Nim#2456]
I made a typo using `=` instead of `:` in var declaration. It resulted in compiler crash:
```
Error: internal error: GetUniqueType
No stack traceback available
```

The shortest way to reproduce:
```nim
var bug = int
```

**Comment by reactormonk** [comment]
Duplicate of https://github.com/Araq/Nim/issues/1183 - it's fixed in devel.
