### ISSUE TITLE
Passing negative number to newSeq results in cryptic error

### ISSUE THREAD

**Issue by endragor** [Araq/Nim#2460]
Reproduces with:
```nim
var mySeq = newSeq[int](-3)
```

Running this results in:
```
Traceback (most recent call last)
test.nim(1)              test
system.nim(570)          newSeq
gc.nim(472)              newSeq
gc.nim(466)              newObj
SIGSEGV: Illegal storage access. (Try to compile with -d:useSysAssert -d:useGcAssert for details.)
```

Notice that changing `-3` to a larger number (e.g. `-3000`) results in a deeper stacktrace (the error occurs one line earlier):
```nim
Traceback (most recent call last)
test.nim(1)              test
system.nim(570)          newSeq
gc.nim(472)              newSeq
gc.nim(465)              newObj
gc.nim(440)              rawNewObj
alloc.nim(569)           rawAlloc
```

Surprisingly, passing `-1` and `-2` does not produce any error.

Would be nice, at least in debug mode, to get a friendly assertion error when a negative value is passed to procedures in gc.nim/alloc.nim.

**Comment by reactormonk** [comment]
There is an additional flag which checks for this, it's `useSysAssert`, which gives the rather unhelpful message `[SYSASSERT] rawAlloc 2`.

**Comment by dom96** [comment]
``newSeq`` just needs an ``assert``.

**Comment by reactormonk** [comment]
`newSeq` is magic, might be a bit more hairy.

**Comment by Araq** [comment]
newSeq's input type needs to be Natural.
