### ISSUE TITLE
Negative slice indices could be more logical and intuitive

### ISSUE THREAD

**Issue by jlp765** [Araq/Nim#2468]
[10.. -2]  removes one element from the tail of the array/seq

In Python  (and more logically),  [10:-2] removes two elements from the tail, and obviously [10:-1] removes one element.

For logical and compatibility reasons, can Nim be changed?

**Comment by goob** [comment]
Given that the range is inclusive of the second index, I think it makes sense the way it is. I don't know how I'd picture `-2` referencing the third-to-last element.

**Comment by Araq** [comment]
We just got rid of this misfeature.

**Comment by Araq** [comment]
See #1979 for a lenghty discussion of the problems it causes.
