### ISSUE TITLE
Asyncnet doesn't seem to close connections properly

### ISSUE THREAD

**Issue by sid-code** [Araq/Nim#2469]
I added a ctrl-c handler to the example in the asyncnet documentation to close connections properly, but it's still not working. Here's how to replicate the issue:

* Start server
* Connect using telnet
* Kill server with ^C (this should close all connections)
* Try to run server again

The program throws an exception saying that the address is already in use, which I take to mean that the connections didn't close properly in the first place. 

I noticed that before step 3, if I closed the connection from the telnet client, the server can bind on the port again.

Is this a bug or did I not write the handler correctly?
```nim
import asyncnet, asyncdispatch

var clients {.threadvar.}: seq[AsyncSocket]

proc processClient(client: AsyncSocket) {.async.} =
  while true:
    let line = await client.recvLine()
    for c in clients:
      await c.send(line & "\c\L")

var server = newAsyncSocket()
proc serve() {.async.} =
  clients = @[]
  server.bindAddr(Port(12342))
  server.listen()

  while true:
    let client = await server.accept()
    clients.add client

    asyncCheck processClient(client)

proc handler {.noconv.} =
  for c in clients:
    c.close()
  server.close()
  quit 0

setControlCHook(handler)

asyncCheck serve()
runForever()
```

Compiled with the latest version of the compiler

**Comment by dom96** [comment]
I don't think this is a bug with the implementation of ``close``, it is due to the socket being put into a ``TIME_WAIT`` state by the OS. If you close the telnet connection before killing the server then you should not see that error.

You can also set ``OptReuseAddr`` on the server socket to prevent that error from happening by using ``setSockOpt``.
