### ISSUE TITLE
Add return value to incl/excl procedures

### ISSUE THREAD

**Issue by endragor** [Araq/Nim#2474]
It's sometimes useful to know whether your call to `incl`/`excl` actually changed the set. In other words, to know whether the element existed in the set at the point you were making the call.

But right now `incl`/`excl` procedures return nothing. Performance-wise it should be cheap, if not free, to make them have `true`/`false` return values.
The procedures will have to be marked as `{.discardable.}` to preserve backward compatibility and due to the fact that often you actually do not need the return value.

**Comment by Araq** [comment]
> *Performance-wise it should be cheap, if not free, to make them have true/false return values.*

But it's not. And we usually have ``containsOrIncl`` as the "test and set" operation.

**Comment by endragor** [comment]
I can see that it's definitely free for HashSet/OrderedSet.

And what about `excl`?

**Comment by Araq** [comment]
But it's not free for ``system.set`` and ``intsets`` and consistency is a nice thing.

**Comment by endragor** [comment]
OK, how about poor `excl` procedure that was deprived of having `true`/`false` analogue?
I can't think of a good name though. Could be something like `exclOrFalse`.
