### ISSUE TITLE
Initial size parameter for toSeq

### ISSUE THREAD

**Issue by endragor** [Araq/Nim#2485]
Sometimes, when you want to combine iterator output into a sequence, you know the expected sequence size. So having additional `initialSize` parameter for `toSeq` procedure would be useful.

An example use case is converting HashSet into a sequence. As I understand, right now, you have to do this:
```nim
toSeq(items(mySet))
```
And this would be more efficient:
```nim
toSeq(items(mySet), len(mySet))
```

**Comment by def-** [comment]
I don't know if this is such a common usecase.

**Comment by endragor** [comment]
I ran into this when I wanted to get sorted list of values from a set. Since there is no TreeSet in the standard library, I had to use HashSet, then make a sequence, and sort it. I didn't care much about algorithm efficiency at that point, but just noticed that `toSeq` doesn't allow me to specify initial size, forcing memory reallocations that could be removed if it had additional parameter.

I believe the additional parameter with reasonable default will not harm. There can definitely be more use cases when you can predict the number of items the iterator will generate.

**Comment by Araq** [comment]
I don't see it. toSeq takes an *iterator* and turns it into a seq. It is usually not known how often the iterator will yield.

**Comment by endragor** [comment]
I still disagree here.

I searched through Nim code (compiler and stdlib), and it was actually pretty hard to find iterators where you don't know the number of yielded elements in advance - a couple of examples is working with files or command line options.

The most common use case here is iterator for *any* collection type. Set is just one of the examples where this might be needed. For (almost) every collection you always its size, and you can iterate through it. But it's not necessary that the author of the collection will provide sequence generating procedure for it (you did not provide one for Set, Table, Queue, JArray, JObject, XmlNode).
Since there is no generic sorting procedure, if a collection does not have `sort` implemented, you are forced to convert the collection into sequence first, and then sort it. This is where efficient `toSeq` would come in handy.
There can be more cases when you want to get `seq` from a collection, just because some library can only work with seqs (openarrays).

Also, even if you don't *know* the exact number of elements that is going to be yielded, sometimes you can *guess* it, and your guess can be better than the default capacity. For example, if I have an iterator that generates primes up to a certain number, I can be sure that by allocating sequence with capacity equal to `number div 2`, I will be safe from memory reallocations.
When you work with command line parameters, you can expect that the iterator will yield less than 20 elements in ~99.99% cases.

**Comment by bluenote10** [comment]
I think that there are many problems that can be divided into (1) construction and (2) actual use. I also think it is a fairly common pattern to use something like a set for construction (for fast insert with duplicate removal) but subsequent use requires O(1) random random access indexing rather than actual set operations. Example in Scala:

    val ranked = collectionOfArbitraryValues.to[SortedSet]
                                            .to[Array]

After that you can operate on the ordered values `ranked(i)` in O(1), which is a handy data structure for many statistical algorithms.
