### ISSUE TITLE
Online documentation should have a release version

### ISSUE THREAD

**Issue by FedericoCeratto** [Araq/Nim#2492]
The HTML pages should contain the release version or the name of the development branch they were generated from.
Also, it could be nice to have every version online. I'd suggest:
http://nim-lang.org/docs/version_number/pagename.html
http://nim-lang.org/docs/latest/   <-- symlink to the latest stable release
http://nim-lang.org/docs/devel/pagename.html    <-- devel branch

This also fixes #1949 and removes the risk of mixing old/unmaintained doc pages and new ones.

**Comment by trustable-code** [comment]
Good idea. I suggest to have two directories:
http://nim-lang.org/docs/stable/
http://nim-lang.org/docs/devel/

**Comment by dom96** [comment]
The docs now live in http://nim-lang.org/docs/lib.html

**Comment by FedericoCeratto** [comment]
@dom96: there is no version number in the path tho. People using any version different from the latest will not be able to access the correct documentation.

**Comment by andreaferretti** [comment]
Why was this closed? Keeping the current and previous versions of the documentation seems easy to do and very useful. I am never sure whether the docs I am browsing are up to date. Is the docs for devel even online anywhere?

**Comment by Araq** [comment]
The docs are versionized now, that's why it was closed. There is no devel version of the docs, so if there is no version, it refers to the latest official release.
