### ISSUE TITLE
Testing 0-element arrays for equality causes an internal error

### ISSUE THREAD

**Issue by MasonMcGill** [Araq/Nim#2498]
Basically the same as issue as #2489, only now the offending snippet deals with 0-element arrays:

```nim
var a: array[0, int]
var b: array[0, int]
discard a == b
```

2176ea7 doesn't fix this, unfortunately.

**Comment by Araq** [comment]
0-element arrays should produce an error message. 0-element arrays are not supported at all!

**Comment by MasonMcGill** [comment]
Darn. It did work, actually. I've been using 0-dimensional arrays for the past couple months, then pulled the latest `devel` branch hoping it would fix some obscure code generation bug I was experiencing.

A couple months ago I switched from using tuples to arrays to represent n-dimensional tensor indices (using tuples required a lot more code generation--making the switch let me compile my test suite in ~0.3 seconds instead of <10 seconds!) It would be great if this could be supported at some point. 0-D arrays come up...
- When scalars interact with tensors (e.g. via [promotion/broadcasting](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)).
- In the base cases of operations defined recursively on arbitrary-rank tensors (e.g. printing, folds/reductions, index transformations).

Though I understand the "low priority" tag given that the manual doesn't actually say this should work : )

**Comment by BlaXpirit** [comment]
0 length arrays are important. Consider procs that accept or return arrays of variable static length.

**Comment by Araq** [comment]
@MasonMcGill How hard is it to work around this?

**Comment by MasonMcGill** [comment]
So long as it's just me using my library, I can work around it. I could just roll my own `array` using `static[T]`, and start using it everywhere.

If I make my library accessible to other people (which I hope to do once 10.4 is out and I catch up with the documentation), this might be too awkward.

```nim
# The code we need:
let image = zeros(initGridIndices(256, 256, 3))
assert image.size == initGridIndices(256, 256, 3)

# The code we deserve:
let image = zeros([256, 256, 3])
assert image.size == [256, 256, 3]
```

(I know I could use converters to reduce the friction a bit, but I've run into a lot of issues mixing them with generics, so I'm hesitant to go down that road.)

**Comment by Araq** [comment]
Er, I feel stupid, isn't ``[]`` an array of size zero in Nim? That surely means we *do* support it!
