### ISSUE TITLE
Tests inside lib/isMainModule are not run

### ISSUE THREAD

**Issue by BlaXpirit** [Araq/Nim#2517]
Add `doAssert false` to e.g. */lib/pure/actors.nim*, run `koch test c lib`. It still succeeds.

**Comment by def-** [comment]
All the tests are just compiled. Running them as well is a bit difficult, since we don't know what they are supposed to output and many are not even tests, for example asynchttpyserver just starts and http server and lets it run.

**Comment by reactormonk** [comment]
How about going by exit code?

**Comment by def-** [comment]
> How about going by exit code?

Yes, that was my plan, but then I noticed the main-blocks that never finish.

**Comment by reactormonk** [comment]
Which ones? I'd say rewrite the ones that don't.

**Comment by Araq** [comment]
Test for 'when defined(testing)' instead of 'when isMainModule' and update the stdlib please.

**Comment by BlaXpirit** [comment]
I'm not really interested in this, but I may do it in a few days.
