### ISSUE TITLE
Hex literals should represent bit-patterns, not numbers.

### ISSUE THREAD

**Issue by ReneSac** [Araq/Nim#2539]
The compiler seems to convert hex literals to `int` and then try to assign that numerical value to the variable, and that is wrong. If we wanted a number, we would use a normal number. The following should work:
``` nim
let foo: int8 = 0xFF  # Error: type mismatch: got (int literal(255)) but expected 'int8'
echo foo  # should print -1

```
Of course there are "workarounds". Two very very elegant ways to specify -1 using hex literals currently: [/sarcasm]
``` nim
let foo:int8 = -0x01
let bar:int8 = 0xFFFF_FFFF_FFFF_FFFF  # this should give a compilation error.
echo foo == bar and foo == -1 # true
```
But for some things there are no workarounds:
``` nim
let bar: uint64 = 0xFFFF_FFFF_FFFF_FFFF  # Error: type mismatch: got (int literal(-1)) but expected 'uint64'
```

**Comment by ReneSac** [comment]
Some current alternatives pointed by flaviu:
```
let foo: int8 = int8(0xFF'u8)  # works even with 0xFF'u64, but still seems hackish
let bar = 0xFFFF_FFFF_FFFF_FFFF'u64
```

**Comment by ReneSac** [comment]
Things in binary and octal notation should also represent bit patterns. The following should work too:

```nim
let foo:int16 = '0b1000000000000000'
```

**Comment by Araq** [comment]
Well no. More complexity won't help us in reducing the number of bugs.
