### ISSUE TITLE
Object fields are case-insensitive.

### ISSUE THREAD

**Issue by MasonMcGill** [Araq/Nim#2551]
```nim
type Tup = tuple
  A, a: int

type Obj = object
  A, a: int

var x: Tup # This works.
var y: Obj # This doesn't.
```

Error message:
```
error: duplicate member ‘A’
 NI A;
    ^
```

**Comment by Varriount** [comment]
The question here is, which is incorrect? What kind of casing is supposed to apply to object, reference, and tuple members.

**Comment by reactormonk** [comment]
Nim is partially case-sensitive, so every identifier should be partially case-sensitive. It should toss a compiler error in both cases.
