### ISSUE TITLE
can not concat cstring and string

### ISSUE THREAD

**Issue by itsmeront** [Araq/Nim#2561]
"aCstring" & "aString" doesn't work.  Tried cstring.string but that doesn't work either.

**Comment by dom96** [comment]
Does ``$cstring & "string"`` work?

**Comment by itsmeront** [comment]
Yes it does.  I missed 
proc `$`(i: TNimrodIdent): string {.magic: "IdentToStr", noSideEffect.}
converts a Nimrod identifier to a string   Source

Tried string(cstring) and cstring.string but both of those did not work.  Thanks!

**Comment by dom96** [comment]
`$` is the universal toString operator for all types in Nim.
