### ISSUE TITLE
--cpu option order matters

### ISSUE THREAD

**Issue by def-** [Araq/Nim#2569]
```
$ nim --cpu:i386 -d:release --parallelBuild:1 c Tak
gcc -c  -w -O3 -fno-strict-aliasing  -I/media/nim/lib -o /home/def/nimcache/Tak.o /home/def/nimcache/Tak.c
$ nim -d:release --cpu:i386 --parallelBuild:1 c Tak
gcc -c  -w  -I/media/nim/lib -o /home/def/nimcache/Tak.o /home/def/nimcache/Tak.c
```

I can guess why this happens internally, but I'm not sure if it's intentional. At least this should be documented.

**Comment by Araq** [comment]
Why does that work without the 'c' command?

**Comment by def-** [comment]
My bad, there was a `c` of course.

**Comment by Araq** [comment]
well that's a serious bug. Why does it happen?

**Comment by def-** [comment]
`--cpu:XXX` overwrites the compile options that `-d:release` set.

**Comment by Araq** [comment]
But -d:release doesn't affect --cpu?

**Comment by def-** [comment]
`--cpu` doesn't seem to set anything on the gcc command line for me, so not sure how that would be in general.

**Comment by Araq** [comment]
In commands.nim there is this:
