### ISSUE TITLE
importcpp spec for procs uses proc return type for '0

### ISSUE THREAD

**Issue by dhasenan** [Araq/Nim#2578]
```
type Foo {.importcpp: "Foo", header: "tempctorwrap.h", nodecl.} [T] = object
proc constructFoo[T](): Foo[T] {.importcpp: "'0(@)", header: "tempctorwrap.h", nodecl.}
proc doFoo[T](t: T): int {.importcpp: "doFoo<'0>(@)", header: "tempctorwrap.h", nodecl.}
discard constructFoo[int]()
discard doFoo[string]("hello")
```

This shows the same problem two different ways. First, on line 2, I wrap the constructor for the C++ type `template <typename T> class Foo`. The method employed here works, though it should not -- the importcpp spec `'0(@)` should expand line 4 to "int()" but instead expands to `Foo<int>()`.

Second, on line 3, I wrap the templated method `doFoo` in the obvious way. The method is declared as returning a Nim int, which is emitted as `NI`. Line 5 instantiates the template with Nim's string type. The emitted code is:

```
doFoo<NI>(((NimStringDesc*) &TMP139));
```

Because the return type of the method differs from the template parameter type, Nim instantiates the template incorrectly, resulting in a type error from g++ (cannot convert `NimStringDesc*` to `long long int`).

**Comment by dhasenan** [comment]
It looks like this is my misunderstanding of the specification. `'0` represents procedure parameter types, not template parameter types.

**Comment by fowlmouth** [comment]
this is a new bug. '0 .. '9 now appears to represent the proc's parameters, it should be the template parameters. 
This is from urhonimo, it would try to import `SharedPtr<SharedPtr<T>>(@)`
```nim
proc constructSharedPtr*[T](): SharedPtr[T] {.importcpp: "Urho3D::SharedPtr<'*0>(@)",
  header: "Ptr.h", constructor.}
```

**Comment by dhasenan** [comment]
The documentation ( https://github.com/Araq/Nim/blob/devel/doc/nimc.txt#L497 ) suggests that the currently implemented behavior is the intended behavior.

**Comment by fowlmouth** [comment]
you're confusing `parameter` and `argument`
https://github.com/Araq/Nim/blob/devel/doc/nimc.txt#L463,L466
