### ISSUE TITLE
Type mismatch with "var var SomeType" in the inferred function signature.

### ISSUE THREAD

**Issue by GrundleTrundle** [Araq/Nim#2585]
I just updated from the devel branch, and some old code stopped compiling.  Here is the error I'm getting: 
```
render.nim(81, 4) Info: template/generic instantiation from here
render.nim(181, 14) Error: type mismatch: got (var RenderData, var var openarray[RenderPass], Mat2, int literal(5123), ptr RenderState)
but expected one of: 
render.render(rdat: var RenderData, passes: var openarray[RenderPass], proj: Mat2, indexType: int, overrideState: ptr RenderState)
```

Note the `var var openarray[RenderPass]`.   The call looks like this: 
```nim
render(rdat, rdat.passes, proj, SomeConstant, nil)
```
Where `rdat` is a var parameter to the function making the call to `render', and `rdat.passes` is a sequence. 

So far I have not been able to make a small testcase that reproduces the problem by removing a lot of the crap around the function and types involved.  But, I ran `git bisect` on the nim source tree, and it looks like `commit d4bca58b7d6896c0a67bc925970ee6511cbb5e21 (fixes #1809; implements overloading based on 'var T')` is the commit that broke it. 

If you need more information, I can take another stab getting a small example that shows the problem later in the evening.

**Comment by Araq** [comment]
Well yes. No idea how that commit broke it.

**Comment by GrundleTrundle** [comment]
Sorry for the delay.  This will reproduce it:

```nim
type
    RenderPass = object
       state: ref int

    RenderData* = object 
        fb: int              
        walls: seq[RenderPass]    

    Mat2 = int
    Vector2[T] = T
    Pixels=int

template use*(fb: int, st: stmt) : stmt = 
    echo "a ", $fb
    st
    echo "a ", $fb

proc render(rdat: var RenderData; passes: var openarray[RenderPass]; proj: Mat2; 
            indexType = 1) = 
    for i in 0 .. <len(passes):
        echo "blah ", repr(passes[i])



proc render2*(rdat: var RenderData; screenSz: Vector2[Pixels]; proj: Mat2) = 
    use rdat.fb:
        render(rdat, rdat.walls, proj, 1)
```

The `use` template seems to be key, I can't get it to happen without that.

Re that commit: I did have to `git bisect skip` one commit because I couldn't build it, so I suppose there is a chance that's not the exact commit, but only close to it.

**Comment by GrundleTrundle** [comment]
Thanks, verified it works in my full program.
