### ISSUE TITLE
The compiler should infer garbage collection status for unsafe memory.

### ISSUE THREAD

**Issue by philip-wernersbach** [Araq/Nim#2591]
See the discussion here: http://forum.nim-lang.org/t/1154

This is an enhancement request to correct unexpected behavior. In the case of allocating unsafe memory for a tuple or object using `allocShared`/`allocShared0` or some other method and then assigning to garbage collected fields in the tuple or object, the compiler should be able to statically infer at compile time that the unsafe memory does not initially contain garbage collected data, and should not attempt to collect the field on the first assignment.

**Comment by Araq** [comment]
Well but the compiler cannot infer that. ``ptr`` doesn't mean that's allocated via some alloc. It only means "pointer from somewhere". It might be a cast from a 'ref', it might be from 'alloc0' where the assignments do work, it might be from 'alloc' where it doesn't.

**Comment by philip-wernersbach** [comment]
I won't reopen, but this is possible for the use case I'm talking about. Consider the following:

```
type
    FooObj = object
        a: string
        b: string

var foo: ptr FooObj = cast[ptr FooObj](allocShared(...))
foo.a = x
foo.b = y
```

In this use case the compiler can see the allocation and the assignments in the same compilation unit. The compiler knows that what the pointer is pointing to is allocated from allocShared, and since the pointer hasn't been changed from that allocation, it can infer that those fields don't need to be collected before the first assignment, since there isn't garbage collected data in them yet.

The next hurdle is letting the compiler know that allocShared returns a memory pointer that doesn't contain GC'd data in it. Create a new pragma for that and mark allocShared with it.

**Comment by winksaville** [comment]
Here's what I'm using now and works ok except its inefficient as we create a prototype and then copy it to the allocated entity.  If we taught the compiler to do this there would be no copy overhead and which would definitely be a win.

```nim
proc initializer*[T](dest: pointer) {.inline.} =
  ## initializer initializes items on the shared heap
  ## which are allocated with alloc/create
  var prototype: T
  copyMem(dest, addr prototype, sizeof(prototype))

proc allocObject*[T](): ptr T =
  ## Allocate T using allocShared and initialize as
  ## a default object. You must use deallocShared
  ## to return to the shared heap and not leak the
  ## memory.
  result = cast[ptr T](allocShared(sizeof(T)))
  initializer[T](result)
```
