### ISSUE TITLE
Implement a thread-shared GC'd heap.

### ISSUE THREAD

**Issue by philip-wernersbach** [Araq/Nim#2592]
Nim desperately needs a GC'd heap that is shared by threads and can be used concurrently with the thread-specific GC'd heaps. People are currently working around the absence of this by passing unsafe memory between threads, which really defeats the purpose of using Nim in the first place.

As a suggestion, here is one way it could work:
```
var foo: ref FooObj
newShared(foo) # Allocates foo on the thread-shared GC'd heap.

# foo can be passed between threads here
```

Nim currently works around this by deep copying references, but it isn't really the same.

**Comment by Araq** [comment]
Except that it doesn't work. It needs to be ``shared ref Foo`` *everywhere* then for correctness. And this new GC needs to stop the world to work correctly etc etc etc. Instead we are getting overloading of assignment and destructors so atomic refcounting can be done for "cheap" sharing.
