### ISSUE TITLE
install from sources failed

### ISSUE THREAD

**Issue by rjammala** [Araq/Nim#2624]
I made sure that I was on the master branch and still hit this error.

[rjammalamadaka@localhost Nim]$ bin/nim c koch
config/nim.cfg(53, 2) Hint: added path: '/home/rjammalamadaka/.babel/pkgs/' [Path]
config/nim.cfg(54, 2) Hint: added path: '/home/rjammalamadaka/.nimble/pkgs/' [Path]
Hint: used config file '/home/rjammalamadaka/Nim/config/nim.cfg' [Conf]
Hint: used config file 'koch.nim.cfg' [Conf]
Hint: system [Processing]
lib/system.nim(147, 40) Warning: unknown magic 'Addr' might crash the compiler [UnknownMagic]
lib/system.nim(152, 39) Warning: unknown magic 'TypeOf' might crash the compiler [UnknownMagic]
lib/system.nim(229, 62) Warning: unknown magic 'DotDot' might crash the compiler [UnknownMagic]
lib/system.nim(237, 59) Warning: unknown magic 'DotDot' might crash the compiler [UnknownMagic]
lib/system.nim(3210, 31) Warning: unknown magic 'Plugin' might crash the compiler [UnknownMagic]
lib/system.nim(3242, 31) Warning: unknown magic 'ProcCall' might crash the compiler [UnknownMagic]
lib/system.nim(3251, 44) Warning: unknown magic 'Roof' might crash the compiler [UnknownMagic]
lib/system.nim(3269, 34) Warning: unknown magic 'XLenStr' might crash the compiler [UnknownMagic]
lib/system.nim(3270, 37) Warning: unknown magic 'XLenSeq' might crash the compiler [UnknownMagic]
Hint: koch [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: times [Processing]
lib/pure/times.nim(585, 30) Info: instantiation from here
lib/system.nim(229, 62) Warning: unknown magic 'DotDot' might crash the compiler [UnknownMagic]
Hint: posix [Processing]
Hint: parseopt [Processing]
lib/pure/parseopt.nim(59, 34) Warning: quoteIfContainsWhite is deprecated [Deprecated]
Hint: osproc [Processing]
Hint: strtabs [Processing]
Hint: hashes [Processing]
Hint: streams [Processing]
Hint: cpuinfo [Processing]
Hint: linux [Processing]
lib/pure/osproc.nim(647, 4) Error: undeclared identifier: 'defer'

[rjammalamadaka@localhost Nim]$ uname -a
Linux localhost.localdomain 2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 22:03:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[rjammalamadaka@localhost Nim]$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by kirbyfan64** [comment]
Your `nim` version is probably too old. Try rebuilding it from the C sources.

**Comment by rjammala** [comment]
Here are the complete steps I followed. Please let me know if something needs to be fixed.

[rjammalamadaka@localhost ~]$ git clone -b master git://github.com/Araq/Nim.git
Initialized empty Git repository in /home/rjammalamadaka/Nim/.git/
remote: Counting objects: 45454, done.        
remote: Compressing objects: 100% (85/85), done.        
remote: Total 45454 (delta 32), reused 0 (delta 0), pack-reused 45369        
Receiving objects: 100% (45454/45454), 36.54 MiB | 33.15 MiB/s, done.
Resolving deltas: 100% (34990/34990), done.
[rjammalamadaka@localhost ~]$ cd Nim
[rjammalamadaka@localhost Nim]$ git clone -b master --depth 1 git://github.com/nim-lang/csources
Initialized empty Git repository in /home/rjammalamadaka/Nim/csources/.git/
remote: Counting objects: 6840, done.        
remote: Compressing objects: 100% (355/355), done.        
remote: Total 6840 (delta 6507), reused 6764 (delta 6484), pack-reused 0        
Receiving objects: 100% (6840/6840), 17.21 MiB | 33.47 MiB/s, done.
Resolving deltas: 100% (6507/6507), done.
[rjammalamadaka@localhost Nim]$ cd sources && sh build.sh
bash: cd: sources: No such file or directory
[rjammalamadaka@localhost Nim]$ cd csources && sh build.sh
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/nim.c -o c_code/2_2/nim.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_system.c -o c_code/2_2/stdlib_system.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/testability.c -o c_code/2_2/testability.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/commands.c -o c_code/2_2/commands.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_os.c -o c_code/2_2/stdlib_os.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_strutils.c -o c_code/2_2/stdlib_strutils.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_parseutils.c -o c_code/2_2/stdlib_parseutils.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_times.c -o c_code/2_2/stdlib_times.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_posix.c -o c_code/2_2/stdlib_posix.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/msgs.c -o c_code/2_2/msgs.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/options.c -o c_code/2_2/options.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/lists.c -o c_code/2_2/lists.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_strtabs.c -o c_code/2_2/stdlib_strtabs.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_hashes.c -o c_code/2_2/stdlib_hashes.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_osproc.c -o c_code/2_2/stdlib_osproc.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_streams.c -o c_code/2_2/stdlib_streams.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_cpuinfo.c -o c_code/2_2/stdlib_cpuinfo.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_linux.c -o c_code/2_2/stdlib_linux.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_sets.c -o c_code/2_2/stdlib_sets.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_math.c -o c_code/2_2/stdlib_math.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_tables.c -o c_code/2_2/stdlib_tables.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/ropes.c -o c_code/2_2/ropes.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/platform.c -o c_code/2_2/platform.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/crc.c -o c_code/2_2/crc.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_sockets.c -o c_code/2_2/stdlib_sockets.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_unsigned.c -o c_code/2_2/stdlib_unsigned.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/nversion.c -o c_code/2_2/nversion.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/condsyms.c -o c_code/2_2/condsyms.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/idents.c -o c_code/2_2/idents.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/extccomp.c -o c_code/2_2/extccomp.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/wordrecg.c -o c_code/2_2/wordrecg.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/nimblecmd.c -o c_code/2_2/nimblecmd.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_parseopt.c -o c_code/2_2/stdlib_parseopt.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/lexer.c -o c_code/2_2/lexer.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/nimlexbase.c -o c_code/2_2/nimlexbase.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/llstream.c -o c_code/2_2/llstream.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/nimconf.c -o c_code/2_2/nimconf.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/main.c -o c_code/2_2/main.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/ast.c -o c_code/2_2/ast.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_intsets.c -o c_code/2_2/stdlib_intsets.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/idgen.c -o c_code/2_2/idgen.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/astalgo.c -o c_code/2_2/astalgo.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/rodutils.c -o c_code/2_2/rodutils.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/syntaxes.c -o c_code/2_2/syntaxes.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/parser.c -o c_code/2_2/parser.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/pbraces.c -o c_code/2_2/pbraces.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/filters.c -o c_code/2_2/filters.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/renderer.c -o c_code/2_2/renderer.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/filter_tmpl.c -o c_code/2_2/filter_tmpl.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/rodread.c -o c_code/2_2/rodread.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/types.c -o c_code/2_2/types.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/trees.c -o c_code/2_2/trees.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_memfiles.c -o c_code/2_2/stdlib_memfiles.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/rodwrite.c -o c_code/2_2/rodwrite.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/passes.c -o c_code/2_2/passes.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/magicsys.c -o c_code/2_2/magicsys.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/nimsets.c -o c_code/2_2/nimsets.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/bitsets.c -o c_code/2_2/bitsets.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/importer.c -o c_code/2_2/importer.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/lookups.c -o c_code/2_2/lookups.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/semdata.c -o c_code/2_2/semdata.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/treetab.c -o c_code/2_2/treetab.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/vmdef.c -o c_code/2_2/vmdef.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/prettybase.c -o c_code/2_2/prettybase.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_lexbase.c -o c_code/2_2/stdlib_lexbase.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/sem.c -o c_code/2_2/sem.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/semfold.c -o c_code/2_2/semfold.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/saturate.c -o c_code/2_2/saturate.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/procfind.c -o c_code/2_2/procfind.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/pragmas.c -o c_code/2_2/pragmas.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/semtypinst.c -o c_code/2_2/semtypinst.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/sigmatch.c -o c_code/2_2/sigmatch.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/parampatterns.c -o c_code/2_2/parampatterns.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/pretty.c -o c_code/2_2/pretty.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/docgen.c -o c_code/2_2/docgen.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/docutils_rstast.c -o c_code/2_2/docutils_rstast.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_json.c -o c_code/2_2/stdlib_json.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_unicode.c -o c_code/2_2/stdlib_unicode.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/docutils_rst.c -o c_code/2_2/docutils_rst.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/docutils_rstgen.c -o c_code/2_2/docutils_rstgen.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/docutils_highlite.c -o c_code/2_2/docutils_highlite.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_sequtils.c -o c_code/2_2/stdlib_sequtils.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_algorithm.c -o c_code/2_2/stdlib_algorithm.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/sempass2.c -o c_code/2_2/sempass2.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/guards.c -o c_code/2_2/guards.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_xmltree.c -o c_code/2_2/stdlib_xmltree.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_macros.c -o c_code/2_2/stdlib_macros.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_cgi.c -o c_code/2_2/stdlib_cgi.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/stdlib_cookies.c -o c_code/2_2/stdlib_cookies.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/typesrenderer.c -o c_code/2_2/typesrenderer.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/transf.c -o c_code/2_2/transf.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/cgmeth.c -o c_code/2_2/cgmeth.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/lambdalifting.c -o c_code/2_2/lambdalifting.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/lowerings.c -o c_code/2_2/lowerings.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/vm.c -o c_code/2_2/vm.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/vmgen.c -o c_code/2_2/vmgen.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/vmdeps.c -o c_code/2_2/vmdeps.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/evaltempl.c -o c_code/2_2/evaltempl.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/aliases.c -o c_code/2_2/aliases.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/patterns.c -o c_code/2_2/patterns.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/semmacrosanity.c -o c_code/2_2/semmacrosanity.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/semparallel.c -o c_code/2_2/semparallel.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/cgen.c -o c_code/2_2/cgen.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/ccgutils.c -o c_code/2_2/ccgutils.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/cgendata.c -o c_code/2_2/cgendata.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/ccgmerge.c -o c_code/2_2/ccgmerge.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/jsgen.c -o c_code/2_2/jsgen.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/passaux.c -o c_code/2_2/passaux.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/depends.c -o c_code/2_2/depends.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/docgen2.c -o c_code/2_2/docgen2.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/service.c -o c_code/2_2/service.o
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/2_2/modules.c -o c_code/2_2/modules.o
gcc -o ../bin/nim  c_code/2_2/nim.o c_code/2_2/stdlib_system.o c_code/2_2/testability.o c_code/2_2/commands.o c_code/2_2/stdlib_os.o c_code/2_2/stdlib_strutils.o c_code/2_2/stdlib_parseutils.o c_code/2_2/stdlib_times.o c_code/2_2/stdlib_posix.o c_code/2_2/msgs.o c_code/2_2/options.o c_code/2_2/lists.o c_code/2_2/stdlib_strtabs.o c_code/2_2/stdlib_hashes.o c_code/2_2/stdlib_osproc.o c_code/2_2/stdlib_streams.o c_code/2_2/stdlib_cpuinfo.o c_code/2_2/stdlib_linux.o c_code/2_2/stdlib_sets.o c_code/2_2/stdlib_math.o c_code/2_2/stdlib_tables.o c_code/2_2/ropes.o c_code/2_2/platform.o c_code/2_2/crc.o c_code/2_2/stdlib_sockets.o c_code/2_2/stdlib_unsigned.o c_code/2_2/nversion.o c_code/2_2/condsyms.o c_code/2_2/idents.o c_code/2_2/extccomp.o c_code/2_2/wordrecg.o c_code/2_2/nimblecmd.o c_code/2_2/stdlib_parseopt.o c_code/2_2/lexer.o c_code/2_2/nimlexbase.o c_code/2_2/llstream.o c_code/2_2/nimconf.o c_code/2_2/main.o c_code/2_2/ast.o c_code/2_2/stdlib_intsets.o c_code/2_2/idgen.o c_code/2_2/astalgo.o c_code/2_2/rodutils.o c_code/2_2/syntaxes.o c_code/2_2/parser.o c_code/2_2/pbraces.o c_code/2_2/filters.o c_code/2_2/renderer.o c_code/2_2/filter_tmpl.o c_code/2_2/rodread.o c_code/2_2/types.o c_code/2_2/trees.o c_code/2_2/stdlib_memfiles.o c_code/2_2/rodwrite.o c_code/2_2/passes.o c_code/2_2/magicsys.o c_code/2_2/nimsets.o c_code/2_2/bitsets.o c_code/2_2/importer.o c_code/2_2/lookups.o c_code/2_2/semdata.o c_code/2_2/treetab.o c_code/2_2/vmdef.o c_code/2_2/prettybase.o c_code/2_2/stdlib_lexbase.o c_code/2_2/sem.o c_code/2_2/semfold.o c_code/2_2/saturate.o c_code/2_2/procfind.o c_code/2_2/pragmas.o c_code/2_2/semtypinst.o c_code/2_2/sigmatch.o c_code/2_2/parampatterns.o c_code/2_2/pretty.o c_code/2_2/docgen.o c_code/2_2/docutils_rstast.o c_code/2_2/stdlib_json.o c_code/2_2/stdlib_unicode.o c_code/2_2/docutils_rst.o c_code/2_2/docutils_rstgen.o c_code/2_2/docutils_highlite.o c_code/2_2/stdlib_sequtils.o c_code/2_2/stdlib_algorithm.o c_code/2_2/sempass2.o c_code/2_2/guards.o c_code/2_2/stdlib_xmltree.o c_code/2_2/stdlib_macros.o c_code/2_2/stdlib_cgi.o c_code/2_2/stdlib_cookies.o c_code/2_2/typesrenderer.o c_code/2_2/transf.o c_code/2_2/cgmeth.o c_code/2_2/lambdalifting.o c_code/2_2/lowerings.o c_code/2_2/vm.o c_code/2_2/vmgen.o c_code/2_2/vmdeps.o c_code/2_2/evaltempl.o c_code/2_2/aliases.o c_code/2_2/patterns.o c_code/2_2/semmacrosanity.o c_code/2_2/semparallel.o c_code/2_2/cgen.o c_code/2_2/ccgutils.o c_code/2_2/cgendata.o c_code/2_2/ccgmerge.o c_code/2_2/jsgen.o c_code/2_2/passaux.o c_code/2_2/depends.o c_code/2_2/docgen2.o c_code/2_2/service.o c_code/2_2/modules.o  -ldl -lm
SUCCESS
[rjammalamadaka@localhost csources]$ cd ..
[rjammalamadaka@localhost Nim]$ bin/nim c koch
config/nim.cfg(53, 2) Hint: added path: '/home/rjammalamadaka/.babel/pkgs/' [Path]
config/nim.cfg(54, 2) Hint: added path: '/home/rjammalamadaka/.nimble/pkgs/' [Path]
Hint: used config file '/home/rjammalamadaka/Nim/config/nim.cfg' [Conf]
Hint: used config file 'koch.nim.cfg' [Conf]
Hint: system [Processing]
lib/system.nim(147, 40) Warning: unknown magic 'Addr' might crash the compiler [UnknownMagic]
lib/system.nim(152, 39) Warning: unknown magic 'TypeOf' might crash the compiler [UnknownMagic]
lib/system.nim(229, 62) Warning: unknown magic 'DotDot' might crash the compiler [UnknownMagic]
lib/system.nim(237, 59) Warning: unknown magic 'DotDot' might crash the compiler [UnknownMagic]
lib/system.nim(3210, 31) Warning: unknown magic 'Plugin' might crash the compiler [UnknownMagic]
lib/system.nim(3242, 31) Warning: unknown magic 'ProcCall' might crash the compiler [UnknownMagic]
lib/system.nim(3251, 44) Warning: unknown magic 'Roof' might crash the compiler [UnknownMagic]
lib/system.nim(3269, 34) Warning: unknown magic 'XLenStr' might crash the compiler [UnknownMagic]
lib/system.nim(3270, 37) Warning: unknown magic 'XLenSeq' might crash the compiler [UnknownMagic]
Hint: koch [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: times [Processing]
lib/pure/times.nim(585, 30) Info: instantiation from here
lib/system.nim(229, 62) Warning: unknown magic 'DotDot' might crash the compiler [UnknownMagic]
Hint: posix [Processing]
Hint: parseopt [Processing]
lib/pure/parseopt.nim(59, 34) Warning: quoteIfContainsWhite is deprecated [Deprecated]
Hint: osproc [Processing]
Hint: strtabs [Processing]
Hint: hashes [Processing]
Hint: streams [Processing]
Hint: cpuinfo [Processing]
Hint: linux [Processing]
lib/pure/osproc.nim(647, 4) Error: undeclared identifier: 'defer'
[rjammalamadaka@localhost Nim]$ 

Thanks,
Raj

**Comment by kirbyfan64** [comment]
Why don't you try using the `devel` branch for both repositories?

**Comment by rjammala** [comment]
devel branch works. Thanks.

**Comment by Araq** [comment]
Oh yeah we need to update the csources master branch. Thanks for reporting!

**Comment by Araq** [comment]
Works for me now. Please reopen if still a problem.

**Comment by rjammala** [comment]
Thanks for fixing it @Araq

**Comment by GrahamStJack** [comment]
I hit this problem too, and ended up working around it by deleting my Nim clone and creating a new one. The problem is that ./build.sh doesn't update the csources clone if it already exists, and for that matter doesn't make sure Nim and csources are both on the same branch.
