### ISSUE TITLE
`[]=` broken for CountTables

### ISSUE THREAD

**Issue by boydgreenfield** [Araq/Nim#2625]
`[]=` is broken for CountTables as of 5fbcf93860e68d7ddde4b01aa4b7222a7fcaaabc. Specifically, it seems to break w/ over 64 elements. `inc()` does work however.

The following code does not work:

```nim
import tables
var substr_counts: CountTable[string] = initCountTable[string]()
var my_string = "Hello, this is sadly broken for strings over 64 characters. Note that it *does* appear to work for short strings."
let s_len = 32
for i in 0..(my_string.len - s_len):
  let s = my_string[i..i+s_len-1]
  substr_counts[s] = 1
  # substr_counts[s] = substr_counts[s] + 1  # Also breaks, + 2 as well, etc.
  # substr_counts.inc(s)  # This works
  echo "Iteration ", i

echo "And we never get here."
```

Here's a [gist](https://gist.github.com/boydgreenfield/9c742c3f9c0ca6eff31c) with a reproduction using the code before and after that commit. I'm not sure what infinite loop bug is being referenced in the original commit, 5fbcf93860e68d7ddde4b01aa4b7222a7fcaaabc, but happy to try and dive in / help out if somebody can point me to it (so we address *both* issues).

**Comment by Araq** [comment]
Works for me on win32 when I define 'const s_len = 64'. Please be more specific.

**Comment by boydgreenfield** [comment]
Sorry – the above is missing the `s_len` definition from the gist, which I have as `let s_len = 32` (and fails). Edited above now.

I've tested this with the provided gist on OS X and Ubuntu and get the same issue. It prints: 
```
...
Iteration 59
Iteration 60
Iteration 61
Iteration 62
Iteration 63
```

And then hangs indefinitely. SIGINT'ing yields:

```
test_old.nim(9)       test_broken
tables.nim(824)          []=
tables.nim(785)          rawGet
SIGINT: Interrupted by Ctrl-C.
Error: execution of an external program failed
```
