### ISSUE TITLE
Compiler returns exit code 0 in case of `execution of an external program failed`

### ISSUE THREAD

**Issue by bluenote10** [Araq/Nim#2638]
I was experimenting with [nimrun](https://gist.github.com/flaviut/27c2dc9cd2d8f5ced4e4) and observed that Nim returns an exit code of 0 even though the C compilation fails. As a result, nimrun cannot detect that the overall compilation failed.

I take it that `execution of an external program failed` always means that the generated code is invalid, right? If this is true, it would be helpful to introduce a more specific error message (maybe a "codegen error" or simply "invalid code"). The current error message is pretty confusing, since it is unclear what "external program" failed -- to me, it even suggests that a system command is broken. Also, having a simple term like "invalid codegen" would simplify reporting/searching issues -- currently I never now how to refer to this type of error in the issue title.

**Comment by bluenote10** [comment]
The problem was caused by a small bug in nimrun.

**Comment by flaviut** [comment]
I've moved nimrun to it's own repo at this point, https://github.com/flaviut/nimrun, and also applied your patches.
Sorry about the bug, that was my fault, I only tested success cases.
