### ISSUE TITLE
generated install.sh does install "nim" compiler binary

### ISSUE THREAD

**Issue by dcreemer** [Araq/Nim#2647]
running the "install.sh" script (as described in [install.txt](https://github.com/Araq/Nim/blob/devel/install.txt)) doesn't actually install the binary. Search for "$bindir" in the script -- only the directory is created.

**Comment by def-** [comment]
That's strange that the release has a broken install.sh. When I manually run `tools/niminst/niminst --var:mingw=none --var:version=0.11.0 --main:compiler/nim.nim scripts compiler/installer.ini` in the devel branch the resulting install.sh contains this:

```
  cp bin/nim $bindir/nim
  chmod 755 $bindir/nim
```

**Comment by def-** [comment]
This has been fixed in 0.11.2.
