### ISSUE TITLE
Non-ref object conversion gives runtime [ObjectConversionError]

### ISSUE THREAD

**Issue by Perelandric** [Araq/Nim#2658]
This code...
```
type
  Parent = object of RootObj
  Child = object of Parent
    s: string

var p:Parent = Child(s:"foobar")  # var p = Parent()  # Also causes the error

var c = Child(p) # error here
```

Causes this runtime error...
>unhandled exception: invalid object conversion [ObjectConversionError]

According to the manual, a qualifying criteria for explicit conversion is:

```
if isSubtype(a, b) or isSubtype(b, a): return true
```

And the `isSubtype` qualification for an object is:

```
    of object:
      var aa = a.baseType
      while aa != nil and aa != b: aa = aa.baseType
```

Unless I'm just misunderstanding the type relationships, this seems like a bug, since if `a` is `Child`, its `baseType` would be `Parent`, which would equal the type of  `b`.

If I am misunderstanding how types relate, then shouldn't it at least be a compile-time error?

**Comment by fowlmouth** [comment]
* docs should be updated, the error is good
* there should also be an error when you do `var p: Parent = Child(s: "..")` because data is lost (string s wont fit in a Parent)

**Comment by Perelandric** [comment]
Thanks fowlmouth. I did wonder how it could work without a pointer. Makes sense that it doesn't.

**Comment by Araq** [comment]
Not a bug.
