### ISSUE TITLE
nimsuggest doesn't work more than once on the non-main file

### ISSUE THREAD

**Issue by reactormonk** [Araq/Nim#2694]
I've done the experimentation with my epc branch, but I haven't changed anything essential except for the frontend.

When calling `nimsuggest` with `tests/caas/main.nim` as argument and running a few suggests against `main_dirty.nim` works just fine. But when I call `nimsuggest` with `compiler/nim.nim` as main file, it only works once and returns no results afterwards.

    $ nimsuggest compiler/nim.nim

Takes about 3s:

    > sug tests/caas/main.nim;tests/caas/main_dirty.nim:12:6
    sug     skField x       int     tests/caas/main.nim      5       4       ""
    sug     skField y       string  tests/caas/main.nim      6       4       ""
    sug     skTemplate      testability.tests       proc (body: stmt): stmt compiler/testability.nim 1       9       ""

Takes about 10s and no result:

    > sug tests/caas/main.nim;tests/caas/main_dirty.nim:12:6

Takes about 0.5s and no result:

    > sug tests/caas/main.nim;tests/caas/main_dirty.nim:12:6

The problem is also reproducible with a file inside the compiler tree, this example is just easier to setup.

**Comment by pigmej** [comment]
I can reproduce it with aporia

Steps:
* install recent aporia 
* enable suggest
* open `compiler/nim.nim`
* write `foo.` at the end, hit `ctrl+space` to toggle completion
* it will work, repeat previous several times, everything will be fine (?)
* open new file `compiler/ast.nim`, write `foo.` and `ctrl + space` in this file, and red box wil appear "No completions" (or something like that).

Is seems that completions in aporia (and in nimsuggest) is working quite ok, only when the completing file is `projectFile` argument. Aporia spawns `nimsuggest` with `projectFile` to the first file where completion was triggered.

Obviously exactly the same happens without aporia as @reactormonk  described
