### ISSUE TITLE
Pure sugar: postfix `if`-statements

### ISSUE THREAD

**Issue by ozra** [Araq/Nim#2713]
A purely sugary feature request, which I know many appreciate.

For early return pattern coding, I most oftenly write it like this (in LiveScript, for those parts of coding i do in the web part of the world):
```livescript
say = (...args) -> console.log.apply(@, args)

some-fn = (a, b) ->
    return 0  if a == 0
    return -1  if b == 47
    say "We passed the early return tests, let's calc..."
    return b / a

foo = some-fn 3, 47
```

The great benefit of postfix if-statements imo are that you can state your intent and focus the reader on certain parts of your statement / expression much more clearly.
In the example above for instance, `return` is a hot statement to a coder - you see a line with return ... and you will look harder, reading the condition. When seeing an if-statement, it's easier to just glance over, when reviewing code for the millionth time, while developing.
Good thing (TM)

**Comment by reactormonk** [comment]
That's a bit harder IIRC, because the syntax is very pythonic. Feel free to tinker in the lexer/parser to get that syntax running.

**Comment by ozra** [comment]
I could imagine. Well, then I've got some interesting things to delve into when I gradudate Nim noob school.

**Comment by def-** [comment]
I don't think the currently possible version looks bad, and postfix `if`s confuse me when I just scan lines to grasp the control flow of a proc. But as so many proposed syntax changes, it mostly comes down to personal preferences:

```nimrod
proc someFn(a, b: int): float =
  if a == 0:
    return 0
  if b == 47:
    return -1

  echo "We passed the early return tests, let's calc..."
  result = b / a

let foo = someFn(3, 47)
```

**Comment by reactormonk** [comment]
Very unlikely to happen.

**Comment by dom96** [comment]
If you are dead set on getting this feature implemented then I would suggest creating a thread on the forum about it, or chatting with Araq on IRC.

I do however believe that it is unlikely to happen. At least for 1.0.

**Comment by ozra** [comment]
@def-  - I hear you, it is kind of an 'aquired taste' (well, like everything), I use it almost exclusively for early return, which makes it an obvious recurring pattern, and soon it's readable with eyes closed. In the middle of procs, it can definitely throw of the flow - but that is up to project coding style standards ofc.

@dom96 - I've lived without it in C++ for aeons, so it won't kill me. My current situation involves re-implementing a system from the ground up, which is an opportunity to replace C++. Nim looks promising, even though I know that I then also have to consider some extra 'lost' time for changing situations since it is not 1.0, but I also know that I'll consistently waste time for every line of C++ I write. Well, what I'm trying to say: implementing this feature is not my highest prio atm, and since no one else seems to desire it, I guess it's better to keep new features minimal before 1.0.

I would be happy to raise the issue and implement it in a post 1.0 version if there's any interest by then. Right now, dirty jobs has to get done.
