### ISSUE TITLE
koch boot failing on Ubuntu 14.04 x86_64

### ISSUE THREAD

**Issue by jagtesh** [Araq/Nim#2714]
Partial console trace:

    ...
    Hint: guards [Processing]                                                                                                                                                         
    Hint: xmltree [Processing]
    Hint: cgi [Processing]
    Hint: cookies [Processing]
    Hint: typesrenderer [Processing]
    Hint: transf [Processing]
    Hint: cgmeth [Processing]
    Hint: lambdalifting [Processing]
    Hint: lowerings [Processing]
    Hint: vm [Processing]
    Hint: vmgen [Processing]
    Hint: vmdeps [Processing]
    Hint: vmmarshal [Processing]
    Hint: evaltempl [Processing]
    Hint: aliases [Processing]
    Hint: patterns [Processing]
    Hint: semmacrosanity [Processing]
    Hint: semparallel [Processing]
    Hint: plugins [Processing]
    Hint: active [Processing]
    Hint: locals [Processing]
    Hint: cgen [Processing]
    Hint: ccgutils [Processing]
    Hint: cgendata [Processing]
    Hint: ccgmerge [Processing]
    Hint: jsgen [Processing]
    Hint: passaux [Processing]
    Hint: depends [Processing]
    Hint: docgen2 [Processing]
    Hint: service [Processing]
    Hint: net [Processing]
    Hint: rawsockets [Processing]
    Hint: modules [Processing]
    Hint: nodejs [Processing]
    gcc -c  -w  -I/opt/Nim/lib -o compiler/nimcache/compiler_nim.o compiler/nimcache/compiler_nim.c
    Error: execution of an external program failed
    FAILURE

I'm clueless. Any help will be greatly appreciated. Thanks in advance!

**Comment by yglukhov** [comment]
Can you run gcc manually? In the Nim repo root dir:
```sh
$ gcc -c  -w  -I/opt/Nim/lib -o compiler/nimcache/compiler_nim.o compiler/nimcache/compiler_nim.c
```

**Comment by fowlmouth** [comment]
Add `--parallelbuild:1` to the `koch` args to see the error

**Comment by jagtesh** [comment]
Thanks for the suggestions @yglukhov, @fowlmouth

    gcc -c  -w  -I/opt/Nim/lib -o compiler/nimcache/compiler_nim.o compiler/nimcache/compiler_nim.c

Produces no output and `echo $?` returns 0

This is the output with `--parallelbuild:1`

    ...
    Hint: modules [Processing]
    Hint: nodejs [Processing]
    gcc -c  -w -O3 -fno-strict-aliasing  -I/opt/Nim/lib -o compiler/nimcache/compiler_nim.o compiler/nimcache/compiler_nim.c
    Error: execution of an external program failed
    FAILURE

**Comment by Araq** [comment]
I've seen this happen for systems with less than 1 GB of RAM, it's likely an out of memory failure. Enable a swap partition.

**Comment by jagtesh** [comment]
@Araq you were right. It was on a VM with limited memory. Enabling swap did the trick. Thanks so much! We should probably add this as a Troubleshooting tip somewhere. I'll be happy to do that if someone could tell me where.
