### ISSUE TITLE
algorithm.nim fix comment

### ISSUE THREAD

**Issue by apense** [Araq/Nim#2719]
Line 246 in algorithm.nim (https://github.com/Araq/Nim/blob/c30d7c3208c1da91e3f71be7d8d9f5149f3031c4/lib/pure/algorithm.nim#L246) references changing once #853 is fixed, which it was in c36619f. Should be changed or comment removed.

**Comment by dom96** [comment]
Perfect candidate for a PR :)

**Comment by apense** [comment]
I actually didn't notice how easy it was. #2733 should fix it, I think. Also changed `result = @[]` to `result = newSeq[T]()`. Is this preferred? I can revert if not

**Comment by yglukhov** [comment]
So... This can be closed, right?

**Comment by Varriount** [comment]
@yglukov Just so you know, if you put something like "fixes #____" in a commit, (where the underscores are an issue number) then when we pull in and merge that commit, the issue automatically closes. It makes it much easier to track issues.

**Comment by Varriount** [comment]
Er, @yglukhov (Sorry, on phone)

**Comment by yglukhov** [comment]
@Varriount, yep, pity though I didn't make that commit ;)
