### ISSUE TITLE
GTK bindings list

### ISSUE THREAD

**Issue by ozra** [Araq/Nim#2720]
Sorry if this is not the right place to issue this:

I noticed that the language bindings list at gtk is missing Nim: http://www.gtk.org/language-bindings.php

Could be good to have there to increase exposure and adoption.

**Comment by reactormonk** [comment]
Could someone comment how well the GTK2/3 are supported?

**Comment by Senketsu** [comment]
Well, so far i had no issue with gtk2 but it's huge lib so..
But i can tell its not fully binded (gtk2) like x11 bindings are missing so i had to make my own additional wrapper but i guess thats not big deal for general use.

**Comment by Araq** [comment]
Not our bug.
