### ISSUE TITLE
newLit doesn't create a bool

### ISSUE THREAD

**Issue by Perelandric** [Araq/Nim#2726]
Using `newLit(false).treeRepr` shows `IntLit 0`.

If I use `parseExpr("false").treeRepr`, it shows `Ident !"false"`, which works as a `bool` in a program, so I assume this is meant to be the correct AST representation of a `bool` literal.

>Nim Compiler Version 0.11.2 (2015-05-13) [Linux: amd64]
>Copyright (c) 2006-2015 by Andreas Rumpf
>
>git hash: c30d7c3208c1da91e3f71be7d8d9f5149f3031c4

**Comment by Araq** [comment]
That's how 'false' is represented internally though. No bug here.

**Comment by Perelandric** [comment]
@Araq: But it doesn't work in practice. The value results in a compile time error when used.

```
import macros

macro test(): stmt =
  result = newLetStmt(ident("foo"), newLit(true))

test()

if foo:
  echo "success"
```

Expected: `"success"`

Actual: `Error: type mismatch: got (int) but expected 'bool'`

It works if I replace `newLit(true)` with `ident("true")`. I'd do a PR to fix it and the `boolVal()` proc if it's indeed a bug.

**Comment by fowlmouth** [comment]
Just played around testing and found this, bool representation is not consistent:
```nim
import macros
macro z (b:typed): stmt =
  echo b.lispRepr
z true # sym true
z true == true # intlit 1
```
