### ISSUE TITLE
The "times" library misspells "milliseconds" in an object field

### ISSUE THREAD

**Issue by Perelandric** [Araq/Nim#2727]
From the `times` library, the field representing milliseconds in the `TimeInterval` type is misspelled as "miliseconds" (one 'l' instead of two):

```
TimeInterval = object 
  miliseconds*: int           ## The number of miliseconds
  seconds*: int               ## The number of seconds
  minutes*: int               ## The number of minutes
  hours*: int                 ## The number of hours
  days*: int                  ## The number of days
  months*: int                ## The number of months
  years*: int                 ## The number of years
```

A few code comments throughout make the same spelling error.

https://github.com/Araq/Nim/search?utf8=%E2%9C%93&q=miliseconds

**Comment by reactormonk** [comment]
Just make a PR.

**Comment by dom96** [comment]
yes, but provide a proc with the old name but add a ``{.deprecated.}`` pragma to it.

**Comment by Perelandric** [comment]
@dom96 The only related proc that I can see is `initInterval`. Are you suggesting a new proc with a new name?

**Comment by kirbyfan64** [comment]
@Perelandric

```nimrod
proc miliseconds(t: TimeInterval): int {.deprecated.} = t.milliseconds
```

**Comment by Perelandric** [comment]
I see what you mean, though the `initInterval` has a parameter misspelled too, which can break code when fixed. Anything special need to be done there?
