### ISSUE TITLE
noSideEffect/func should not be able to call non-noSideEffect/non-func

### ISSUE THREAD

**Issue by nanoant** [Araq/Nim#2741]
Calling proc having side-effect (not marked `{.noSideEffect.}`) should be prohibited from `{.noSideEffect.}` functions.

Otherwise we risk letting many hard to trace bugs live.

Eg.

~~~nim
proc add1(i: int): int {.noSideEffect.} = i + 1
proc add2(i: int): int                  = add1(add1(i))
proc add3(i: int): int {.noSideEffect.} = add1(add2(i))

echo add3(3) #<- lets me chain-call side-effect proc add2 :(
~~~

**Comment by def-** [comment]
But `add2` has no sideeffects. If you add a sideeffect comilation fails, as expected:

```nimrod
proc add1(i: int): int {.noSideEffect.} = i + 1
proc add2(i: int): int =
  echo "foo"
  add1(add1(i))
proc add3(i: int): int {.noSideEffect.} = add1(add2(i))

echo add3(3)
```

**Comment by nanoant** [comment]
Yeah, you are absolutely right. Sorry about that. Thanks for clarifying that.

**Comment by nanoant** [comment]
@def- FYI I made wrong assumption that reason #2742 fails to compile is that Nims allows that behavior, but it doesn't. However in fact Nim's probably does not make enough checks for side-effects, see #2742.
