### ISSUE TITLE
`type` block enforces togetherness (type scope)

### ISSUE THREAD

**Issue by apense** [Araq/Nim#2744]
This is fine:

```nim
type
  Node = ref NodeObj
  NodeObj = object
    le, ri: Node
    data: int
```

This generates an error:
```nim
type
  Node = ref NodeObj

type
  NodeObj = object
    le, ri: Node
    data: int
```

Unless I am missing something, this has changed recently. I don't remember the compiler enforcing the type declarations' togetherness.

**Comment by apense** [comment]
BTW the error is `test.nim(3, 14) Error: undeclared identifier: 'NodeObj'`

**Comment by kirbyfan64** [comment]
To quote [Tutorial part 2](http://nim-lang.org/docs/tut2.html#object-oriented-programming-mutually-recursive-types):

>  In Nim these types can only be declared within a single type section. (Anything else would require arbitrary symbol lookahead which slows down compilation.)

It's been like that ever since I started using Nim (somewhere around a year ago).

**Comment by apense** [comment]
Yikes! My mistake! Thank you!
