### ISSUE TITLE
[Question] Is it possible to disable heap?

### ISSUE THREAD

**Issue by frol** [Araq/Nim#2746]
I'm asking this question on behalf of readers of [my article about Nim](http://habrahabr.ru/post/258119/).

They want to know whether Nim is useful for low-level programming (kernel/drivers/etc).

Thank you!

**Comment by def-** [comment]
First, thanks for translating my article! Great to see it getting so many readers! Now, about your answer:

Yes, you can do low-level stuff in Nim:
- https://github.com/dom96/nimkernel
- https://github.com/ckkashyap/rustix/issues/8
- http://hookrace.net/blog/nim-binary-size/
- https://github.com/def-/nim-small-coreutils

They also asked about what else has been written in Nim:
- http://hookrace.net/blog/porting-nes-go-nim/

**Comment by frol** [comment]
Thank you!
