### ISSUE TITLE
Invalid indentation on implicit result with multiline binary operators

### ISSUE THREAD

**Issue by apense** [Araq/Nim#2776]
It seems like having an implicit `result` still expects indentation like a normal `result`. Not sure if this is intentional.

Example
```nim
proc ortest(): int =
  ## fine
  3 or 4 or
    5
proc ortest2(): int =
  ## fails, like ortest3()
  result = 3 or 4 or
  5
proc ortest3(): int =
  ## fails
  3 or 4 or
  5
```

Does the same thing with all binary operators I tried (logical and arithmetic) including `+`, etc.

I likely missed something in the tutorial, *but* it seems like since
```nim
proc test(): bool =
  result = true or
           false ## the true and false are aligned
```
works, not declaring `result` explicitly should support similar indentation

**Comment by kirbyfan64** [comment]
You `5` in the last two examples needs to be indented a bit more. Think of the indentation relative to everything else. In the last two examples, there is no extra indentation in comparison to the line above it. In the first one and the tutorial example, there is.

**Comment by apense** [comment]
Oh I understand why the second test fails. It just seemed a little odd when doing multilines without an explicit `result` needs an indent as if you already wrote `result`. I was doing:

```nim
pb(a, bit, 0)         or pb(b, bit, 1)       or pb(c, bit, 2)       or pb(d, bit, 3)       or
pb(a, bit +  8, 4)  or pb(b, bit +  8, 5)  or pb(c, bit +  8, 6)  or pb(d, bit +  8, 7)   or
pb(a, bit + 16, 8)  or pb(b, bit + 16, 9)  or pb(c, bit + 16, 10) or pb(d, bit + 16, 11)  or
pb(a, bit + 24, 12) or pb(b, bit + 24, 13) or pb(c, bit + 24, 14) or pb(d, bit + 24, 15)
```

for an AES routine, but now I have
```nim
pb(a, bit, 0)         or pb(b, bit, 1)       or pb(c, bit, 2)       or pb(d, bit, 3)       or
      pb(a, bit +  8, 4)  or pb(b, bit +  8, 5)  or pb(c, bit +  8, 6)  or pb(d, bit +  8, 7)   or
      pb(a, bit + 16, 8)  or pb(b, bit + 16, 9)  or pb(c, bit + 16, 10) or pb(d, bit + 16, 11)  or
      pb(a, bit + 24, 12) or pb(b, bit + 24, 13) or pb(c, bit + 24, 14) or pb(d, bit + 24, 15)
```

which just didn't look as nice. It's not a problem really, it's just not obvious unless you write out `result` (which is why I guess it's not recommended to omit it :stuck_out_tongue_closed_eyes: )

**Comment by kirbyfan64** [comment]
But, in the example without `result`, you're indenting it! The second line is preceded by more spaces than the first. With the other two, they're on the same level.

**Comment by apense** [comment]
Ah yeah. I know why the first result works. I just think it would be nice to line them up row after row. But really, I get why it's happening. No issue here, really. I'll close.

**Comment by kirbyfan64** [comment]
Well, not sure about Nim, but I know that Python lets you end a line with a slash and continue it on the next line with whatever indentation. Maybe Nim has that too?
