### ISSUE TITLE
Wrong indentation produced for Macro containing do { } while()

### ISSUE THREAD

**Issue by jlp765** [Araq/Nim#2781]
c2nim:

    #define SET_REAL(zp,x) do {(zp)->dat[0]=(x);} while(0=1)

produces 

    template SET_REAL*(zp, x: expr): stmt =
      while true:
      (zp).dat[0] = (x)
      if not 0 = 1: break

which doesn't indent the body of the while loop

**Comment by reactormonk** [comment]
c2nim got its own repo now: https://github.com/nim-lang/c2nim/issues
