### ISSUE TITLE
logging inconsistencies

### ISSUE THREAD

**Issue by yglukhov** [Araq/Nim#2827]
This is a proposal to change logging module interface in a breaking manner before 1.0 release. The following entities:
```nim
template log*(level: Level, frmt: string, args: varargs[string, `$`])
template debug*(frmt: string, args: varargs[string, `$`])
template info*(frmt: string, args: varargs[string, `$`])
template warn*(frmt: string, args: varargs[string, `$`])
template error*(frmt: string, args: varargs[string, `$`])
template fatal*(frmt: string, args: varargs[string, `$`])
method log*(logger: Logger, level: Level, frmt: string, args: varargs[string, `$`])
```
need to be changed to not have any frmt string to output their arguments just as echo does. Reasoning:
1. Consistent with echo
2. Easier to use
3. frmt functionality still would be easily achieved: ``info MY_FORMAT % [MY_ARGS]``
4. Easier and clearer to implement Logger (backend). E.g. console.log in JavaScript takes vararg, which is prettified in browser console. Dealing with frmt it is not clear how to pass the arguments to console.log.
5. I can't think of a Logger implementation where frmt would not just end up with ``frmt % args`` (as it is seen from current state of logging.nim), so it is really redundant.
6. Performance: in case of multiple loggers formatting is done in every one of them.

For C guys we could introduce ``logf, debugf, infof, etc...`` instead.

**Comment by dom96** [comment]
:+1:

**Comment by yglukhov** [comment]
Also I would vote against the ``substituteLog``-related functionality, because it is a task of a particular logger backend to decide whether he should print app name, timetamp, etc. E.g. Android's NDK logging API prints the timestamp and package name automatically. Same for MacOS/iOS NSLog. So delegating this task to the user (as it is currently done) obliges him to think of cross-platform details.

What do you think? Can't wait to do a PR on this. Should I?

**Comment by Araq** [comment]
:+1:

**Comment by bluenote10** [comment]
:+1: 

I'm in general not a big fan of ```varargs[string, `$`]``` since it has drawbacks in terms of usability ([example](http://forum.nim-lang.org/t/1235)) and performance (many calls to `sprintf` instead of the one required).

> For C guys we could introduce logf, debugf, infof, etc... instead.

If the language would feature a [general wrapper for `snprintf`](https://github.com/bluenote10/nim-stringinterpolation), this would not be necessary. Just saying :).

**Comment by dom96** [comment]
Closed via 2830
