### ISSUE TITLE
Bad indexing info in the manual

### ISSUE THREAD

**Issue by jaco60** [Araq/Nim#2843]
In the "Array and sequence types" section of the manual, the second-to-last paragraph writes:

"The notation x[i] can be used to access the i-th element of x."

It should be "The notation x[i] can be used to access the *x.low + i-th* element of x." as, for fixed arrays, the index range could be 5..10, for example (in which case, x{1] is invalid...)

I admit that, with the example given, x is indexed starting from 0, but a more general information about indexing would be better, imho

**Comment by Araq** [comment]
It's not specified what the 'i-th' element means so the manuals is fine.

**Comment by jaco60** [comment]
Well... For me, the 4th element is the 4th element ☺
If x is indexed from 3 to 10, x[4] is not the 4th élément, but the
second...

**Comment by Araq** [comment]
Ever since some programming languages started counting at 0, *nobody* knows what the 'i-th' element is.
