### ISSUE TITLE
Colors!

### ISSUE THREAD

**Issue by kirbyfan64** [Araq/Nim#2845]
This is a feature request that I'd *really* like to see before 1.0 hits. Basically: colored output from the compiler. When an error message appears, the word `error` would be red, the word `hint` could be green or purple, and so forth. I can make a PR, though someone would need to try it under Windows (I'm using Ubuntu).

**Comment by Varriount** [comment]
I can test it on Windows.

**Comment by ozra** [comment]
This would be nice! Optional of course?

**Comment by ozra** [comment]
Vote for errors red, warnings 'dark "non bold" yellow', the rest default color...

**Comment by Abrasax-** [comment]
:+1: great idea
