### ISSUE TITLE
Unexpected case range requirements

### ISSUE THREAD

**Issue by apense** [Araq/Nim#2860]
When writing something like

```nim
proc test(j: int) =
  case j
  of < 0:
    echo "invalid"
  of <= 15:
    echo "hello"
  else:
    discard
```
it doesn't work like you would think. Rather, you seem to need to write
```nim
proc test(j: int) =
  case j
  of < 0:
    echo "invalid"
  of < 15, 15:
    echo "hello"
  else:
    discard
```

It is probably an easy fix, but I'm not sure where to start.

**Comment by dom96** [comment]
The ``of < 0`` doesn't check whether ``j`` is less than 0. It checks whether ``j`` is ``-1``. Similar for the other branch. This is because of the unary ``<`` operator which is the same as ``0-1``.

**Comment by apense** [comment]
Ohh. You're right. The manual refers to the case statement and *slicelist*, which it doesn't define, but I'm guessing it's a set of the branches. If you want to do something like matching ranged in a case statement, I assume you should either use a range or if/else?
I guess that's just a subtlety of the language I didn't know before. Thanks for clearing it up.

**Comment by apense** [comment]
Closing because answered.
