### ISSUE TITLE
httpclient async requests with method httpPOST isn't sending Content-Length header

### ISSUE THREAD

**Issue by esibun** [Araq/Nim#2884]
Self-explanatory. If the body field is set, the method needs to send the Content-Length header for the HTTP server to accept the data alongside the request.

```
data = "example=data"
var httpClient = newAsyncHttpClient()
var resp = await httpClient.request("http:/example.com/" % apiUrl, httpMethod = httpPOST, body = data)
```

Expected:
> POST / HTTP/1.1
> Host: example.com
> Connection: Keep-Alive
> User-Agent: Nim httpclient/0.1
> Content-Length: 12
>
> example=data

Actual:
> POST / HTTP/1.1
> Host: example.com
> Connection: Keep-Alive
> User-Agent: Nim httpclient/0.1
>
> example=data

This is causing my server to reject the POST data.

**Comment by dom96** [comment]
Let me know if this works.

**Comment by esibun** [comment]
Seems to be working on my end, thanks for the fix.
