### ISSUE TITLE
writeFile suggestion

### ISSUE THREAD

**Issue by vegansk** [Araq/Nim#2888]
This suggestion is for this function in system.nim: ```proc writeFile(filename, content: string)```. It fails with existing ```filename``` and can be used only for creating new files because of ```fmWrite``` flag. Maybe we should add to it an additional boolean parameter ```overwrite``` with default value equal to false?

**Comment by reactormonk** [comment]
What does the current nim look like to achieve the same?

**Comment by vegansk** [comment]
Oops, it was my fault, thats why IOError was thrown!
