### ISSUE TITLE
Unexpected idetools behaviour

### ISSUE THREAD

**Issue by gradha** [Araq/Nim#325]
Using the idetools.nim file from https://gist.github.com/4702621 as an example, running the idetools command on the line 11, column 38 (cursor placed on the ``s`` of the ``str_val`` word) returns the the ``in`` template from lib/system.nim which is not present on that line:
```
def	skTemplate	system.in	proc (expr, expr): expr	/Users/gradha/project/nimrod/root/lib/system.nim	702	10	""
```
Other columns give unexpected values too. For instance, column 32 of that line will point to the ``str_val`` definition of line 7 instead of pointing to the ``$`` proc from the system module. From the whole ``str_val`` word, the first ``s`` points to the ``in`` template, but the rest returns nothing. The surrounding ampersands point correctly to system's ``&`` proc.

The expected behaviour for the ``str_val`` word (columns 38-44) would be to jump to line 7.

**Comment by Araq** [comment]
This bug even exists in the new nimsuggest. Very strange bug.
