### ISSUE TITLE
nimrod serve crashes on wrong usage

### ISSUE THREAD

**Issue by reactormonk** [Araq/Nim#344]
nimrod serve --server.type:stdin foo.nim
    idetools --track foo.nim,1,1 --suggest
    command line(1, 1) Error: argument for command line option expected: 'track'
    command line(1, 1) Error: 'FILE,LINE,COLUMN' expected
    command line(1, 1) Error: `ów is not a valid number
    SIGSEGV: Illegal storage access. (Attempt to read from nil?)

**Comment by Araq** [comment]
Nimsuggest is the future.
