### ISSUE TITLE
C++ codegen improvements

### ISSUE THREAD

**Issue by fowlmouth** [Araq/Nim#346]
In C++ mode, variables should be declared at the same place they're declared in your nimrod code, for example this gist shouldn't instantiate TFoo before returning, TFoo could be a class with a constructor with side-effects. https://gist.github.com/fowlmouth/5009626

On constructors, a new mechanism is required to access them. I tried to do it with templates with not much success.
```nimrod
template newWindow*(name: expr, arg1, arg2, arg3): stmt {.immediate,dirty.} =
  var name {.noDecl.}: TRenderWindow
  {.emit "sf::RenderWindow `name`(`arg1`, `arg2`, `arg3`);".}
```

We should also figure out what to do about const and reference(&) types. I think that `let` could be used in most cases for const types, but this definitely needs more research.

**Comment by Araq** [comment]
Has been implemented.
