### ISSUE TITLE
Forward declaration of exported proc modifies its visibility

### ISSUE THREAD

**Issue by gradha** [Araq/Nim#350]
Given the following file t1.nim:
````
proc forward(a: int)

proc normal*(b: int) =
  forward(b)

proc forward*(a: int) =
  echo "forward says: " & $a
````
and the following t2.nim:
````
import t1

when isMainModule:
  normal(2)
  forward(3)
````
Compilation of the t2 module yields the following error:
````
t2.nim(5, 9) Error: undeclared identifier: 'forward'
````
I would like the compiler to warn (or even fail compilation) forward declarations having a different visibility than their later implementation. At least in this case it seems that exporting the forward proc is wanted, yet the forward declaration effectively hides it.

As a sidenote, the error for the undeclared identifier points to the ninth column, I think it should point to the beginning of the word,

**Comment by Perelandric** [comment]
Is this considered fixed?

The code example from `t1.nim` yields:

>Error: public implementation 't1.forward(a: int)' has non-public forward declaration in t1.nim(20,5)

While an exported forward declaration does export an unexported implementation, it offers a convenient way to keep all your exports together at the top of a file.

**Comment by Araq** [comment]
Indeed, we fixed that. Docgen needs testing though.

**Comment by dom96** [comment]
``nim doc`` no longer generates duplicate entries, ``nim doc2`` raises the error. Assuming that is the correct behaviour.
