### ISSUE TITLE
Feature request: make "nimrod i" wrap output of evaluated expressions with repr()

### ISSUE THREAD

**Issue by ackalker** [Araq/Nim#369]
Example:
```
>>> var myseq = @[1,2,3]
>>> myseq
stdin(2, 5) Error: type mismatch: got (seq[int])
but expected one of: 
system.$(x: int): string
system.$(x: int64): string
system.$(x: cstring): string
system.$(x: TEnum): string
system.$(x: float): string
system.$(x: T): string
system.$(x: char): string
system.$(x: string): string
system.$(x: bool): string
```
Probably scares most of the Pythonista would-be Nimrod converts away.

Nicer:
```
>>> repr(myseq)
[1, 2, 3]
```
Aww, that's almost too much Python :-)

But the following doesn't work! :-(
```
>>> myseq = [1,2,3]
stdin(3, 9) Error: type mismatch: got (Array constructor[0..2, int]) but expected 'seq[int]'
```
More Pythonistas heading back to the snake pit :-/

Most useful would be something like:
```
>>> myseq
@[1, 2, 3]
```
This way, the output can be simply copy/pasted and edited to make a new sequence (which is what Python's 'repr' attempts to do, according to its docs: "return a string that would yield an object with the same value when passed to eval()", for simple cases).
I would like to help with a possible fix, but I don't know enough yet about Nimrod's interactive mode (in particular where the output of evaluation is generated) to know where to start.

**Comment by Araq** [comment]
There is no supported 'nim i' anymore.
