### ISSUE TITLE
idetools serve command seems to leak memory

### ISSUE THREAD

**Issue by gradha** [Araq/Nim#450]
When I run the following command inside nimrod's lib directory:
```
$ yes "idetools --def --track:system.nim,796,7" | \
  nimrod serve --server.type:stdin system.nim > /dev/null
```
and watch the process with the system monitor, the nimrod process starts with 30.2MB of total virtual memory usage. After about 4 minutes it has grown to 33.2MB and keeps increasing steadily.

Similarly, when I run https://github.com/gradha/the_hyperlink_vs_nimrod on itself in server mode, in the beginning it starts with 60MB virtual memory size, and about 14000 queries and 30 minutes later the process has grown to 360MB and keeps expanding.

**Comment by Araq** [comment]
nimsuggest uses markAndSweep.
