### ISSUE TITLE
Method recursion fails

### ISSUE THREAD

**Issue by EXetoC** [Araq/Nim#496]
```nimrod
type TObj = object of TObject
method f(o: TObj) = f(o) # 'proc' works.
```
Hint: system [Processing]
Hint: method_bug [Processing]
Traceback (most recent call last)
nimrod.nim(79)           nimrod
nimrod.nim(55)           HandleCmdLine
main.nim(487)            MainCommand
main.nim(256)            CommandCompileToC
main.nim(210)            CompileProject
main.nim(168)            compileModule
passes.nim(192)          processModule
passes.nim(136)          processTopLevelStmt
sem.nim(298)             myProcess
sem.nim(272)             SemStmtAndGenerateGenerics
semstmts.nim(1236)       semStmt
semexprs.nim(773)        semExprNoType
semexprs.nim(1924)       semExpr
semstmts.nim(1087)       semMethod
semstmts.nim(1025)       semProcAux
transf.nim(709)          transformBody
transf.nim(684)          processTransf
transf.nim(630)          transform
transf.nim(571)          transformCall
cgmeth.nim(39)           methodCall
Error: unhandled exception: sym is not accessible [EInvalidField]

**Comment by reactormonk** [comment]
Works at https://github.com/Araq/Nim/commit/9bd72fc0d96c1ce2e0c162b446346ec0e39712e2
