### ISSUE TITLE
Name mangling for closure environments can fail

### ISSUE THREAD

**Issue by rbehrends** [Araq/Nim#601]
For example, consider the following code:

```nimrod
for i in 1..1:
  let fname = "example"
  proc report(message: string) =
    echo(fname & ": " & message)

  for j in 1..1:
    report "a"
  report "b"
```

Here, the code may, e.g., try to use `HEX3Aenv_74044` when the actual name is `HEX3Aenv_74042` (the number is always off by 2).

This occurs only if: (1) the procedure is defined inside a for loop and (2) is called from both within and without a nested for loop.

**Comment by Araq** [comment]
Duplicate of some other lambda lifting bug.

**Comment by dom96** [comment]
Care to reference this other lambda lifting bug?
