### ISSUE TITLE
nimrod serve only answers the first request

### ISSUE THREAD

**Issue by reactormonk** [Araq/Nim#804]
To reproduce:

Start the server with

    cd $NIMROD_DIR/tests/caas
    nimrod serve --server.type:stdin idetools_api.nim
    
Which echos approx.

    config/nimrod.cfg(36, 2) Hint: added path: '/home/tass//.babel/pkgs/babel-0.1.0' [Path]
    config/nimrod.cfg(36, 2) Hint: added path: '/home/tass//.babel/pkgs/' [Path]
    Hint: used config file '/home/tass/dev/nimrod/Nimrod/config/nimrod.cfg' [Conf]

Then copy/paste (with the newline)

    c --verbosity:0 --hints:on
    
Which should echo

    tests/caas/idetools_api.nim(84, 4) Hint: 'notAModule' is declared but not used [XDeclaredButNotUsed]
    tests/caas/idetools_api.nim(15, 6) Hint: 'SOME_SEQUENCE' is declared but not used [XDeclaredButNotUsed]
    tests/caas/idetools_api.nim(22, 5) Hint: 'idetools_api.adder(a: int, b: int): int' is declared but not used [XDeclaredButNotUsed]
    tests/caas/idetools_api.nim(9, 5) Hint: 'idetools_api.test_iterators(filename: string)' is declared but not used [XDeclaredButNotUsed]
    tests/caas/idetools_api.nim(3, 5) Hint: 'idetools_api.test_enums()' is declared but not used [XDeclaredButNotUsed]
    tests/caas/idetools_api.nim(18, 2) Hint: 'TPerson' is declared but not used [XDeclaredButNotUsed]
    
But an additional (after the first finished) doesn't return anything.

    c --verbosity:0 --hints:on

    ^CSIGINT: Interrupted by Ctrl-C.

**Comment by Araq** [comment]
I'm closing this since it works in nimsuggest, at least, which is the future anyway.
